### ISSUE TITLE
Update the test suite?

### ISSUE THREAD

**Issue by jnweaver** [jarednova/timber#172]
I've been spending some time trying to make sense of the test environment for Timber (because I hope to contribute some to the project). 

As I was working with tests, I first wanted to get them running in my local environment (OSX), without using Vagrant, while not breaking the Travis CI tests.

I managed to get that working (see here: https://github.com/jnweaver/timber/commits/test_updates) with some changes to the bash installer:

* Switched the WP test suite from http://unit-tests.svn.wordpress.org to http://develop.svn.wordpress.org (which is the suite running in the Varying Vagrant Vagrants setup). Because the newer test suite comes with its own Wordpress source, the installer does not need to also install Wordpress.

* Changed the sed text replacements so that they'll work in both OSX and Linux. (OSX and linux handle in-place sed differently [it turns out](http://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux))

* Check to see if the Db exists before trying to create it

* Changed the path reference in tests/bootstrap.php to reflect the structure of the newer WP test suite

* Changed Travis config to test WP 3.7 and 3.8.1 because the current Wordpress test suite only goes back to 3.7. Also, because the test suite bundles its own Wordpress, testing against the github master branch is no longer possible. I guess you'd have to test against the trunk of http://develop.svn.wordpress.org?

* In phpunit.xml, suppress PHP notices from being converted to exceptions in PHPUnit. Many of the Timber tests trigger notices when tested against WP 3.8.1 because of the twentyfourteen_post_classes() filter calling has_thumbnail() when no $post global exists.

## Caveat

These changes work. The Travis tests pass and I can run the bash installer and then the phpunit tests successfully in my local environment.

But ... I imagine the goal is to be able to run tests against 3.5 still? But it seems like the tests should be running against the newer WP test suite which only goes back to 3.7. I'm not sure how to straddle both.

## Testing with Vagrant

After making the changes above, I also set up Vagrant for testing as described in the Timber wiki. I got it to work, but not quite as described in the wiki. To run the tests using the VVV environment, I had to ```vagrant ssh``` into the VM and then run phpunit from within the timber plugin directory. When doing so, it uses the newer WP test suite available in /www/wordpress-develop/. But most of the tests fail as above because of the notices generated due to the issue with the twentyfourteen_post_classes() filter and the fact that phpunit.xml is not suppressing conversion of notices to exceptions.

Anyway, I really love Timber and hope to contribute some, but wanted to make sure I had the tests working properly, hence this lengthy post! If I'm overlooking something with tests, please let me know!

**Comment by connorjburton** [comment]
Hi @jnweaver - I know this is really old and you might not remember, is this still an issue or can I close this? Just going through legacy issues to clear up the issues list.

Thanks

**Comment by jnweaver** [comment]
Oh, thanks. I'm closing it. If I get involved with Timber development again, I'll build a new test environment from scratch. I'm sure my issues were mostly from a lack of understanding on my part at that time (Vagrant and PHP testing was new to me then.)

**Comment by connorjburton** [comment]
Thanks for getting back to me :+1:
