### ISSUE TITLE
[suggestion] Twig fork of underscores anyone?

### ISSUE THREAD

**Issue by alexej-d** [jarednova/timber#203]
Hey guys,

Timber is a really neat piece of software, thank you for that!
Is there somebody using [underscores.me](https://github.com/Automattic/_s/) with Timber? Would be great to see it rewritten for Timber because it is a fantastic starter theme. I would do it myself but unfortunately my schedule does not allow this + I am just starting with Timber…

**Comment by connorjburton** [comment]
As we have a decent starter theme now I am going to go ahead and close this.
