### ISSUE TITLE
Rating Widget Plugin incompatible w Timber

### ISSUE THREAD

**Issue by dreamon11** [jarednova/timber#267]
Hi,

{{ function('wp_footer') }} in template doesn't call the scripts inside the wp_footer() Wordpress function.

I try with the default theme and scripts are loaded by wp_footer() function.

In single.php, i try to only call wp_footer() but it doesn't show anything.

However, when i write that, it's OK : 
while ( have_posts() ) : the_post();
the_content();
endwhile;
wp_footer();

When i write that, it's not OK : 
while ( have_posts() ) : the_post();
endwhile;
wp_footer();

Any solutions ?

Thanks !

**Comment by connorjburton** [comment]
Hi @dreamon11 - I know this is a really old issue, am I okay to close this?

Thanks

**Comment by dreamon11** [comment]
No problem ;)

**Comment by connorjburton** [comment]
Thanks for getting back to me! :)
