### ISSUE TITLE
Image resize relative to height

### ISSUE THREAD

**Issue by alexej-d** [jarednova/timber#280]
Would it be possible to implement something like this:
`<img src="{{item.thumbnail|resize(false, 200)}}">`
So that one can resize all images in a row to have the same height, but different widths according to their aspect ratio?
Thanks in advance!

**Comment by marciojcoelho** [comment]
Have you try
```
<img src="{{item.thumbnail|resize(0, 200)}}">
```

**Comment by tmyie** [comment]
`resize(0, 200)` works great.

**Comment by alexej-d** [comment]
Guys, thank you, but the question is already a year old. By the the time I asked this was not possible… Nevertheless thank you ;)
