### ISSUE TITLE
Poedit not finding gettext inside attribute 

### ISSUE THREAD

**Issue by jedrzejchalubek** [jarednova/timber#320]
Hi!

I have something like this in my .twig file:

```html
<input type="text" class="form-control" name="s" id="search" value="{{ searchquery }}" placeholder="{{ __('ENTER YOUR CITY', 'WK') }}" required>
```

And scanning twig files with Poedit not showup gettext inside placeholder attribute. Any advice?

Poedit setup as in tutorial https://github.com/jarednova/timber/wiki/Text-Cookbook#generating-po-files-using-poedit

**Comment by ocReaper** [comment]
Sadly Poedit could not search in stings, but [xgettext](https://github.com/Wisembly/xgettext-php) can. Take a try.
