### ISSUE TITLE
Clear the cache

### ISSUE THREAD

**Issue by asecondwill** [jarednova/timber#351]
What is the correct way / best practice for clearing the cache?

This works, but is a bit clumsy: 

````
// Timber::$cache = true;
$loader = new TimberLoader();
$loader->clear_cache_timber();
````

I found an issue that mentioned doing this: 

````
TimberLoader::clear_cache_timber();
````

but it isn't a static method. 

I updated the wiki with this a mo ago, but realised i was stretching a bit & deleted it.

**Comment by connorjburton** [comment]
I know this is really old, just clearing up issues. This was covered in #399

**Comment by asecondwill** [comment]
This is still super painful.  Note for next time im googling it.   
timber 1.x
wp debug - true

functions.php:
$loader = new TimberLoader();
$loader->clear_cache_timber();


Probably differnet in timber 2.x
