### ISSUE TITLE
TimberMenu works only with menu ID not name or slug

### ISSUE THREAD

**Issue by ynt** [jarednova/timber#364]
TimberMenu works only with menu ID not name or slug.

Menu parameters:

```
term_id: "9",
name: "top_sub",
slug: "top_sub",
term_group: "0",
term_taxonomy_id: "9",
taxonomy: "nav_menu",
description: "",
parent: "0",
count: "2",
ID: "9"
```

There is no problem with Initializing it by passing ID:

```
$context['menu_top_sub'] = new TimberMenu('9');
```

However, passing slug does not work:

```
$context['menu_top_sub'] = new TimberMenu('top_sub');
```

**Comment by connorjburton** [comment]
`TimberMenu` does support `slug`s when you are passing the `slug` of a registered menu. This may also have been added after this ticket was raised so i'm going to close this.

If it's still an issue please comment and I will re-open
