### ISSUE TITLE
Get image size warning

### ISSUE THREAD

**Issue by front-stream** [jarednova/timber#365]
When I try get size of the image {{image.width}} I got an error 

getimagesize(): Filename cannot be empty in app/wp-content/plugins/timber-library/functions/timber-image.php on line 53

where my image is: TimberImage(location.photo)

**Comment by connorjburton** [comment]
Hi @front-stream - I know this is an old one but is this still an issue for you?

**Comment by front-stream** [comment]
It is ok now, thanks for info
