### ISSUE TITLE
Conditionally disabling the Twig Cache Extension

### ISSUE THREAD

**Issue by mmikkel** [jarednova/timber#370]
If I wanted to completely disable the *partial cache* method (Twig Cache Extension) – say, in a local environment's config file – what would be the best/easiest way to accomplish this?

In staging/production I have the deploy script call a method to clear the cache for me – but locally it gets really old manually clearing the cache whenever I tweak the markup :)

**Comment by nexxome** [comment]
I just had the same question and if someone is interested here is my solution (here I just use the constant "WP_DEBUG" defined in wp-config.php):
        if ( WP_DEBUG ) {
            add_filter( 'timber/cache/mode', function ( $title ) {
                return 'none';
            } );
        }

**Comment by mmikkel** [comment]
Nice one, @nexxome! Thanks.
