### ISSUE TITLE
Post preview on published posts doesn't work

### ISSUE THREAD

**Issue by calder12** [jarednova/timber#375]
When creating a new post or editing a draft the preview function works fine. If you change the post from published to draft and save it the preview function works again. But as long as the post status is "published" the post preview doesn't update changes made.

**Comment by scottfatbeehive** [comment]
You can fix this in your controller temporarily by doing something like the following:

    $context['post'] = new TimberPost();
    if (is_preview() && $context['post'] && isset($_GET['preview_id'],$_GET['preview_nonce'])) {
        $context['post'] = apply_filters('the_preview',$context['post']);
    }

**Comment by billcolumbia** [comment]
Any updates on this?

**Comment by connorjburton** [comment]
Working on this #876

**Comment by connorjburton** [comment]
Going to close this one and can continue discussion in #876 if needed.
