### ISSUE TITLE
PHPRouter

### ISSUE THREAD

**Issue by mmikkel** [jarednova/timber#378]
Hello,

Implementing *routes* w/ Timber throws the following error (I've just installed 20.7 through Composer):

```php
Catchable fatal error: Argument 1 passed to PHPRouter\Router::__construct() must be an instance of PHPRouter\RouteCollection, null given
```

I (very briefly) looked into it, but there doesn't seem to be a "one-line" fix for this – if I add a *RouteCollection* instance to the Router instantiation I get the following:

```php
Fatal error: Call to undefined method PHPRouter\Router::map()
```

I guess there were some breaking changes w/ PHPRouter, and TimberRoute needs a refactor? Any ETA on this? If the issue isn't resolved I'm going to take a closer look myself as soon as I get the time.

**Comment by frekw** [comment]
I'm seeing this as well. :+1:

**Comment by mmikkel** [comment]
Yeeeeah,  ```composer.install``` now chokes again w/ the following message:

```
jarednova/timber dev-master requires jarednova/php-router 1.0.1 -> no matching package found.
```

Temporary fix: Add the php-router repository to your local composer.json file – see working composer.json file here: https://gist.github.com/mmikkel/292f692746c2dcedcc16

**Comment by jarednova** [comment]
@mmikkel: are you seeing this error when you install Timber? or a project that's calling Timber as a dependency?

**Comment by mmikkel** [comment]
@jarednova The latter – I'm not using the ```composer create-project``` to install, but a local composer.json file distributed with the theme (and running ```composer install``` from the command line). My complete, current composer.json file is up at the gist above (minus some other non-related dependencies).

**Comment by jarednova** [comment]
@mmikkel -- great, thanks! I'll investigate from there

**Comment by mmikkel** [comment]
Awesome - thank you :)

**Comment by connorjburton** [comment]
@jarednova, @mmikkel - is this still an issue?

**Comment by mmikkel** [comment]
@connorjburton I don't believe so – just created a new Timber project for the first time in ages, and had no issues installing with Composer.

**Comment by connorjburton** [comment]
Brilliant thanks for getting back to me.
