### ISSUE TITLE
multiple theme caching issue

### ISSUE THREAD

**Issue by nadimtuhin** [jarednova/timber#380]
I am not sure if I should have posted here. I maintain a magazine that I built with timber. It works just awesome. Now I want to implement a mobile theme. So when I use the theme changer  plugin the website gets terribly slow.

I am using w3totalcache
I have set timber cache true

can someone point out the best way to achieve this behaviour? my website is nirbhik.com I want a mobile theme to be active in m.nirbhik.com

I love timber go on guys

**Comment by connorjburton** [comment]
Hi @nadimtuhin - is this still an issue for you?

Thanks

**Comment by connorjburton** [comment]
As this seems inactive I am going to close this for now. If it's still an issue please let me know and I will re-open.
