### ISSUE TITLE
Can't activate plugin on fresh install of WP

### ISSUE THREAD

**Issue by geoffyuen** [jarednova/timber#381]
I did a fresh install of WP (on Bluehost) and install Timber through the WP admin but when I try to activate it I get this error on the Plugins page:

    Plugin could not be activated because it triggered a fatal error.
    
    Warning: require_once(__DIR__/functions/timber-twig.php) [function.require-once]: failed to open stream: No such file or directory in /home4/winnipi1/public_html/wp-content/plugins/timber-library/timber.php on line 19
    
    Fatal error: require_once() [function.require]: Failed opening required '__DIR__/functions/timber-twig.php' (include_path='.:/usr/lib64/php:/usr/share/pear') in /home4/winnipi1/public_html/wp-content/plugins/timber-library/timber.php on line 19

**Comment by connorjburton** [comment]
There is a check now for 5.3>
