### ISSUE TITLE
problem with classes in TimberMenuItem

### ISSUE THREAD

**Issue by alesdvorakcz** [jarednova/timber#383]
Hi I have basic menu with two pages:

    {% for item in menu.get_items %}
        <li class="menu-item {{item.classes | join(' ')}}">
            <a href="{{item.link}}">{{item.title}}</a>
        </li>
    {% endfor %}

when I make var_dump for item.classes I get this
`array(5) { [0]=> string(0) "" [1]=> string(9) "menu-item" [2]=> string(15) "menu-item-type-" [3]=> string(17) "menu-item-object-" [4]=> string(11) "menu-item-2" }`
`array(5) { [0]=> string(0) "" [1]=> string(9) "menu-item" [2]=> string(15) "menu-item-type-" [3]=> string(17) "menu-item-object-" [4]=> string(12) "menu-item-41" }`

I tried disable all other plugins (WPML, Types) and the problem still remains.

Any idea?

**Comment by connorjburton** [comment]
Hi @alesdvorakcz, is this still an issue for you?

**Comment by alesdvorakcz** [comment]
hi I made it work with some workaround I think. it is long time now and I dont need it anymore
