### ISSUE TITLE
Fatal error from unhandled object

### ISSUE THREAD

**Issue by terminalpixel** [jarednova/timber#385]
I've run into an issue with the `$rid` variable being a "Object of class WP_Post" and therefore causing a fatal error on [this line](https://github.com/jarednova/timber/blob/master/functions/timber-posts-collection.php#L26)

The problem is fixed by simply escaping it with a `print_r` or something similar but I'm not 100% sure what the function is doing so that may not be the greatest solution.

**Comment by connorjburton** [comment]
Hi @terminalpixel, is this still an issue for you?

**Comment by terminalpixel** [comment]
@connorjburton honestly can't remember how I caused it but I'll close this since I've not noticed any issue in a long time.

**Comment by connorjburton** [comment]
Thanks @terminalpixel, appreciate it
