### ISSUE TITLE
Load more posts

### ISSUE THREAD

**Issue by shiftsave** [jarednova/timber#389]
Hi,

I was wondering if anyone could direct me as to how to write a load more posts for a blog I'm working on with Timber.

Thanks, any guidance would be appreciated!
I

**Comment by connorjburton** [comment]
I'm going to close this as it isn't directly related to Timber and it's been around for a while.

**Comment by geoffyuen** [comment]
@shiftsave , I realize this is old and closed but this *is* possible using the Ajax Load More plugin. More importantly you can still use twig templates. In the Ajax Load More: Repeater Templates you can save what ever PHP you like. In my case:
```
<?php
$context['post'] = new Timber\Post();
Timber::render( 'ajaxloadmore.twig', $context );
?>
```

Now you can write whatever you want in ajaxloadmore.twig and access the post object.

**Comment by abarcenas29** [comment]
@geoffyuen could you provide a more elaborate example?
