### ISSUE TITLE
image|resize() converts progressive image to baseline

### ISSUE THREAD

**Issue by mindfullsilence** [jarednova/timber#390]
Keep the jpegs as progressive if they started out that way for website performance reasons. Currently, the `|resize()` function converts the image to baseline. Any way to keep an image as progressive when using resize()?

**Comment by mgmartel** [comment]
Timber uses the default WordPress image editing implementation, which does not support progressive JPGs, unfortunately. There has been a ticket in the WP trac for over 2 years now ([#21668](https://core.trac.wordpress.org/ticket/21668)) to get this solved, but no news yet.

Even though it's not optimal in this respect, the closer Timber stays to WP image editing functionalities the better, I think.

You could consider using a plugin like [EWWW Image Optimizer](https://wordpress.org/plugins/ewww-image-optimizer/), that extends the default WP image editor functionalities and supports progressive JPGs!

-- Mike

**Comment by connorjburton** [comment]
I'm going to go ahead and close this issue, if this is still an issue please comment and i'll reopen.

**Comment by horizon89** [comment]
Hello, this is still an issue. Anytime I edit an image (resize, crop, etc), it becomes baseline, even if it was progressive originally. (WP version: 4.9.5)
