### ISSUE TITLE
Clear cache programmatically

### ISSUE THREAD

**Issue by kuus** [jarednova/timber#399]
Is there a way to flush the timber cache programmatically?

**Comment by mgmartel** [comment]
Hi @kuus, that is correct. Just a bit of background: 

## `$loader->clear_cache_twig();`
When you set `Timber::$cache` to `true`, all `twig` files will be compiled to `php` files and saved. That saves you some processor cycles on page views. However, this means that changes to your `twig` templates are not visible, unless you clear the cache. That is `$loader->clear_cache_twig();`.

This cache described [here](https://github.com/jarednova/timber/wiki/Performance#cache-the-twig-file-but-not-the-data).

## `$loader->clear_cache_timber( $cache_mode );`
This clears [this cache](https://github.com/jarednova/timber/wiki/Performance#cache-the-entire-twig-file-and-data). Timber's "cache everything" mode. Make sure you pass the cache mode you are actually using as an argument into this function!

If you use a persistent object cache like `memcached`, this will not clear your cache. I remember having some luck with [Johnny Cache](https://wordpress.org/plugins/johnny-cache/) to do this. Make sure you flush the `timberloader` group. Alternatively, purge the whole cache and you're also done!

## Partial cache
The partial cache ([this one](https://github.com/jarednova/timber/wiki/Performance#cache-parts-of-the-twig-file-and-data)) is not cleared by either method. It stores everything in the `timber` cache group by default, so to invalidate it, you have to do it manually. With Memcache see my note above about Johnny Cache. 

-- Mike

**Comment by kuus** [comment]
@mgmartel thanks for the insights mike!

**Comment by connorjburton** [comment]
This seems to have been covered pretty well so I am going to close this now. Feel free to comment if it's still an issue.

**Comment by adskinner** [comment]
Where do you add "$loader->clear_cache_twig();" to clear the cache? in the functions.php file?

**Comment by asecondwill** [comment]
@adskinner  yes, in the functions.php

```
$loader = new TimberLoader();
$loader->clear_cache_timber();
```

I've just come accross an issue where templates are not updating in staging for users not logged in as admins.  This clears that.

**Comment by danburzo** [comment]
Hi everyone,

I'm going to piggyback on this issue for context. I've been reading the [Timber Docs page for Performance](https://timber.github.io/docs/guides/performance/) and tried the Twig caching as described:

```php
Timber::$cache = true;
```

And I can see the `cache/twig` folder being created or not depending on the value of `$cache`. The part that trips me up is that the docs mention changes you make to the Twig templates will not be reflected until you flush the cache. However, (at least) on my local environment, changes I make to the templates _do_ apply as usual.

Has the functionality of the Twig cache changed in the meantime to allow these refreshes to happen, or is it something else about my setup that causes them to work this way?

The second question (which has been answered in this thread) is how to flush the cache. Do you think it would be a good addition to the docs page?

**Comment by connorjburton** [comment]
Hi,

It has been a long time since I have worked on Timber (a couple of years at least) so my memory is hazy however a couple of points:

1. On the docs page is does mention some cache busting that happens

```
But here’s the cool part: Timber hashes the fields in the view context.
This means that as soon as the data changes, the cache is automatically invalidated. Yay!
```

Are you sure you aren't hitting this criteria?

2. When we used to deploy new versions of websites we would have a post deployment script that would POST to a file we have on each theme to clear the timber cache. I am pretty sure it was just a PHP file that ran the clear cache functions.

**Comment by danburzo** [comment]
> Are you sure you aren't hitting this criteria?

I would assume that refers to `Timber::render` with an `$expires` argument? I'm simply using `Timber::$cache = true`, which is supposed to cache the Twig part of the equation, if I understand correctly.

**Comment by gchtr** [comment]
Hey @danburzo 

> The part that trips me up is that the docs mention changes you make to the Twig templates will not be reflected until you flush the cache. However, (at least) on my local environment, changes I make to the templates do apply as usual.

I realized this too. There’s the `auto_reload` [option for the Twig Environment](https://twig.symfony.com/doc/2.x/api.html#environment-options), which takes the default value of `cache`. And the `cache` option is set to the value of `WP_DEBUG` by default. That’s why see all changes in your local environment.

A clarification for how this works might be valuable in the current docs.

I recently updated how these options can be controlled in #1997 against `2.x`.

> The second question (which has been answered in this thread) is how to flush the cache. Do you think it would be a good addition to the docs page?

I think that would be a great addition. If you could do a pull request for this, that would be awesome!

**Comment by danburzo** [comment]
> I realized this too. There’s the auto_reload option for the Twig Environment, which takes the default value of cache. And the cache option is set to the value of WP_DEBUG by default. That’s why see all changes in your local environment.

Ooh, thanks for the pointers. I [located the code](https://github.com/timber/timber/blob/6a6f1ad8fccca8c34efe9fe61b25ad3c7a81f295/lib/Loader.php), and it seems `auto_reload` is triggered by virtue of the `debug` param (i.e. `WP_DEBUG`), which is independent of Timber's `$cache` option. I think I understand now.

> I think that would be a great addition. If you could do a pull request for this, that would be awesome!

I think I can squeeze in a note about `$cache` and WP_DEBUG here as well.
