### ISSUE TITLE
Question: Extending Timber for Custom Post Types

### ISSUE THREAD

**Issue by anugupta** [jarednova/timber#411]
A couple of questions about Timber and CPTs.

1. In the Extending Timber page, we see an example of TimberPost being extended to add custom functionality. I'm unclear how this works - how does the `TimberPost` object become a `MySitePost` object?

2.  I'm trying to reduce the size of my controllers, and thus thinking about creating models that represent each of the custom post types I'll be using, which would lead to something like:

```php
class PeopleCollection {

    public function get_posts($args = array()) {

        $default_args = array(
                'post_type' => 'person',
                'posts_per_page' => -1,
                'orderby' => 'menu_order',
                'order' => 'ASC',
                'post_status' => 'publish',
        );
        $args += $default_args;
        $team_members =  Timber::get_posts($args);
    }

}
```

which allows me to do this in the controller

```php
$context['people'] = (new PeopleCollection)->get_posts();
```

Does this make any sense? It feels cleaner than adding all this to the controller, but maybe I'm overcomplicating things. If I'd extended `TimberPost` to create a class called `MyPersonPost`, how can I get the array to contain "MyPersonPost' objects instead of `TimberPost` objects?

**Comment by IJMacD** [comment]
The `Timber::get_posts()` function has a class argument so you should be able to use it like this:

```
class PeopleCollection {

    public static function get_posts($args = array()) {

        $default_args = array(
                'post_type' => 'person',
                'posts_per_page' => -1,
                'orderby' => 'menu_order',
                'order' => 'ASC',
                'post_status' => 'publish',
        );
        $args += $default_args;
        $team_members =  Timber::get_posts($args, 'MySitePost');
    }
}

$context['people'] = PeopleCollection::get_posts();
```

**Comment by connorjburton** [comment]
I'm going to close this as @IJMacD seems to have covered it. Let me know if it's still an issue and I will re-open.

**Comment by orest22** [comment]
@IJMacD Hi! How do you add 'MyPersonPost' class to timber?

**Comment by chrisgherbert** [comment]
You just need to load the class the same way you'd load any other PHP class or code.  As long as it's a subclass of TimberPost, passing it as an argument to Timber::get_posts should work.

**Comment by jarednova** [comment]
@orest22 @chrisgherbert this can be accomplished as simply as...

```php
/* functions.php */
require_once('lib/MyPersonPost.php');
```
