### ISSUE TITLE
Using alongside Event Espresso

### ISSUE THREAD

**Issue by maketimetodesign** [jarednova/timber#416]
With the plugin Event Espresso 4.4.4.p installed the following is outputted prior to the page rendering:

```html
<div id="espresso-notices"></div>	
	<div id="espresso-ajax-loading" style="display:none;">
		<span class="ee-spinner ee-spin"></span><span style="display:none;">loading...</span>
	</div>

	<div id="espresso-ajax-notices">
	
		<div id="espresso-ajax-notices-success" class="espresso-ajax-notices success fade-away" style="display:none;">
			<a class="close-espresso-notice">&times;</a>
			<p class="espresso-notices-msg"></p>
		</div>
		
		<div id="espresso-ajax-notices-attention" class="espresso-ajax-notices attention fade-away" style="display:none;">
			<a class="close-espresso-notice">&times;</a>
			<p class="espresso-notices-msg"></p>
		</div>
		
		<div id="espresso-ajax-notices-error" class="espresso-ajax-notices error fade-away" style="display:none;">
			<a class="close-espresso-notice">&times;</a>
			<p class="espresso-notices-msg"></p>
		</div>
		
	</div>
<!doctype html>
```

It's the following query that causes the HTML to be output, but even when it's not an event post.

```
Timber::query_post();
```

I'm no expert so am a bit confused, so unsure if this is a problem with EE or Timber. Any help would be hugely helpful and I can supply any other code, but there isn't much else going on besides the query.

This only happens via single.php and only seems to effect CPTs as the HTML isn't rendered when I view other pages, i.e. homepage etc.

Thanks in advance!

**Comment by maketimetodesign** [comment]
Hey @jarednova happy new year! I was just wondering if you had had any luck taking a look at this?

Cheers
Tom

**Comment by jarednova** [comment]
@maketimetodesign I didn't realize this was a paid plugin. Can you [email me](mailto:jared@upstatement.com) a zip of the plugin so I can replicate yr issue?

**Comment by maketimetodesign** [comment]
We haven't bought the plugin yet due to the problem. I've only been testing with the free version so far. The "de-caffeinated" version...

**Comment by jarednova** [comment]
Hey @maketimetodesign I'm able to see the issue you're seeing. It would seem that it's as simple as just not using `Timber::query_post();` which is triggering something in the bowels of EE. You said you're trying this on `single.php`? Here's what I have for that PHP file that renders fine (WITH event info, but without that extra markup you noted in yr first comment):

```php
/* single.php */

<?php
/**
 * The Template for displaying all single posts
 *
 * Methods for TimberHelper can be found in the /functions sub-directory
 *
 * @package  WordPress
 * @subpackage  Timber
 * @since    Timber 0.1
 */


$context = Timber::get_context();
$post = new TimberPost(); //this will get the current post, be it an EE event or other
$things = Timber::query_posts('post_type=post'); // in-case you need to query other things. This works w/o generating the extra markup.
$context['post'] = $post;
$context['wp_title'] .= ' - ' . $post->title();
$context['comment_form'] = TimberHelper::get_comment_form();

if (post_password_required($post->ID)){
	Timber::render('single-password.twig', $context);
} else {
	Timber::render(array('single-' . $post->ID . '.twig', 'single-' . $post->post_type . '.twig', 'single.twig'), $context);
}
```

**Comment by maketimetodesign** [comment]
Hey @jarednova, thanks for taking the time to check that out. that seems to work fine and stops the EE AJAX markup from being output.

I'm still getting my head in to it all, but how would I go about accessing the `EE_Event` object? So that I can access all of the EE specific fields, i.e. `EVT_name`, `EVT_created` etc.

Cheers!
T

**Comment by jarednova** [comment]
@maketimetodesign, here's [a gist](https://gist.github.com/jarednova/8a1ffa595fae8bfb25b7) to help you out. Again, not familiar with EE so lots of psudo code in there

**Comment by maketimetodesign** [comment]
Thanks for your time helping on this @jarednova, much appreciated!
