### ISSUE TITLE
blank page

### ISSUE THREAD

**Issue by sschak** [jarednova/timber#417]
Hello, 

I have installed newest version of wordpress on a webspace server, installed the newest version of timber and activated the timber starter theme. But I just get a blank white page. I tried it on a local server and it works fine. On the webserver they use php 5.3. Is it because the version isn't the newest one?

**Comment by connorjburton** [comment]
Hi @sschak, is this still an issue for you?

**Comment by connorjburton** [comment]
I am going to close this as I haven't had a reply. Feel free to comment at any point in time and I will re-open.
