### ISSUE TITLE
Timber does not re-compile templates while on the customizer

### ISSUE THREAD

**Issue by aristath** [jarednova/timber#420]
I've got some options in the theme customizer.
On my global context for timber I'm using this:
```php
$context['theme_mods'] = get_theme_mods();
```
and on my twig templates I can get the customizer options using
```twig
{{ theme_mods.option_name }}
```
My problem is that when a user is in the customizer and changes some option (the option is set to refresh and not postmessage), the templates are not regenerated, and so on refresh the user does not see their options applied. They have to save the options and refresh the page.

I've tried setting Timber Caching to none when in the customizer without any effect:
```php
global $wp_customize;
if ( isset( $wp_customize ) ) {
	TimberLoader::CACHE_NONE;
}
```

**Comment by shawnsandy** [comment]
Same issue here - stymies the user experience...

**Comment by aristath** [comment]
I still haven't figured this one out...
Any ideas?

**Comment by briancwelch** [comment]
I also am experiencing this issue.  Have tried a couple different methods to no avail.  Can anyone offer any insight?

**Comment by jarednova** [comment]
I've actually run into this too, help!!!!!!

I remember doing some debugging on this a few years back and getting nowhere. I'll look at it w fresh eyes since yall are hitting it too and report back

**Comment by lmartins** [comment]
For some reason I haven't seen this one for a while now. Not really sure what changed on my sites, i'll post it here if I ever found the reason.

**Comment by aristath** [comment]
When we're creating a setting in the customizer, we also have the ability to add a `sanitize_callback` argument, calling our own function that will reset all timber/twig caches.
Perhaps this would help...

So we could have a callback function like this:
```php
function my_control_sanitize( $value ) {
	// If Timber is installed, reset its caches.
	if ( class_exists( 'TimberLoader' ) ) {
		TimberLoader::clear_cache_twig();
	}
	return $value;
}
```
However this doesn't work yet 'cause it only clears the twig file caches, and I suspect there are more caches that will have to be cleared...

**Comment by aristath** [comment]
I found the issue.
The problem was not with Timber but my implementation (no surprise there...)
I was adding theme_mods to the global context using
```php
$context['theme_mods'] = get_theme_mods();
```
and then calling these in my template files using
```twig
{{ theme_mods.theme_mod_name }}
```
However, Timber being so brilliantly developed already has a theme object so instead of the above, I am now doing it like this:
```twig
{{ theme.theme_mod('theme_mod_name', 'default_value') }}
```
and everything works smoothly. :+1: 

@jarednova I'll just go ahead and close this issue, it has already been taken care of.
The issue actually was lack of documentation for the `TimberTheme` class. All it took was grep'ing the plugin source code for `get_theme_mod` and I was able to figure it out. :)

**Comment by tousignant-christopher** [comment]
I would argue that while this works, Timber is calling each theme mod individually. I am assuming the point of calling get_theme_mods is to cut down on the number of database calls. I would suggest that you call the theme mods differently for the customizer vs. for the front end. I would call each theme mod individually in the customizer, and then store the values in a transient that can then be called when constructing the front end.
