### ISSUE TITLE
How to add pagination to a sidebar inside a single post

### ISSUE THREAD

**Issue by paul-straetmans** [jarednova/timber#422]
At the moment I have a single post page displaying the post. In a sidebar I want to display all posts with a pagination (15 posts per page). 

The single post is displayed. And in the sidebar I become 15 posts. But the pagination is not there. I checked the Debug bar but the Array is empty. Is this because it's not allowed? Or i'm doing something wrong? I checked the wiki and used the global $paged, but no success.

single.php
````
<?php

//sidebar post + pagination
global $paged;
if (!isset($paged) || !$paged){
    $paged = 0;
}

$context = Timber::get_context();

$args = array(
	'post_type' => array('post','feature','decider'),
	'posts_per_page' => 14,
	'orderby' => 'latest'
);

$context['all_posts'] = Timber::get_posts($args);
$context['pagination'] = Timber::get_pagination();

// single post
$post = new TimberPost();
$context['post'] = $post;
$context['acf'] = get_field_objects($data["post"]->ID);

// single post ad
$args_ad = 'post_type=ads&category_name=post-ad&numberposts=1&orderby=latest';
$context['ads_post'] = Timber::get_posts($args_ad);

// search related posts with tags from this post
$tags = $post->tags();
$search_tag = $tags[0];

$templates = array('single-' . $post->ID . '.twig', 'single-' . $post->post_type . '.twig', 'single.twig');
Timber::render($templates, $context);

````

Somebody sees what I'm doing wrong?

**Comment by connorjburton** [comment]
Hi @paul-straetmans - is this still an issue?

Thanks

**Comment by connorjburton** [comment]
As this seems inactive I am going to close this for now. If this is still an issue please post it on Stackoverflow under the Timber tag.

Thanks
