### ISSUE TITLE
Timber fragment / partial caching - expiration

### ISSUE THREAD

**Issue by anugupta** [jarednova/timber#423]
Been playing around with caching parts of the template using the `{{ cache }}` method.

I can see that it creates a `_transient_timber_xxx` field in the WP options table - how does this field get expired - does Timber do any sort of cleanup of old cache entries? 

It seems as if it only changes if the underlying WP data changes - ie template changes don't force a refresh. Is there any Timber mechanism to regenerate the data after a period of time (similar to the `$expires` parameter in `Timber::render`?

**Comment by mgmartel** [comment]
Hi @anugupta,

The cache is based on the data you pass in as the second parameter, ie. in the doc example:

```twig
{#                       cache key #}
{#                       |         #}
{#                       V         #}
{% cache 'index/content' posts %}
    {% for post in posts %}
        {% include ['tease-'~post.post_type~'.twig', 'tease.twig'] %}
    {% endfor %}
{% endcache %}
```

The cache key will be based on the contents of `posts`. If anything in `posts` changes, the cache will be invalidated. For simplicity's sake, this is the only invalidation strategy.

The cache is stored in the cache mode that is set through the `timber/cache/mode` filter. That is transient by default. If you want to use your object cache instead for example, you can use:

```php
add_filter( 'timber/cache/mode', function( $cache_mode ) {
    $cache_mode = TimberLoader::CACHE_OBJECT;
    return $cache_mode;
} );
```

If you really want to use a time-based expiration of your cache, you could think about creating an expiration value in your context. For example, to expire the cache at 3am every day:

```php
// any-template.php or somewhere else where you have access to the context
$context['expiry'] = strtotime( 'tomorrow 3am' );
```
```twig
{# your-template.twig #}
{% cache 'index/content' expiry %}
    {% for post in posts %}
        {% include ['tease-'~post.post_type~'.twig', 'tease.twig'] %}
    {% endfor %}
{% endcache %}
```
The only catch is that if you use transient based caching without a persistent object cache, they will not be replaced. This means your database will grow and grow and grow!

Mike

**Comment by anugupta** [comment]
Hey @mgmartel 

Great reply - thanks :smile: 

If I've dropped in `object-cache.php` (to get WP to store transients in some other form), does Timber respect that, or do we still need to hook into `timber/cache/mode' and set the cache type?

Like the idea of encoding the expiry time in the cache key, very clever.

**Comment by mgmartel** [comment]
Yes! If available, WordPress automatically uses the external object cache for transients. So also the Timber transient cache will automatically go to the object cache set up in `object-cache.php`.

**Comment by bigmike7801** [comment]
I too have noticed a lot of `_transient_timber_xxx` records in my `wp_options` table. Will these records just keep increasing? Is there some sort of preferred process/method for going in and deleting them?

**Comment by mgmartel** [comment]
Hi @bigmike7801,

WordPress doesn't purge expired transients out of the box - if you don't use a persistent cache back-end, they will start filling up your options table. See [this](http://www.stumiller.me/does-wordpress-delete-expired-transients-from-the-database/) article about the problem. 

You can use the plugin [linked in the article](https://github.com/Seebz/Snippets/blob/master/Wordpress/plugins/purge-transients/purge-transients.php) to set up automatic purging of transients.
