### ISSUE TITLE
How to get ACF fields from inside a loop

### ISSUE THREAD

**Issue by lmartins** [jarednova/timber#430]
Im having a hard time figuring out how to get a relationship ACF field from inside a loop. 
I currently have:
```
<h2 class="h2"><a href="{{ banner.link }}">{{ banner.title }}</a></h2>
<p>{{ banner.description }}</p>
<p>{{ banner.button_text }}</p>
<img src="{{ TimberImage( banner.meta('banner_top_image') ).src }}" />
{{ banner.meta('banner_link') }}
```

The last line returns an array of objects, where I need to get the permalink from the first object.
Could you help figure this out please?

**Comment by maketimetodesign** [comment]
I'm guessing you may need to init a new TimberPost( POSTID ); in your PHP file before it gets to the Twig template?

I'm kinda new to Timber/Twig but I think that makes sense to me! :)

**Comment by asecondwill** [comment]
what does 

````{{dump(post)}}````

give you?  Can you use |first to get at that first object and access the permalink directly or if it isn't in the object create a TimberPost right in the template a bit like you are creating a TimberImage above.

**Comment by lmartins** [comment]
I ended up using:
```
{% set link = fn('get_permalink', banner.get_field('link')[0].id ) %}
```
it's not the prettiest solution but im not sure if there's a more elegant solution to this. Im closing it for now, maybe I will find a better way as I get more experience with Timber.

Thank you both for the suggestions.
