### ISSUE TITLE
Support for Jade?

### ISSUE THREAD

**Issue by ivanjuras** [jarednova/timber#433]
Hey there, I was wondering if Timber supports Jade? I'm asking because after trying it, I simply can't go back to writing normal HTML ever again :D.

**Comment by jarednova** [comment]
Not something that it supports right now -- but something that would make for an interesting extension. Let me know if you have a start or have progress to share. I can imagine a future where Timber is agonistic about allowing different template languages.

**Comment by ivanjuras** [comment]
Okay, thanks anyways. Yeah, I've been building static sites for a while (I'm a front end guy), and, like many of us front-enders out there, we simply can't go back to writing pure HTML again.

PHP is on the same line of "ugliness" as well, so making Timber work with these preprocessors would be great.

**Comment by thiagodebastos** [comment]
:+1: For Jade support!

**Comment by herrbischoff** [comment]
I'm totally for Jade support. In the meantime, I have set up my `gulp` install to bridge the gap somewhat:

```coffee
changed = require 'gulp-changed'
jade = require 'gulp-jade'
plumber = require 'gulp-plumber'
rename = require 'gulp-rename'

gulp.task 'jade', ->
  gulp.src paths.jade.input
    .pipe changed paths.jade.output, extension: '.twig'
    .pipe plumber(
      derrorHandler: (error) ->
        gutil.log('(ERROR)', error.message)
        gutil.beep()
      errorHandler: notify.onError("Error: <%= error.message %>")
    )
    .pipe jade(
      pretty: true
    )
    .pipe rename
      extname: '.twig'
    .pipe gulp.dest paths.jade.output
```

In the Jade templates, you simply write the Twig tags/expressions as plain text, like so:

```jade
body
  .site-container
    | {% include 'header.twig' %}
    | {% block content %}{% endblock %}
    | {% include 'footer.twig' %}
```

Works like a charm. And I was positively shocked when I realized how much cleaner my templates have become by using Jade.

Direct support would be much preferred at any rate. Imagine how fantastically clean it would be to do something like this

```jade
each post in posts
  article
    h3= post.title
    p= post.content
```

instead of this

```twig
{% for post in posts %}
<article>
  <h3>{{post.title}}</h3>
  <p>{{post.content}}</p>
</article>
{% endfor %}
```

**Comment by herrbischoff** [comment]
Any news on this?

**Comment by dinolatoga** [comment]
I'm looking forward to Jade support too. But for now @herrbischoff 's solution should work.

**Comment by jarednova** [comment]
@dinolatoga @herrbischoff: I'd love to see continued development on this front, but I'm afraid I'm working on an intense backlog of stuff and don't see getting to this myself for quite some time. That said, PRs are always welcome if you want to pursue a "more native" (ie: gulp-less) solution towards implementation

**Comment by herrbischoff** [comment]
@jarednova I'd love to work on it but have to admit that I'm a little puzzled by how the actual template compile workflow runs. If you could give me some pointers where I should replace code, hook in and what to expect to happen, I'd give it a shot. Especially important would be the proper implementation of the included functions, variables and placeholders.

A serious roadblock may also be that there appears to be no *up-to-date* implementation of Jade for PHP, which is a shame.

**Comment by herrbischoff** [comment]
Just wanted to bring this back into consideration. There is now a very active and maintained implementation of Jade for PHP: https://github.com/kylekatarnls/jade-php

I'd really like to take a stab at bringing it to Timber. Having looked through the source, so far it promises to be rather painful as Twig appears to be woven in pretty deep. On the other hand, as Jade has no concept of filters in the way Twig does, it should be possible to leave a lot of those complexities out. All in all Jade is a very much different approach to templating than Twig is and way less in the general PHP style, which I consider to be a good thing.

**Comment by connorjburton** [comment]
Hi @herrbischoff, I think this would be great to implement at some stage.

I can't speak for @jarednova however I do feel this would be better suited for v2, rather than trying to crowbar it into the existing codebase. As obviously that might take a little while and you want to take a crack at this (I saw you posted a workaround), it may be worth forking Timber or doing a PR on https://github.com/timber/sugar (whichever is more suitable) so when it comes to making Timber a bit more agnostic about it's templating language we have something to work from

**Comment by connorjburton** [comment]
I'm going to go ahead and close this as it's not an issue as such and trying to get the issues list a bit clearer. If you want to discuss this further jump into Gitter :+1:

**Comment by herrbischoff** [comment]
Agreed, although this issue carries the "enhancement" tag. I'm going to go ahead and fork Timber to try and get the Jade implementation going. I presume there is no rough timetable for the template engine agnostic change, is there? I wouldn't want to write code that cannot be used afterwards.

**Comment by connorjburton** [comment]
It's more for my sanity, going through 100+ issues everyday is taxing :)

We are a way off V2 (re-write, not on V1 yet!) so I think you are good for a while, I'm sure there will be some notification on when V2 is being started and (if we haven't spoke before that time) we can take a look at a Jade implementation.

**Comment by connorjburton** [comment]
And make sure to keep us up to date via Gitter!
