### ISSUE TITLE
TimberImage dimensions for a size.

### ISSUE THREAD

**Issue by addedlovely** [jarednova/timber#438]
I am trying to pull in the dimensions for an image. 
When trying to set the width / height with the code below, nothing is returned. ('Size' is a variable which is set to a wordpress image size, e.g. 'thumbnail', 'large' etc.)

    <img src="{{TimberImage(item_project.thumbnail.id ).src(size)}}" width="{{TimberImage(item_project.thumbnail.id ).src(size).width }}" >

If I print_r TimberImage(item_project.thumbnail.id ) the dimensions are in the array. Any suggestions?

**Comment by jnweaver** [comment]
Nothing gets returned because you need to reference *ID* on thumbnail instead of the lowercase *id*.

But actually, the *thumbnail* method returns a TimberImage object already that corresponds to your post's featured image as defined in the Wordpress admin UI. So you should be able to replace the above code with:

```
<img src="{{item_project.thumbnail.src(size)}}" width="{{item_project.thumbnail.width }}" >
```

Just for the record, if you were trying to reference TimberImage objects as in your original code, it would be:

```
<img src="{{TimberImage(item_project.thumbnail.ID ).src(size)}}" width="{{TimberImage(item_project.thumbnail.ID ).width }}" >
```

**Comment by addedlovely** [comment]
Hi @jnweaver

Sorry should of been clearer. I'm not getting the default wordpress featured image here, thumbnail is a custom field from Advanced Custom Fields, which is within a flexible content layout.

Your second option, as per below, I'd tried. This returns the dimension of the image as originally uploaded, not the actual size of the image, e.g. the thumbnail dimensions.

    <img src="{{TimberImage(item_project.thumbnail.ID ).src(size)}}" width="{{TimberImage(item_project.thumbnail.ID ).width }}" >

Thanks,

Ian.

**Comment by jnweaver** [comment]
Ah, I see. 

The TimberObject also returns a *sizes* attribute containing an array of info about each existing size of an image. So maybe this is what you are looking for?

```
<img src="{{TimberImage(item_project.thumbnail.ID ).src(size)}}" width="{{TimberImage(item_project.thumbnail.ID).sizes[size].width }}" >
```

**Comment by addedlovely** [comment]
@jnweaver ah great, that does indeed work.

There is an edge-case where it fails, if the specific image size hasn't been generated and wordpress defaults back to the original uploaded image, but for now that works.

Thanks for the help.
