### ISSUE TITLE
Check if ACF value exists inside loop

### ISSUE THREAD

**Issue by tmyie** [jarednova/timber#440]
Hey,

Love the plugin.

However, I'm inside a loop (from WP_Query) and I'm trying to check if an ACF field value exists.

I've tried:

		`{% set foo = post.get_field('project_portrait_thumbnail') %}`

And variants of, but `foo` then renders nothing. I intend to check if the image exists, before writing a `<img>` tag.

**Comment by asecondwill** [comment]
I think you can just do this, no?

{% if post.get_field('project_portrait_thumbnail') %}

do stuff

{% endif %}

**Comment by ladislavsulc** [comment]
Thanks @asecondwill, that helped me as well :+1:
