### ISSUE TITLE
Store cache data in the wp-content/cache directory

### ISSUE THREAD

**Issue by tmoitie** [jarednova/timber#441]
This directory is typically better set up for permissions and would therefore be more appropriate a location.

**Comment by aristath** [comment]
:+1: 
Or maybe even on `wp-content/uploads/timber-cache` 
Basically anything would be better than saving caches in the plugin folder. :smile:

**Comment by aristath** [comment]
Fixed in https://github.com/jarednova/timber/pull/450

Now you can use the `timber/cache/location` filter to change the location where cached data is stored.

example:
```php
/**
 * Change Timber's cache folder.
 * We want to use wp-content/cache/timber
 */
function custom_change_twig_cache_dir() {
  return WP_CONTENT_DIR . '/cache/timber';
}
add_filter( 'timber/cache/location', 'custom_change_twig_cache_dir' );
```

**Comment by connorjburton** [comment]
This is solved so I'm gonna close this.
