### ISSUE TITLE
Calling a widget with arguments

### ISSUE THREAD

**Issue by sb-lc** [jarednova/timber#443]
hello, I am currently converting my template to use timber, I have run into an issue with widgets. although there is documentation about how to render a widget with timber commands, I can't find out how to send arguments / parameters to that widget. In PHP it looks like this:

<?php if( has_nav_menu( 'footer-menu-location') ) : ?>
				                	<?php the_widget( 'blocks_menu_widget', 'menu_src=menu&menu_location=footer-menu-location'); ?>
				            	<?php endif; ?>

I was trying various things in footer.twig, but can't seem to get it working, any help would be greatly appreciated,

thanks

**Comment by igregson** [comment]
@sb-lc 

Though I haven't tested this, I think this should work.

In `footer.php`: 

```
$context[call_this_whatever] = has_nav_menu( 'footer-menu-location');
```

Then, in a `footer.twig` file you can use `call_this_whatever` as a variable (in this case a boolean variable, meaning it will either be true or false). 

I couldn't find a straightforward example of how to create a Twig variable from php logic in the Timber docs. Regardless of whether this works for your particular case, it's at least an example of creating Twig variables from php logic.

**Comment by connorjburton** [comment]
Hi @sb-lc, is this still an issue for you?

**Comment by connorjburton** [comment]
Hi, as this doesn't seem to be active I am going to close this. If this is still an issue, please let me know and I will re-open.
