### ISSUE TITLE
Unable to preserve post ID order given in the post__in array when using Timber::get_posts()

### ISSUE THREAD

**Issue by dinolatoga** [jarednova/timber#447]
`'orderby' => 'post__in'` does not seem to be supported by `Timber::get_posts()`. It is supported by the WP_Query since [WP 3.5](http://codex.wordpress.org/Class_Reference/WP_Query)

WordPress Debug Bar error output: `Unknown column 'post__in' in 'order clause'`

**Comment by marciojcoelho** [comment]
Have you define the array of ids?

```
'orderby'        => 'post__in',
'post__in'       => $array_of_ids
```

**Comment by xymurgist** [comment]
Yes, of course. I wanted the output to follow the order if the array but using the timber get_posts method doesn't work. The native WP get_posts returns correctly ordered posts though.

**Comment by marciojcoelho** [comment]
I using this at a project and works. can you provide the full timber get_posts code?

**Comment by xymurgist** [comment]
```
$posts = Timber::get_posts(array(
  'post_type'      => $post_type,
  'posts_per_page' => $num,
  'post__in'       => $eatsb_options[$option_id],
  'orderby'        => 'post__in'
));
```

**Comment by Karzin** [comment]
Same problem here

**Comment by Karzin** [comment]
Sorry. I found the problem. It was the Post Types Order plugin. Once it was deactivated the problem was solved

**Comment by connorjburton** [comment]
Hi @dinolatoga, is this still an issue for you? Thanks

**Comment by connorjburton** [comment]
As this seems inactive and there are other solutions posted I am going to close this now.

Feel free to comment if it's still an issue and I will re-open.

**Comment by emanuellopes** [comment]
Hello, i have this problem. i am trying using that but the result is not the same as get_posts from WordPress.

**Comment by jarednova** [comment]
@emanuellopes I've validated that the current version of `master` works as expected and matches WordPress's `get_posts` ordering (see tests in 485c2b8 and 2596ae5)
