### ISSUE TITLE
Any way to translate the "Read More" label from get_preview?

### ISSUE THREAD

**Issue by lmartins** [jarednova/timber#448]
Hi,

Is there any way to translate this string?
Im currently unable to use the `get_preview` because I need that string to be in another language.

Thanks

**Comment by marciojcoelho** [comment]
you can input the translation.

get_preview($len = 50, $force = false, $readmore = 'Read More', $strip = true)

**Comment by lmartins** [comment]
Hey Marcio,
That solved for me, not as elegant but simple `get_preview()` but it works:
```
<p>{{post.get_preview(20, false, __('Read More', 'wip'))}}</p>
```

Thank you.
