### ISSUE TITLE
Issue with Query params

### ISSUE THREAD

**Issue by lmartins** [jarednova/timber#449]
Im looping through a list of categories that are children of the current category, to achieve that:

```
$args = 'post_type=page&post_parent='. $page_id .'&numberposts=-1&orderby=menu_order&order=ASC';
        $context['posts'] = Timber::get_posts( $args );

Timber::render( 'page-listcategories.twig', $context );
```

The reason im using the query this is because the following no matter what I try won't sort the categories the same way, I have no idea why:

```
$args = array(
            'post_type'   => 'page',
            'numberposts' => -1,
            'post_parent' => $page_id,
            'order_by'    => 'menu_order',
            'order'       => 'DESC'
        );

$context['posts'] = Timber::get_posts( $args );

Timber::render( 'page-listcategories.twig', $context );
```

Since the query has the exact same params in both cases, what can be causing the different behaviour?

**Comment by jnweaver** [comment]
I might be missing something, but in the first example above you're *order* is *ASC* and in the second its *DESC*. Are you saying, however, that when both use the same value for *order*, you're still getting different results? For what it's worth, I only ever pass query arguments in as an array, but I would expect the string method to work just the same.

**Comment by lmartins** [comment]
Hey @jnweaver ,
You're right, that actually was a mistake on copy paste and a result of the ongoing tests.
What im saying is that only the string method is working as expected, the array won't make any change to the order, no matter what values I insert for "order" and "order_by", which is pretty weird.

**Comment by xymurgist** [comment]
I think it's a typo error. You need to use `orderby` instead of `order_by`. Note: there should be no underscore.

**Comment by lmartins** [comment]
Oh man, this is embarrassing. You're right @xymurgist its that typo.
Strange thing i've been using that snippet in other places and only now i've noticed the problem.

Thank you for catching that.

**Comment by xymurgist** [comment]
Glad to be of help. :)
