### ISSUE TITLE
Timber starter theme: WordPress coding standard

### ISSUE THREAD

**Issue by kuus** [jarednova/timber#454]
Hello @jarednova, first of all thanks for the hard work on Timber, second, would you accept a pull request with the Timber starter theme reformatted to meet the WordPress [coding standard](https://make.wordpress.org/core/handbook/coding-standards/php/) ? If so, I'll do it right away.

**Comment by jarednova** [comment]
Hi @kuus! Yes, I'd be all-for making it match WP coding standards please submit and I'll review.
