### ISSUE TITLE
Git clone from 'Getting started' gives permission error.

### ISSUE THREAD

**Issue by tmyie** [jarednova/timber#455]
Love the plugin & theme!

However, for me, this didn't work:

git clone git@github.com:jarednova/timber.git

But this did:

git clone https://github.com/jarednova/timber.git

**Comment by jarednova** [comment]
Hi @tmyie can you post a screenshot of the command and error? I want to make sure I'm properly replicating the issue and encountering the same error

**Comment by connorjburton** [comment]
Hi @tmyie is this still an issue for you? Thanks.

**Comment by connorjburton** [comment]
I am going to close this as I haven't had a reply. Feel free to comment at any point in time and I will re-open.
