### ISSUE TITLE
Going deeper than 2 two level with TimberMenu

### ISSUE THREAD

**Issue by lmartins** [jarednova/timber#458]
Is this possible? 
I've tried to run the `get_children` from the child object on the code samples but got nothing back.

Thanks.

**Comment by mindfullsilence** [comment]
The following seems to work well for me:

__page.php__
```
$context['menu']['header_nav'] = new TimberMenu('Header Nav');
Timber::render('about-noah-webster.twig', $context);
```

__macros/menus.twig__
```
{% macro embedded_list(items) %}
	{% import _self as menus %}
	{% for item in items %}
		<li>
			<a href="{{ item.link }}">{{ item.title }}</a>
			{% if item.has_child_class %}
				<ul>
					{{ menus.embedded_list(item.get_children) }}
				</ul>
			{% endif %}
		</li>
	{% endfor %}
{% endmacro %}
```

__page.twig__
```
<ul>
  {% import 'macros/menus.twig' as menus %}
  {{ menus.embeddded_list(navs.header_nav.items) }}
</ul>
```

**Comment by lmartins** [comment]
Hey Timothy, thank you so much for the tips. I wasn't familiar with Twig macros but it seems like a very useful feature.

In the last part of your code, `page.twig`, should the parameter passed to the list be `menu.header_nav.items`? Im confused where that `navs` come from...

**Comment by lmartins** [comment]
Anyway, got it working with the necessary adjustments to your code. Thanks again for the help Timothy. 

Cheers!
