### ISSUE TITLE
Use for admin theming?

### ISSUE THREAD

**Issue by beatelite** [jarednova/timber#460]
I'm new to timber and twig so this may be a dumb question but could you use it to for a custom admin interface for the wordpress admin?

In building an app, we need to tightly control the UX and have written our own. Now we're looking for a simple and clean way to implement. Could timber and twig be used in this case or is only for wp "front-end"?

Great idea btw.

**Comment by jarednova** [comment]
@beatelite -- I use it all the time for backend things. See this plugin we've made for a quick view of it in-action:

https://github.com/upstatement/zoneboard

**Comment by beatelite** [comment]
Wow. excellent news! Do you happen to have or know of any tutorials on how to implement on the backend?

**Comment by simonmilz** [comment]
@beatelite  -- I only do admin things with timber. Without timber... Oh.. I don't want to think about it. For example, i just have a normal metabox:

```php
        add_meta_box(
            'periods',
            __('Periods', I18N),
            array($this, 'render'),
            'holidayhome',
            'normal',
            'high'
        );
```

and a render function:

```php
public function render($template) {
    $content = array(); // do your stuff
    \Timber::render($template, $context);
}
```

**Comment by connorjburton** [comment]
Hey guys, I'm going to close this as an example has been posted and it's not really and issue with Timber per-say.

Feel free to continue the discussion over at Stackoverflow.
