### ISSUE TITLE
WPML and Timbers image retina filter not playing nice 

### ISSUE THREAD

**Issue by Quirksmode** [jarednova/timber#465]
Such a massive fan of this plugin btw, have used it on several sites with great success. For my next project I am required to use WPML and it seemed to be working great until I viewed a translated page on my retina screen and saw that all the images were coming up as not found. When I inspected the html I saw that Timber is outputting the retina src incorrectly:

    <img srcset="http://examplesite.dev/wp-content/uploads/2015/02/download-480x325.jpeg, http://examplesite.dev?lang=fr/wp-content/uploads/2015/02/db1cf469b6c27ae7a8287a0235fa84f4@2x.jpeg 2x" alt="">

The Timber code I am using is:

    <img srcset="{{TimberImage(item.image).src('mobile')}}, {{TimberImage(item.image).src('mobile') | retina(2)}} 2x" />

Am I doing something wrong, how can I fix this?

**Comment by xavierpriour** [comment]
Pardon the shameless plug, but this is fixed in my #457

**Comment by Quirksmode** [comment]
Wow, the internet never ceases to amaze me. You are an absolute legend, thanks so much for this, will give it a go tonight :-)

**Comment by connorjburton** [comment]
The PR related to this was merged so going to close this.
