### ISSUE TITLE
Timber::get_terms arguments not working

### ISSUE THREAD

**Issue by Quirksmode** [jarednova/timber#470]
I am trying to only display the top level elements of a taxonomy, but for some reason the hierarchical argument does not seem to work. I tried orderby and this also does not work? 

$context['products'] = Timber::get_terms('products', array('hierarchical' => 0));

When I remove 'Timber::' it works perfectly, any ideas?

$context['products'] = get_terms('products', array('hierarchical' => 0));

**Comment by Quirksmode** [comment]
The difference may be because Timber::get_terms by default shows empty results which is a good thing. I have used parent=0 to solve this, but will leave the issue open in case there is an issue with hierarchical.

**Comment by connorjburton** [comment]
@Quirksmode is this still an issue for you?

**Comment by connorjburton** [comment]
I am going to close this as I haven't had a reply. Feel free to comment at any point in time and I will re-open.

**Comment by simonmilz** [comment]
I can reproduce the issue as well:

`$context['locations'] = \Timber::get_terms('location' , array(
            'hide_empty' => true
        ));`

don't work for me.

**Comment by simonmilz** [comment]
Sorry, my fault. The count value of my term was not up to date.
