### ISSUE TITLE
Routes for Custom Post types, including Single as well as Index

### ISSUE THREAD

**Issue by asecondwill** [jarednova/timber#479]
Hi there

I often want a structure where the posts index, or a custom post type index is really a page with a template somewhere in the site structure.  so like this
````
Home
About
Research 
  People
    - Will
    - Bob
    - Jared
  Approach
  Science
  Centres
    - Computing
    - Medicine
````

Where People and centres are a custom post type. 

Is it possible to configure routing to respect that structure?   So my url would be
````
/research/people/will
````

**Comment by alaninteractive** [comment]
Hey. I have URL structures with 3 segments based on custom post types and custom taxonomy terms, and the post name/slug.

```

// Case Studies
Timber::add_route(':post_type/:term/:name', function($params){

    //make a custom query based on incoming path and run it...
    $query = array(
		'post_type' => $params['post_type'],
		'tax_query' 	=> array(
    		'taxonomy' 	=> 'business-type',
			'terms'    	=> $params['term']
    	),
		'name' => $params['name']
	);
    //Check for the term and load the template, or 404
    if( term_exists($params['term']) ) {
    	Timber::load_template('single.php', $query);		
    } else {
    	Timber::load_template('404.php');
    }
    
});
```

Wordpress was being overly helpful, in that the URL could contain anything in the middle segment... hence the if statement.

**Comment by connorjburton** [comment]
@alaninteractive seems to have covered this so i'm going to close this issue. Let me know if it's still an issue and i'll re-open.
