### ISSUE TITLE
Fatal error: Call to undefined method TimberImageHelper::delete_resized_files_from_url()

### ISSUE THREAD

**Issue by JeyKeu** [jarednova/timber#481]
I got this error when i tried to delete an image from the Media library.
`Fatal error: Call to undefined method TimberImageHelper::delete_resized_files_from_url() in /plugins/timber-library/lib/timber-image-helper.php on line 87`

**Comment by tmoitie** [comment]
+1, got this when viewing images in list view (Media Library), selecting them as checkboxes, selecting Delete Permanently and clicking Apply.

**Comment by tmoitie** [comment]
I've just noticed this has been fixed a few commits ago. What's the ETA on this being released?

**Comment by jarednova** [comment]
Yes, this should be resolved with #480. @tmoitie the fix is currently in master. I was planning on deploying to WP.org on Thursday

**Comment by tmoitie** [comment]
Okay thanks 👍

**Comment by JeyKeu** [comment]
Great! Thanks.
