### ISSUE TITLE
E_ERROR: Class 'TimberSite' not found when confirming user accounts

### ISSUE THREAD

**Issue by lmartins** [jarednova/timber#482]
When a user account is created via dashboard, my sites are generating an email with a link something like:

```
http://domain.com/wp-activate.php?key=something
```
When the users click on that link they gat a blank page an New Relic shows me the following information:

```
Error message
E_ERROR: Class 'TimberSite' not found

Stack trace
…n called at /srv/wordpress/wordpress/mw-public/themes/wip-foster/
functions.php (42)
in include called at /srv/wordpress/wordpress/wp-settings.php (327)
in require_once called at /srv/wordpress/wordpress/wp-config.php (140)
in require_once called at /srv/wordpress/wordpress/wp-load.php (29)
in require called at /srv/wordpress/wordpress/wp-activate.php (12)
```
The site has timber plugin active and the front-end works without issues otherwise.

Any tips?

**Comment by jarednova** [comment]
@lmartins -- what version of Timber are you using? Can you also include code samples of anywhere in yr theme that you're calling `TimberSite`? (if in-fact you are)

**Comment by lmartins** [comment]
Im only extending TimberSite, which I imagine is provided by the plugin:
```
class StarterSite extends TimberSite {
...
```

**Comment by lmartins** [comment]
Im currently running version 0.20.10 and was getting the same error.
Im running a multisite network and was activating Timber on site-by-site basis, I've activated Timber at network level and it now works. I guess this is something related with when Wordpress runs the code associated to users creation (at network level in multisite).

Thanks.
