### ISSUE TITLE
Composer cannot resolve an installable set of packages.

### ISSUE THREAD

**Issue by tmoitie** [jarednova/timber#483]
```
Problem 1
    - Installation request for jarednova/timber dev-master -> satisfiable by jarednova/timber[dev-master].
    - jarednova/timber dev-master requires jarednova/php-router 1.0.1 -> no matching package found.
```
`jarednova/php-router` is not in packagist, and also https://github.com/jarednova/PHP-Router does not have a tag release for 1.0.1 so I cannot force the issue with a vcs repository.

I've noted there is an explicit repository inside your composer.json but from the outside my install never gets the chance to look through it before it throws the unresolvable error

**Comment by xemlock** [comment]
+1. This issue should be marked as a bug, as it makes timber not installable via composer.
