### ISSUE TITLE
Mixing WooCommerce products and regular posts in search loops

### ISSUE THREAD

**Issue by lmartins** [jarednova/timber#484]
Im still having a few issues in some loops, where Wordpress or Timber get confused about which post type is being shown at each loop cycle.

Case in point, im using @jarednova 's function in my `tease-product.twig` to set the context correctly for each product at each loop interaction, like this:

## tease-product.twig
```
{{ fn('timber_set_product', post)}}
<article {{ fn('post_class','entry', post.ID ) }}>
...
```

That function `timber_set_product` btw is this:
```
function timber_set_product( $post ) {
    global $product;
    if ( is_woocommerce() ) {
        $product = get_product($post->ID);
    }
}
```
(again, thank you @jarednova for the tip)

This does output the correct information for each product at each loop cycle, but once I get a regular posts after those, they all get the IDs from the first post in the loop.

It's easier to show on this screenshot:
![inspector_-_http___localhost_3000__s_design](https://cloud.githubusercontent.com/assets/151981/6425907/cfa2f8ee-bf37-11e4-9b42-341728239a78.png)

As you can see, after my products every post gets the same ID and post css classes on the loop, event thought these results are not products but regular posts.

Is it something I need to fix on the `timber_set_product` function so it considers when is processing a common post instead of a product?

**Comment by lmartins** [comment]
Hi Jared, 

I've found an issue with the code we've discussed before and that I published on Timber's Wiki:
https://github.com/jarednova/timber/wiki/WooCommerce-Integration#tease-product

The problem with this is that within search all the products have the same output, changing the code to:

```php
function timber_set_product( $post ) {
    global $product, $post;
    if ( is_woocommerce() || is_search() ) {
        $product = get_product($post->ID);
    }
}
```
has another side effect. 

With this version, if the results mix products and pages for example, the post classes added to the loop item stays the same for every result item, being that an product, page or post.

Do you have any tip on this so I can fix the my code and the Wiki.

**Comment by jarednova** [comment]
@lmartins I wish I knew. As the issue in #575 touches on: WordPress loops work in mysterious ways. Knowing when you're "in the loop," etc. is part of the problem. That said, the little bit of philosophy doesn't really help you here.

I wonder if you could do something in your if statement to filter out posts and pages, something like....

```php
function timber_set_product( $post ) {
    global $product, $post;
    if ( is_woocommerce() || is_search() && $post->post_type == 'product' ) {
        $product = get_product($post->ID);
    }
}
```

... would that avoid the issue of it applying to posts and pages?

**Comment by lmartins** [comment]
@jarednova 
Thank for your comments. 
The problem is actually a bit different from what you've mentioned. The issue is that the `post_class` retrieves the same output for every post in the loop. The same as the first item in the loop that is.
http://snpy.link/S8T0Mp

I think i've fixed by passing the `post.ID` to that function in the loop:

```twig
<article
    {{ fn('post_class', ['entry', entry_classes ], post.ID ) }}
    data-eq-pts="small: 120, medium: 320, large: 520, xlarge: 720"
    >

```

**Comment by WebAssembler** [comment]
Thanks @lmartins @jarednova the last fix you posted was exactly what I was looking for!
