### ISSUE TITLE
`new TimberMenu` not working with anything but IDs

### ISSUE THREAD

**Issue by lmartins** [jarednova/timber#488]
Hey,

I've noticed `TimberMenu` isn't working as described in the documentation, except when passing and ID.
When you pass the name or the menu slug the output is somewhat weird, im getting every page and category, so not sure where that's coming from.

To my use case I really need to get the ID from the menu name (or slug), so for now im resorting to the following:

```
$menu_designs_term = get_term_by('name', 'Designs', 'nav_menu');
$context['nav']['designs']       = new TimberMenu( $menu_designs_term->term_id );
``

Thanks.

**Comment by lmartins** [comment]
Ohh, I think I may have misunderstood the `TimberMenu()`.
Is it supposed to be able to retrieve menus or just registered menu positions?

What I mean by this is that I can retrieve menu positions created with `register_nav_menus()` but not menus created with `wp_create_nav_menu()`.

Could you please clarify this?

**Comment by connorjburton** [comment]
This is an old issue (just cleaning up old issues) and you have probably figured it out but yes it's just registered menus.

**Comment by lmartins** [comment]
Thank you @connorjburton, and many thanks for taking part of the Timber project.
