### ISSUE TITLE
ACF Relationship Reverse Lookup

### ISSUE THREAD

**Issue by asecondwill** [jarednova/timber#493]
I often find myself wanting to do a reverse lookup on an ACF relationship field.  Is there a nice way to do this?

I have a People Post type and a Project Post type, projects have many people, I'd like to be able to get at all of a persons projects from {{person}} where person is the TimberPost for a person.

It's a bit like whats happening for a single location here:

http://www.advancedcustomfields.com/resources/querying-relationship-fields/

Only I would like to be able to do it Just im Twig / Timber for situations where I am not in the Single-Person template.

Any Ideas?

**Comment by asecondwill** [comment]
so one, bit hacky way to do that would be:
````
add_filter('get_twig', 'add_to_twig');

function add_to_twig($twig) {
    $twig->addExtension(new Twig_Extension_StringLoader());
    $twig->addFilter('publications', new Twig_Filter_Function('publications'));
    return $twig;
}

function publications($post) {
  $args['meta_query'] = [['key' => 'people',
        									'value' => '"' . $post->ID . '"',
                          'compare' => 'LIKE']];
  $args['post_type'] = 'publication';

  $pubs = Timber::get_posts($args);
  return $pubs;
}````

which i have just put in the sites twig.php file.

**Comment by jnweaver** [comment]
Take a look at the [Wiki page for extending Timber](https://github.com/jarednova/timber/wiki/Extending-Timber). You can subclass TimberPost and add methods to your subclass for retrieving related objects, allowing you to reference, e.g., something like `person.pubs` in your Twig view. It's one of my favorite parts of Timber.

**Comment by jnweaver** [comment]
Also, it might not be evident from the Wiki page, but you also have to tell Timber to return your subclass instead of TimberPost (using the optional second argument on get_post and get_posts). So if you created a subclass called *Person* you would then call, e.g., `$context['people'] = Timber::get_posts(array('post_type' => 'person'), 'Person');` — that will return a collection of *Person* objects with your methods appended to the methods inherited from TimberPost.

**Comment by Twansparant** [comment]
I've got a slightly more complicated situation I would like to solve without any additional php templates;
In my homepage template I've got the following setup:

• **ACF Flexible Content Blocks**
• In each of the flexible content blocks an **ACF Relationship field** to connect custom post types with.
• On some of those connected post types I would like to do a **reversed query**.

In plain php templates I would know how to achieve this, but I'm a bit stuck on how to add an Array to a TimberPost that's already in a loop in a Twig template.

What I have right now, is the following:

**template-home.php**
```php
$data['sections']  = get_field('acf_content_blocks');

if( have_rows('acf_content_blocks') ):
  while ( have_rows('acf_content_blocks') ) : the_row();
    if( get_row_layout() == 'benefits_block' ):
      $ids  = get_sub_field('acf_block_benefits', false, false);
      $args = array(
        'post_type'       => 'benefit',
        'post__in'		    => $ids,
        'posts_per_page'	=> -1
      );
      $data['benefits'] = Timber::get_posts($args);
    elseif( get_row_layout() == 'cases_block' ):
      // Get connected cases
      $ids  = get_sub_field('acf_block_cases', false, false);
      $args = array(
        'post_type'       => 'case',
        'post__in'		    => $ids,
        'posts_per_page'	=> -1
      );
    	$data['cases'] = Timber::get_posts($args);
    	/* Get connected solutions */
    	$wp_query = new WP_Query($args);
    	if (have_posts()) : while (have_posts()) : the_post();
        $data['case_solutions'] = Timber::get_posts(array('post_type' => 'solution'), 'Solutions');				
      endwhile; endif;
    endif;
  endwhile;
endif;
Timber::render('home.twig', $data);
```

**timber.php**
```php
/* Add connected solutions to case */
class Solutions extends TimberPost {
  var $_solution;
  public function issue() {
    if (!$this->_solution) {
      $args = array(
				'post_type'  => 'solution',
				'meta_query' => array(
					array(
						'key'     => 'acf_solution_cases',
						'value'   => '"' . get_the_ID() . '"',
						'compare' => 'LIKE'
					)
				)
			);
      if (is_array($solutions) && count($solutions)) {
        $this->_solution = $solutions[0];
      }
    }
    return $this->_solution;
  }
}
```
**home.twig**
```twig
{% if sections %}
  {% for section in sections %}
	  <section class="{{section.acf_fc_layout}} flex_block">
      {% if section.acf_fc_layout == 'benefits_block' %}
        {% include 'block_benefits.twig' %}
      {% elseif section.acf_fc_layout == 'cases_block' %}
        {% include 'block_cases.twig' %}
      {% endif %}
	  </section>
  {% endfor %}
{% endif %}
```
**block_cases.twig**
```twig
{% block cases %}
    {{section.acf_block_title}}
    {{section.acf_block_content}}
    {% if cases %}
      <div class="cases__row row">
        {% for case in cases %}
          <article class="{{case.post_title|sanitize}} cases__case col-xs-12 col-sm-4">
            <a class="touch_effect" href="{{case.link|relative}}" title="{{case.post_title}}">
              <div class="case__info">
                <div class="entry-content">
                  <h4>{{case.post_title}}</h4>
                  {% if case_solutions %}
                    {{case_solutions|print_r}} // returns all solutions
                    <div class="solutions">{{ __('In', 'soluforce') }}: {{case_solutions.post_title|join(', ')}}</div>
                  {% endif %}  
                </div>
              </div>
            </a>  
          </article>
        {% endfor %}
      </div>  
    {% endif %}
{% endblock %}
```
Is this even possible with just 1 php template for all the data?
Thanks!

**Comment by connorjburton** [comment]
Hi guys,

I think these questions are best suited to be posted on Stackoverflow under the Timber tag. I would agree with @jnweaver's comments is the best solution.

Thanks
