### ISSUE TITLE
Get same view rendered twice

### ISSUE THREAD

**Issue by wcalderipe** [jarednova/timber#494]
I'm trying to create views to shortcodes so I'm using Timber::render to render some separate files when I need it but it's render my twice the same view and when I added a var_dump inside of Timber::render the dump is only outputted once.

Anyone have some idea of what's happen?

```language-php
if( ! function_exists( 'crystal_sc_render' ) )
{
    function crystal_sc_render( $shortcode, $data )
    {
        return \Timber::render( CRYSTAL_SC_TEMPLATES_DIR . $shortcode . '.twig.html', $data );
    }
}

if( ! function_exists( 'crystal_bottom_parallax' ) )
{
    function crystal_bottom_parallax( $attr, $content = null )
    {
        extract(shortcode_atts(array(
            'icon' 	        => '',
            'title' 		=> '',
            'label'	 		=> '',
            'href' 		    => '#',
            'button' 	    => 'READ MORE'
        ), $attr));
        
        return crystal_sc_render('crystal_bottom_parallax', $attr);
    }
    add_shortcode('crystal_bottom_parallax', 'crystal_bottom_parallax');
}
?>
```

This shortcode is called in a page once and that is it.

**Comment by lmartins** [comment]
I had a similar issue today and it was due to nested blocks being misused. Not sure if that's your situation but worth a check.

**Comment by wcalderipe** [comment]
Did you fixed it?

**Comment by ffub** [comment]
I have the same issue. I am using a filter with a custom function to replace Wordpress' default rendering for a gallery. My function renders the template using Timber but I get duplicate ouput.

**Comment by shackep** [comment]
I was able to change Timber::render to Timber::compile to get rid of the duplicate.

**Comment by ffub** [comment]
Thanks, Peter. I had too figured that out and should have updated this issue. Render does of course compile AND output.

**Comment by wcalderipe** [comment]
Use `Timber::compile` instead of `Timber::render`
