### ISSUE TITLE
PHP Fatal error:  Call to undefined method TimberImageHelper

### ISSUE THREAD

**Issue by lmartins** [jarednova/timber#495]
Im having a few issues with sites using Timber.
When I try to delete any image, I get the following error:
```
[06-Mar-2015 10:38:05 UTC] 
PHP Fatal error:  
Call to undefined method TimberImageHelper::delete_resized_files_from_url() in 
/plugins/timber-library/lib/timber-image-helper.php on line 87
```
Needless to say this is quite worrying, can you please provide any info on how to overcome this problem?

I should also point out that im using Jetpack's Photon service. I've tried disabling but it still outputting the same error.

**Comment by hrsetyono** [comment]
It also happened to me. I tried replacing the `timber-image-helper.php` with the one from version `0.20.9` and it works fine.

I'm not experienced with WP plugin development so I can't tell what caused it.

**Comment by lmartins** [comment]
Thank you @hrsetyono, lets see if one of the dev's can comment on this.
I'll also try your temporary fix to overcome the issues im having right now.

**Comment by jarednova** [comment]
Hey @hrsetyono and @lmartins thanks for raising this issue. The recent changes to the TimberImage code cleaned-up some long-standing messiness in the code but also introduced a few gaps like this that were not uncovered by automated testing and my own visual tests. Regardless, I'm working hard to resolve the last things.

Which version are you encountering these issues on, is it the WP.org version or the current GitHub master?

**Comment by lmartins** [comment]
Hey @jarednova, thanks the feedback and all the hard work.
As I said on twitter, im hoping to learn enough to be able to help somehow. 

Im running the wp.org version, should I move to the github version?

**Comment by hrsetyono** [comment]
Hi @jarednova I'm running the WP.org version. How do I use the Github one? The file structure from this repo and WP.org is different

**Comment by jarednova** [comment]
@lmartins @hrsetyono: you need to run a `composer install --no-dev` from within the `timber` directory and this will download the dependencies that are distributed with the WP.org version. Of course, you'll also need to [install Composer](https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx)

**Comment by jarednova** [comment]
... I should note that I'm working hard to get a fresh version up to WP.org; but I want to make sure the next version is bug-free before I pull the trigger

**Comment by oskarrough** [comment]
Having the same error with the WP version and tried exchanging for master as of this post, which works for me.

**Comment by hrsetyono** [comment]
@jarednova Thanks for the update! `0.21.0` fixed this issue.

**Comment by lmartins** [comment]
Fixed for me too. Closing this.
