### ISSUE TITLE
Timber 0.21.0 - Fatal Error: Class Routes not found

### ISSUE THREAD

**Issue by anugupta** [jarednova/timber#497]
WPEngine - updating Timber from 0.20.10 to 0.21.0 breaks the site completely:

`Fatal error: Class 'Routes' not found in /nas/wp/www/staging/<themename>/wp-content/plugins/timber-library/lib/timber-routes.php on line 15`

Seems to work fine on my local dev site - pushing repo changes to WPEngine broke the site. I reverted, and then did a manual plugin update via wp-admin. Same result. 

AFAICT, all necessary files are there.

**Comment by jarednova** [comment]
Hi @anugupta: try running a `composer update` and that will download the new dependencies

**Comment by anugupta** [comment]
Hey @jarednova - this is WPEngine - no command line access. 

Not sure that a plugin from the plugins directory should require a manual composer update...

**Comment by jarednova** [comment]
It shouldn't, I didn't realize you were talking about the WP.org version

**Comment by anugupta** [comment]
I can also reproduce this on a different install on my on staging server, where I use capistrano to deploy. 

* If I update locally (on my local dev server), everything is fine. 
* Commit to git, cap deploy to staging, and the site breaks,
* If I update manually (ie by clicking on update in the admin plugin page), the site breaks, with the same error,

I'm thinking, that in both cases, there might be some weird symlink / moving of wp-content and plugin folders - would this explain why the autoloader isn't being found? I'll try and debug it later today, just completely out of time at the moment

**Comment by jarednova** [comment]
@anugupta thanks so much for the heads-up on this. It was a problem with a Capitalization in one of the file names. I've fixed this on the WP.org version

**Comment by anugupta** [comment]
Did you bump the version? If not, I've tried the fix, and it doesn't seem to change anything. 

There's something going on with the autoloader - adding this line in `lib/timber-routes.php` fixes it

`require_once(__DIR__.'/../vendor/upstatement/routes/routes.php');`

I realise this isn't a solution, just trying to work out what's going wrong.

**Comment by jarednova** [comment]
The problem is that for Composer's autoload to recognize the file, it should be named `Routes.php`. Because OSX is not case insensitive it didn't raise testing errors. However, your WPEngine Box IS cAsE sensitive -- so `routes.php` isn't being recognized as `Routes.php`.

I'm going to bump the WP.org version so that the update gets pushed

**Comment by anugupta** [comment]
Ah, that's what I thought - just got confused as I thought you'd pushed the new version.

I renamed routes.php to Routes.php, and can confirm that fixes it.

**Comment by jarednova** [comment]
Great, I've released 0.21.1 to force the file re-naming. Again, thanks for bringing this to my attention!

**Comment by teohhanhui** [comment]
Can you please tag v0.21.1 for use with Composer? Thanks
