### ISSUE TITLE
Inline tags are removed when WYSIWYG is inside flexible content

### ISSUE THREAD

**Issue by laras126** [jarednova/timber#499]
My flexible content field in the Twig file:

   	{% for content in post.get_field('content') %}
    	    	{% if content.acf_fc_layout == 'section' %}
        
            	    	{% for blck in content.blocks %} 
                	    	{% if blck.acf_fc_layout == 'block_text' %}
                    		    	{{blck.text}}
                    		{% elseif blck.acf_fc_layout == 'block_list' %}
                    		    	{% include 'blocks/block-list.twig' %}
                    		 {% endif %}
                    	{% endfor %}
	
	    	{% endif %}
   	{% for %}

Where ```{{blck.text}}``` is an ACF wysiwyg field. When I add inline tags within paragraph text, they will stripped out, but anything inside a heading is okay. So, If I have this text:

### [Link in heading](http://google.com)

Nulla vitae elit libero, [a pharetra augue](http://google.com). Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.

The ```<a>``` inside the heading would be fine, but the link in the paragraph would be stripped away. Everything works correctly if the wysiwyg is not inside the flexible content. I believe this happens with a repeater as well. 

Would be an ACF specific issue or maybe a weirdness with ```wpautop```? Posted [on the ACF forum](http://support.advancedcustomfields.com/forums/topic/inline-tags-are-removed-from-s-when-wysiwyg-in-flex-contentrepeater/) as well.

**Comment by connorjburton** [comment]
Hi @laras126 - I know this is an old issue, is it still a problem? Have you tried using `the_content`?

Thanks

**Comment by laras126** [comment]
Not a problem! It was a JS issue - forgot to update this. Thanks!

**Comment by jessCmi** [comment]
I am currently having this issue, any clue what the causes might be?

```
<div class="bio-block__content--bio">
        <div id="personBlockReadMore-{{person.slug}}" class="bio-block__content--bio--text">
          {{ person.get_field('biography') }}
        </div>
</div>
```

**Comment by laras126** [comment]
@jessCmi Try `person.get_field('biography)|wpautop`?

**Comment by bubbowrap** [comment]
@laras126 Thanks a ton, I ran into the same exact problem and that fixed it!
