### ISSUE TITLE
Help needed with wrapping functions

### ISSUE THREAD

**Issue by lmartins** [jarednova/timber#503]
I was trying to implement responsive images using [this plugin](https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images).

The plugin makes a function available that outputs all image sizes for `srcset`usage like this:

    <img src="myimg.png" <?php echo tevkori_get_sizes_string( 11, 'medium' ); ?> >

Translating this to Twig, I've wrapping the function in a helper:

    $context['srcset'] = TimberHelper::function_wrapper( 'tevkori_get_srcset_string' );

And then in my template I would call the function like this:

    <img src="{{ post.thumbnail.src('medium') }}" {{ srcset( post.thumbnail.ID ) }} />

This however, wouldn't return the value anyway, but is also returning an error:

    [13-Mar-2015 19:16:54 UTC] PHP Fatal error:
    Method TimberFunctionWrapper::__toString() must not throw an exception in     
    /Users/luismartins/Sites/webipack.dev/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Environment.php(332) : eval()'d code on line 0

How can I make the function available to the template?

**Comment by lmartins** [comment]
Hi everyone, still needing help with this one, could anyone help on how to wrap a function such as `<?php echo esc_attr( wp_get_attachment_image_sizes( 'medium' ) ); ?>`

Thanks.

**Comment by dinolatoga** [comment]
`{{ function('wp_get_attachment_image_sizes', 'medium') | apply_filters('esc_attr') }}`

**Comment by lmartins** [comment]
Hi @dinolatoga, thank you so much for your input on this. :) 
Cheers man.
