### ISSUE TITLE
Timber::$dirname causes problems on specific hoster when updating to 20.1

### ISSUE THREAD

**Issue by jscontrust** [jarednova/timber#505]
I had to replace
Timber::$dirname = 'twigs';

with 

Timber::$dirname = array('twigs');

my timber instllation on hoster https://www.mittwald.de/. On my localhost, the update caused no problems. Timber::$dirname = 'twigs'; just did not add mytheme/twigs to the timber template locations which are printed out when templates are missing.

**Comment by connorjburton** [comment]
Hi @jscontrust, is this still an issue for you?

**Comment by Schwankenson** [comment]
I do not have the ability to check it anymore, so I think you can close it...
