### ISSUE TITLE
Update from 0.20.9 to 0.21.1 breaks image resize src when running through php buffer

### ISSUE THREAD

**Issue by gillesgoetsch** [jarednova/timber#506]
Timber Version 0.21.1

twig:
```
<div class="inner">
   <img src="{{ this.image.url|resize(510, 280) }}">
   {{ this.title }}
</div>
```

now produces:
```
<div class="inner">
<img src="�����JFIF���������;CREATOR: gd-jpeg v1.0 (using IJG JPEG v80), quality = 90
���

```
.....

This only appears when buffering the twig output through the "ob_start();" function and saving it in a variable with "ob_get_contents()".
Calling twig directly via the normal way produces the proper output. Buffering the twig output is used for a json-api.

**Comment by jarednova** [comment]
Thanks @gillesgoetsch! will look into

**Comment by jarednova** [comment]
@gillesgoetsch -- I tried writing a test around the scenario you proposed but everything seemed to work. Can you try switching `{{ this.image.url }}` --- to ---> `{{ this.image.src }}` and see if that resolves?

**Comment by lmartins** [comment]
Having the same issue, and the only way I can get around it is by passing a built-in image size `image.src('thumbnail')` instead of arbitrary sizes `image.src|resize(320,240)`

**Comment by gillesgoetsch** [comment]
Thanks @jarednova for your investment.

Here is my followup as I do have this problem now even when no output buffering is used.
Here are my findings during the debug-session:

**The Error**
The Error actually appears because of the wordpress main image function for editing images (wp_get_image_editor). To be exact, when saving the image (more details bellow) - throwing following Error after outputting the whole image-src into the html: *Warning:  fopen(http://project.int/content/uploads/2015/03/01-5x5-c-default.png): failed to open stream: HTTP wrapper does not support writeable connections in /Applications/MAMP/htdocs/project/wp/wp-includes/class-wp-image-editor.php on line 424 /content/uploads/2015/03/01.png');*

This might explain why you cannot reproduce the error. The issue seems to be dependent on write access and may only appear on specific environments. However this is still an issue..

**Appearance in Timber**
Yes, I digged a bit into the source-code and had some findings:

- In "timber-image-helper.php" timber is using the function *_operate* (line 376) to generate the paths / source-urls for the images for the different resize types, passing it on to the resize operation.

- This resize-operation *$op->run($old_server_path, $new_server_path)* (called in the same File, line 414) makes the error / image-output as returned so from passing it further to function *run* inside timber-image-operation-resize.php.

- Here the "bad" magic happens when using the native wordpress function to save the cropped image *$image->save( $save_filename );* now *$save_filename* starting with http://project.int/.. Most likely opening it as an http-connection which fails to write the image onto the filesystem and returning those errors.

- I did some testing with cutting the path / $save_filename from *http://project.int/content/uploads/2015/03/01-5x5-c-default.png* to */content/uploads/2015/03/01-5x5-c-default.png* which then created the image properly and gave the return back as the expected url. However this is not a throughly testet solution.

**Conclusion**
I guess the whole error needs some more debugging and a clean fix. Hope this helps with understanding the issue, which enough users are experiencing now..

Let me know if I can give any more help on this. In the meantime using the predefined images-sizes might be the only way to get around this. Good luck :+1:

**Comment by gillesgoetsch** [comment]
Ok, I've found the solution. It seems to be a permission-issue that appears if your wordpress content directory is not in the wordpress-installation directory. To fix this add the following code to your wp-config which declares the external content directory explicitly:

```
define('WP_CONTENT_URL', 'http://' . $_SERVER['HTTP_HOST'] . '/content');
define('WP_CONTENT_DIR', $_SERVER['DOCUMENT_ROOT'] . '/content');
```

Replacing "/content" with your actual content dir. Changing ``WP_CONTENT_URL`` from ``/content`` to ``http://domain.dev/content`` did the magic for me. Hope this helps, glad to use the resize functionality again.

**Comment by ogrosko** [comment]
Hey 

I have exactly the same problem (Timber v 0.21.7/9)

I trying to resize youtube thumbnail

{% set img = TimberImage('http://img.youtube.com/vi/'~video.youtube_video_id~'/0.jpg') %}
{{img.src|resize(20, 20)}}

WP_CONTENT_URL and WP_CONTENT_DIR I have set to /wp-content dir

any news about it?
