### ISSUE TITLE
TimberPost and WPML: retrieving the post in the correct language

### ISSUE THREAD

**Issue by JoaoSaleiro** [jarednova/timber#509]
It seems TimberPost cannot get the post in the correct language when using WPML.

I'm using Timber with WPML, and so far it works great, except if you need to retrieve the post manually. 
In other words, I have a page called "about-us" that is translated in pt_PT and en_US , and has a corresponding about-us.twig. If I navigate to http://mysite.com/about-us it shows the content of the page in the correct language.
But If I need to retrieve manually the page about-us using TimberPost, it will only retrieve the original language. Example below:

```php
$context['about_us'] = new TimberPost('about-us')
// The $context['about_us'] should have the pt_PT or en_US version 
// of the about-us page, depending on the language we are on
```

Is this a know issue, or am I doing something wrong?
Is there a workaround?

**Comment by JoaoSaleiro** [comment]
My solution for this was doing:
```php
$context['about_us'] = new TimberPost(get_page_by_path('about-us'));
```

Not sure if it's the best way, though

**Comment by addedlovely** [comment]
Why not just use the ID of the post for that language, and let WPML translate the ID to the current language.

See the WPML Object ID filter.
https://wpml.org/wpml-hook/wpml_object_id/

**Comment by connorjburton** [comment]
Going to close this as there seems to be a couple of solutions. Feel free to comment if it's still an issue.

**Comment by chaladm** [comment]
hi addedlovely, i'm having this same issue. How do you use wpml_object_id with timberpost

**Comment by addedlovely** [comment]
@chaladm see the examples on the link.


```
// will return the post ID in the current language for post ID 1
$translatedID =  apply_filters( 'wpml_object_id', 1, 'post' );

// load post, and add to context
$context['about_us'] = new TimberPost($translatedID);

```
