### ISSUE TITLE
Timber::get_posts inside of twig file

### ISSUE THREAD

**Issue by TristanSlater** [jarednova/timber#513]
Is it possible to create a query within a twig file? In my case, I'd like to replace `posts` with a new query. For example:

    {% set posts = Timber.get_posts('post_type=pages') %}

This is impossible in PHP, because I need to use `posts` in the twig file *before* I replace it. I could use something like `pages`, and loop through that, but then I can't use generic templates.

Is this something Timber supports?

Thanks,
Tristan

**Comment by TristanSlater** [comment]
I found a solution I am going to use for now. I just add the query via PHP to a context key called `pages`, but then in the for loop go `{% for post in pages %}`. Then I can include twig files using `post` as the post obj and everything works.

Would still be nice to know if my original question can be done.

Thanks,
Tristan

**Comment by connorjburton** [comment]
Hi @TristanSlater, sorry for delayed reply. I think adding via the context in PHP is the preferred way to be honest.

If you really wanted to do it the way above, on the next Timber release you should be able to do the following (though not tested)

```php
TimberHelper::function_wrapper(array('Timber', 'get_posts'));
```

Then you'd be able to do

```twig
{% set posts = get_posts('post_type=pages') %}
```

**Comment by TristanSlater** [comment]
Thanks. Adding it to the Twig file is fine.

The one thing I still find tricky though is when you have nested child
posts inside posts. Right now, I just get the parent posts and then loop
through the posts array and get the child posts for each one and add them
to the array in the PHP file. Then I use nested loops again in the Twig,
but this seems really inefficient. Is there a way to get child posts with a
query?

**Comment by connorjburton** [comment]
Hm, to be honest this may be a limitation of Wordpress, everything I have read about getting children and what I have personally done is add another loop.

AFAIK the loop in twig really won't be expensive at all. The big limiting factor with performance in Wordpress is usually the DB queries.

If you are doing the same call multiple times on the same page to the same children posts then you could memoize (http://stevephillips.me/blog/quick-and-dirty-php-memoization) the function, that'd help.

Maybe @jarednova knows a more efficient way?
