### ISSUE TITLE
TimberArchives not working

### ISSUE THREAD

**Issue by ogrosko** [jarednova/timber#516]
Hey

when I use new TimberArchives(array(some arguments)) I'm still getting the same result. Arguments has no effects.

Problem is line 139:
$type = $limit = $order = $post_type = $nested = $format = $before = $after = null;
than extract($r, EXTR_SKIP); skips all params.

I sole this by commenting line 139

also show_post_count not working

**Comment by jarednova** [comment]
@ogrosko -- thanks for your note. I did a lot of work today cleaning it up. It's now merged into master
