### ISSUE TITLE
Timber::get_posts() unable to get attachment post_type

### ISSUE THREAD

**Issue by esiao** [jarednova/timber#518]
Hello, I'm facing an issue related to Timber and the starter theme. When I do a query for attachment type

    $args = array(
       'post_type' => 'attachment'
    );
    $images = Timber::get_posts($args);
    //$images = new WP_Query($args);

Both will return an empty array even if I have attachments. And the weird thing is that it's working on a non Timber theme. Any insights ?

Using

    $images = get_posts($args)

Seems to work.

**Comment by jarednova** [comment]
@esaio this is probably because the `post_status` on attachments is set to `inherit`, while by default WP looks for `post_status=publish` try...
```php
$args = array(
   'post_type' => 'attachment',
   'post_status' => 'inherit',
);
$images = Timber::get_posts($args);
```

**Comment by jarednova** [comment]
@esiao it appears that WP's `get_posts` will ignore the `post_status` parameter on attachments. However, `WP_Query` (which Timber uses) requires you to set it to `any` or `inherit`, from the WP_Query docs:

![screen shot 2015-04-07 at 9 12 37 pm](https://cloud.githubusercontent.com/assets/1298086/7037091/fe9f4df4-dd6a-11e4-9277-121200facf90.png)
