### ISSUE TITLE
resize filter should understand WordPress named image sizes

### ISSUE THREAD

**Issue by teohhanhui** [jarednova/timber#524]
i.e. `{{ ...|resize('medium') }}` which allows for a consistent syntax

Inspired by https://github.com/liip/LiipImagineBundle (for Symfony2 framework)

**Comment by jarednova** [comment]
Totally agree, would this be something you (or someone) is interested in working on a PR for?

FYI, you can right now do `{{ my_image.src('medium') }}`, but if that size hasn't already been generated you'll just get back an empty string

**Comment by teohhanhui** [comment]
If anyone wants to implement this, I think this will be good reference: https://gist.github.com/timkinnane/e82eb87d9cc489620b80

**Comment by zlove** [comment]
Shouldn't this be closed? It looks like this has been implemented for awhile.

**Comment by teohhanhui** [comment]
The [wiki page](https://github.com/jarednova/timber/wiki/Image-cookbook) should be updated, as the `.src(...)` method is flawed (see https://github.com/jarednova/timber/issues/524#issuecomment-93587120)

**Comment by connorjburton** [comment]
Thanks @teohhanhui, will get it updated.

**Comment by connorjburton** [comment]
Updated the wiki
