### ISSUE TITLE
Backend admin UI configuration

### ISSUE THREAD

**Issue by ogrosko** [jarednova/timber#528]
It would be great if there will be some backend administration UI config. Like clear cache button. Set default cacheTime, cacheMode etc.
What do you think?

**Comment by ogrosko** [comment]
Hey check this https://github.com/ogrosko/timber-clear-cache
Please don't kill me ;) It's my first WP plugin and I wrote it in 30minutes

I would need something like this

**Comment by ogrosko** [comment]
Hey any news about this issue?

**Comment by connorjburton** [comment]
Hi @ogrosko, this is something we may look at as an add-on for `Timber` rather than part of the core. I will take a look at the plugin once we have cleared a bunch of bugs out the way.
