### ISSUE TITLE
Global $wp_query object

### ISSUE THREAD

**Issue by anugupta** [jarednova/timber#530]
Is there a 'Timber' way for accessing the global $wp_query object?

I have a taxonomy archive `taxonomy-resourcetype}.php`  and want to be able to see what term `resourcetype` is.

I can do this with:

    global $wp_query;
    $archive_term_name = $wp_query->query_vars['resourcetype'];

but is there a better way?

**Comment by djmadeira** [comment]
If you want to find out what the title of an archive page should be, you could use the WP function `get_the_archive_title()`. Add that to the $context in your `taxonomy-resourcetype.php` and you'll be all set.

**Comment by anugupta** [comment]
`Timber::get_context()` injects the entire `$wp_query` object into `$context['posts']->_query`, but this is private. Typically `$context['posts']` will get overwritten by `$context['posts']  = Timber::get_posts()`, but in any case as `_query` is private, it can't be accessed.

Should I just add the `query_var` portion of the `$wp_query` object to `$context` myself? Really, at this point, it's more about style and using Timber idiomatically - I know I can get this data in a number of different ways, just trying to work out the most elegant.

**Comment by connorjburton** [comment]
It seems wordpress does have built in functions to grab this data, as @djmadeira - I'm not sure it would be beneficial to add wrappers around those, can't see much benefit myself.

I think @djmadeira is the best solution here, I wouldn't access `$wp_query` directly
