### ISSUE TITLE
Use Twig_Loader_Filesystem instead of Twig_Loader_String?

### ISSUE THREAD

**Issue by graphikjunkie** [jarednova/timber#531]
Great work on this plugin. We use Twig on my team at work and it is world's apart from sprawling php functions or heredoc templates. Embedding it into WordPress is awesome. 

Just curious why you opted to use Twig_Loader_String instead of Twig_Loader_Filesystem and setting a basepath for the location of views? 

In the Sensiolabs documentation it does state "This loader should NEVER be used. It only exists for Twig internal purposes".

**Comment by ivanjuras** [comment]
+1, I'd like to know that too :).

**Comment by tommymarshall** [comment]
+1 as well.

**Comment by jarednova** [comment]
Oh geeze, what have I done?!?!?! I'm not sure. I'll take a look and see if I can figure out why I did that

**Comment by connorjburton** [comment]
Discussion for this has moved to #863 and will be resolved soon.
