### ISSUE TITLE
Does Timber work on Multisites?

### ISSUE THREAD

**Issue by adamsr13** [jarednova/timber#532]
The reason I asked is that I used the example on the Timber install page, created a views folder inside my Theme, etc. And I do not see any changes.

rad1964

**Comment by jarednova** [comment]
Yup! I've used it successfully on multisite installs and each build is tested against multisite:

https://travis-ci.org/jarednova/timber/jobs/58482630

**Comment by lmartins** [comment]
I've been using it on a multisite environment for months now. No issues related to being on a multisite.

**Comment by iamkevingreen** [comment]
I'm running it in a multisite + WPML environment and it works great

**Comment by Buooy** [comment]
Using it on a wordpress Multisite platform and loving it!
