### ISSUE TITLE
Having trouble setting a custom page as the site homepage

### ISSUE THREAD

**Issue by lmartins** [jarednova/timber#533]
Usually the way I setup the homepage using timber is by setting the file `front-page.php` call a twig file I arrange according to my need. 
This time though I need to have a regular page set as the site home page, so I've followed the steps:

* Created a template file `template-home.php`
* Created a new page, assigned to the template above
* Configured the site to use that as the front-page

Among other pieces of code, `template-home.php` has the following contents:

```twig

$context = Timber::get_context();
(...)

$templates = array('home.twig');
Timber::render($templates, $context);
```

But for some reason when I load the site the front essentialy loads the header and footer, which comes from `base.twig`, which `home.twig` is extending.

Am I missing something obvious here?

**Comment by bezierer** [comment]
Did you try defining which page gets uses which twig file in index.php, like so:

<pre>
if (is_single()) {
    $template = 'blog-post';
} else if (is_front_page()) {
    $template = 'front-page';
}
</pre>

**Comment by lmartins** [comment]
Thanks Cameron, I don't `index.php` will any influence here as Im setting a specific template and that is being loaded instead. If I remove my custom template will then fallback to `page.php` and if that doesn't exist will finally try to display using `index.php`. 

Unless im missing something this is how it works, however for some my template isn't rendering the twig file.

**Comment by connorjburton** [comment]
@lmartins I assume this is okay now?

**Comment by lmartins** [comment]
Absolutely.
