### ISSUE TITLE
Any way to fetch comment form fields and data?

### ISSUE THREAD

**Issue by ivanjuras** [jarednova/timber#534]
I was wondering if there is a way to fetch the comment_form object so that I could do something with it.

For example, I want to create a new twig file which adds markup to every field of the comment_form.

**Comment by igregson** [comment]
+1 for this. 

Even something as simple as adding placeholder text doesn't seem possible via the current implementation. 

Any suggestions on how to go about this?

**Comment by ivanjuras** [comment]
Yeah, the comments.php file is so tiresome to edit, just like almost everything else is ( with pure WP PHP, of course :) ).

**Comment by ivanjuras** [comment]
@jarednova is there any way to implement this? It would make it sooo much easier to edit comments. I'd do it, but I'm just a front-end dev, I don't know PHP that well.

**Comment by jarednova** [comment]
@ivanjuras @igregson  just to make sure I have you correct: would a `.twig` snippet (maybe an addition to the [starter theme](https://github.com/Upstatement/timber-starter-theme)) with the comment form HTML/variables exposed so you can have your way with the placeholder/default/fields/etc.?

**Comment by ivanjuras** [comment]
@jarednova Yes, the best thing you could do is to extract all the comment-form ( if I'm not mistaken, it's this one here: http://codex.wordpress.org/Function_Reference/comment_form ) variables into something more readble, and something easier to edit.

You could build it into the original $context variable, so that we can call it someting like  {{ comment_form.name }} in our twig files.

**Comment by igregson** [comment]
Agreed :)

**Comment by connorjburton** [comment]
Hey all, apologises for my ignorance, is this solved with https://github.com/timber/starter-theme/blob/master/templates/comment.twig?

**Comment by connorjburton** [comment]
As this seems inactive I am going to close this for now, let me know if it's still an issue and I will re-open.
