### ISSUE TITLE
problems with php-fpm

### ISSUE THREAD

**Issue by quinn** [jarednova/timber#537]
Hi there,

I recently switched a project using timber to use php-fpm instead of apache + mod_php. After I switched, some templates weren't showing changes until I restarted php-fpm. I realize there could be any number of things going wrong here, but I thought i'd post this question and see if it rang any bells.... thank you!

**Comment by quinn** [comment]
let me clarify: changes to the actual templated showed up, but the context of the template would not be changed, even if the data being passed to it changed. spooky!

**Comment by connorjburton** [comment]
Hi @quinn - is this still an issue?

**Comment by quinn** [comment]
i don't remember how i fixed this but it's no longer an issue.

**Comment by connorjburton** [comment]
Okay thanks for getting back to me.
