### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by marvinhagemeister** [jarednova/timber#538]
I've just switched my site to Timber and I'm loving it a lot so far! Everything works fine, except this debug message:

Notice: Array to string conversion in /var/www/mysite/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Environment.php(332) : eval()'d code on line 108
Array

**Comment by marvinhagemeister** [comment]
Eeks! Should have digged in deeper before submitting this report. The problem was in my template where I tried to echo an array:

<p>{{ myarray }}</p>

**Comment by jarednova** [comment]
Eeeks! That'll happen; you'll find this little diddy helpful:

```twig
{{ myarray | print_r }}
```
