### ISSUE TITLE
Any ideas?

### ISSUE THREAD

**Issue by maketimetodesign** [jarednova/timber#539]
I appreciate this isn't a support forum, but had an issue when deploying a new version of our clients site. So decided to roll back to last known commit but now throwing this error:

Fatal error: Class 'PHPRouter\Router' not found in 
******************/wp-content/plugins/timber-library/lib/timber-routes.php on line 30

Can anyone throw any light on the issue?! (URGENTLY if possible! :)) 
Assumed it was something to do with the Github version VS Wordpress.org but I've used the WP.org version...

**Comment by maketimetodesign** [comment]
This was the first error we got:

Fatal error: Class 'Routes' not found in ......

**Comment by anugupta** [comment]
Looks like something might have gone wrong with your rollback - I think PHPRouter is the old router that Timber used to use, before it got switched out for AltoRouter.

So - check on the server in `/wp-content-plugins/timber-library/vendor/` to see if you've got an `altorouter` folder. If so, that's probably the issue. You can download older plugin versions here: https://wordpress.org/plugins/timber-library/developers/ - you just need to get the one you were using previously.

**Comment by maketimetodesign** [comment]
Amazing @anugupta, thanks for helping out with this! Typical, meant to be going live with the new version and all this explodes! I've managed to get the site working by completely deleting the plugin and re-uploading via FTP...I guess there may have been something conflicting in Codebase that was throwing the error...going to have to trial and error to see if I can resolve the issue!

Thanks again!

**Comment by anugupta** [comment]
You're welcome - glad that helped :)
