### ISSUE TITLE
Leveling up the timber starter theme

### ISSUE THREAD

**Issue by bryanaka** [jarednova/timber#55]
The starter theme included is good for a beginning reference, but definitely has room to be improved to resemble at least something like a port of Automattic's [underscores](http://underscores.me/).

I am working on something with influence from underscores with bootstrap 3. Would you like something like that as a bundled starter theme or maybe something a bit less verbose?

**Comment by connorjburton** [comment]
Going to close this as https://github.com/timber/starter-theme seems to be pretty good now!
