### ISSUE TITLE
TimberHelper::function_wrapper() converts function output to string

### ISSUE THREAD

**Issue by aaronhipple** [jarednova/timber#551]
I was playing around with using TimberHelper::function_wrapper() and a function returning an array with the idea of using some language like this in the Twig file:
```
{% set link = get_post_link(post.ID) %}
<a href="{{link.href}}" target="{{link.target}}">...</a>
```
Unfortunately, this doesn't work, and throws a warning `Notice: Array to string conversion in /var/www/fsm-wp-env/wp-content/plugins/timber-library/lib/timber-function-wrapper.php on line 50`

Removing the explicit `(string)` from [this line](https://github.com/jarednova/timber/blob/master/lib/timber-function-wrapper.php#L50) seems to allow the behaviour I'd like without issue.

Is there some unintended consequence I'm not finding? Is explicitly casting this to a string keeping a horrible kraken at bay, or would it be possible to permit the passing of arrays (or other types?) as return values from functions?

**Comment by jarednova** [comment]
@aaronhipple -- thanks for filing. I have a patch: #584. I'd love your evaluation and feedback before I merge into master, thanks!

**Comment by ste93cry** [comment]
Just one note, it seems that in the patch #584 the indentation was changed from spaces to tabs. I don't know if this is right, but usually tabs are not used in common code styles.

**Comment by jarednova** [comment]
@ste93cry after much hemming (and hawing) I decided to stick with WordPress coding standards about a year or so ago to keep things consistent. They prescribe [to use tabs over spaces](https://make.wordpress.org/core/handbook/coding-standards/php/#indentation) so here we are...

**Comment by ste93cry** [comment]
Oh, I didn't know they used tabs instead of spaces. What a bad thing :(

**Comment by jarednova** [comment]
Luckily it's the only bad thing that WordPress does, right? Right? Thanks for the note on that file, I'll zap those

**Comment by aaronhipple** [comment]
Heh. Yes, we're quite fortunate that WordPress is otherwise immaculate.

Thanks for checking this out @jarednova, in my testing that change did everything we needed it to do without causing any terrible side effects. If you're happy with it, we're happy!
