### ISSUE TITLE
Version 0.21.2 breaks menu/static posts page

### ISSUE THREAD

**Issue by nevinlaughlin** [jarednova/timber#552]
When using version 0.21.2 and setting your posts page to a static page (ie.blog), I get the following errors.
![blog_with_error](https://cloud.githubusercontent.com/assets/5831003/7902870/8f15ced0-0796-11e5-8627-62b877e5d43b.png)

Here's a screen of it working using version 0.21.1:
![blog_without_error](https://cloud.githubusercontent.com/assets/5831003/7902869/8f13065a-0796-11e5-9f80-b943588dfa04.png)

I haven't been able to figure out the issue yet. I'm using fresh install of wordpress with the timber starter theme.

Thanks for everything!

**Comment by brad-decker** [comment]
I'm noticing a similar issue with using get_posts. instead of grabbing x recent posts it grabs x copies of the very first blog post made on the site.

**Comment by xymurgist** [comment]
Plus one to this. I'm having the same issue after updating to 0.21.2. 

To redo this error, assign a static page as 'posts page' in `Settings > Reading > Front page displays > *the static page*`. You'll then get the following warnings for each iteration of the menu array when you visit the page.

```
Warning: array_merge(): Argument #2 is not an array in .../wp-content/plugins/timber-library/lib/timber-menu-item.php on line 131

Warning: array_unique() expects parameter 1 to be array, null given in .../wp-content/plugins/timber-library/lib/timber-menu-item.php on line 132

Warning: implode(): Invalid arguments passed in .../wp-content/plugins/timber-library/lib/timber-menu-item.php on line 134
```

**Comment by lifeforms** [comment]
We've seen the same thing. In `error_log` we get very similar warnings as the OP describes, and the items seem duplicated and without content.

![image](https://cloud.githubusercontent.com/assets/3464056/7963723/7183a1b4-0a14-11e5-9e2c-b7a54bcd9eb7.png)

Reverting back to 0.21.1 resolves the issue.

I haven't really looked at the plugin internals ever, but if there's something I can do to test or debug I am game.

**Comment by slimndap** [comment]
I have the same issue when I set a static front page, but _only_ on the posts page.

**Comment by jarednova** [comment]
Hey all! I'm taking a look at this right now. Hope to have a fix over the weekend.

**Comment by thisislawatts** [comment]
I've just added another check into the conditional so it's not used on post pages

**Comment by prisis** [comment]
some news?

**Comment by jarednova** [comment]
@prisis working as we speak!

**Comment by jarednova** [comment]
@nevinlaughlin @lifeforms @prisis @thisislawatts @xymurgist @slimndap thanks much for the nudges on this issue. I have a patch ready as a PR:

https://github.com/jarednova/timber/pull/558

... I've also done testing on my side to confirm this fixes the error ID'd by @nevinlaughlin. I'll merge the PR in once the Travis tests complete. If you find more specific issues, please open up a new issue so I can dive-deep and fix these buggers.

**Comment by brad-decker** [comment]
thanks @jarednova

**Comment by prisis** [comment]
thanks @jarednova <3

**Comment by thisislawatts** [comment]
👌

**Comment by lifeforms** [comment]
@jarednova We've tried out the fix and it works awesome, thanks!
