### ISSUE TITLE
TimberPost ignores $pid for a static posts page

### ISSUE THREAD

**Issue by zlove** [jarednova/timber#553]
When creating a new TimberPost on a page designated the static posts page, the $pid passed to the constructor is ignored, and the TimberPost is created for the static posts page Post, not the Post ID requested. 

It looks like this is the offending condition in TimberPost->determine_id() (timber-post.php line 55). Shouldn't there be a check for `$pid === null` before the rest of the conditions?

    if ($wp_query->is_home && isset($wp_query->queried_object_id) && $wp_query->queried_object_id )  {
        		//hack for static page as home page
                ...
    }

**Comment by kylehotchkiss** [comment]
I recieve a similar issue with "Blog Posts" page - 

the entire array of posts is filled with the "blog post" page itself. Changing wp query does not fix

**Comment by xymurgist** [comment]
This maybe related to this issue: https://github.com/jarednova/timber/issues/552

**Comment by jarednova** [comment]
@zlove @kylehotchkiss @xymurgist  thanks much for the nudges on this issue. I have a patch ready as a PR: https://github.com/jarednova/timber/pull/558

... I've also done testing on my side to implement the change suggested by @zlove and everything checksout. I'm going to wait for the Travis checks to finish and then merge this into master.

**Comment by zlove** [comment]
Great. Glad to see this fixed. Thanks @jarednova

**Comment by xymurgist** [comment]
Thank you @jarednova!
