### ISSUE TITLE
Deleting image in media library throws error in timber-image-helper.php

### ISSUE THREAD

**Issue by addedlovely** [jarednova/timber#557]
When in the media library in the admin area, (wp-admin/upload.php?mode=list) deleting an image throws the following error:

Warning: Invalid argument supplied for foreach() in 
/plugins/timber-library/lib/timber-image-helper.php on line 193

This is on the most recent version of Timber and Wordpress, replicated on a clean install.

**Comment by connorjburton** [comment]
Hi @addedlovely - is this still an issue for you?

**Comment by addedlovely** [comment]
@connorjburton haven't noticed it since, assume it's resolved in more recent version. Thanks for checking in.
