### ISSUE TITLE
new TimberPost does not use the ID passed in some situations

### ISSUE THREAD

**Issue by asecondwill** [jarednova/timber#561]
If i pass an id into  

```` new TimberPost(3244) ````

i get the event post i want for my footer almost everywhere.  Not the blog index page though.  

Checking the code in timber-post.php , I can make it work right by commenting out the determine_id line

````
function __construct($pid = null) {
    	//$pid = $this->determine_id( $pid ); now it works
        $this->init($pid);
    }
````

looking at that method, there is nothing in there to just return the ID passed to the constructor

````
protected function determine_id($pid) {
    	global $wp_query;
        if ($pid === null &&
        	isset($wp_query->queried_object_id)
        	&& $wp_query->queried_object_id
        	&& isset($wp_query->queried_object)
        	&& is_object($wp_query->queried_object)
        	&& get_class($wp_query->queried_object) == 'WP_Post'
        	) {
            $pid = $wp_query->queried_object_id;
    	} else if ($wp_query->is_home && isset($wp_query->queried_object_id) && $wp_query->queried_object_id )  {
    		//hack for static page as home page
    		$pid = $wp_query->queried_object_id;
        } else if ($pid === null) {
        	$gtid = false;
          $maybe_post = get_post();
          if (isset($maybe_post->ID)){
    			  $gtid = true;
    		  }
          if ( $gtid ) {
        	   $pid = get_the_ID();
    		  }
        }
        if ($pid === null && ($pid_from_loop = TimberPostGetter::loop_to_id())) {
            $pid = $pid_from_loop;
        }
        return $pid;
    }

````

I think that's a bug right? ill do a pull request.

**Comment by jarednova** [comment]
Thanks for the issue and the PR @asecondwill. I want to make sure I understand (and can write an appropriate test) for the issue you're encountering. Can you give me a better understanding of...

- **Where this occurs?** specific filename and how it relates to your setup. You mention a blog index page, is that the same as a posts page set to a static page set in wp-admin/options-reading.php ?
- **What you're expecting**?
- **What happens instead**?

Once I have that I'll (try) to write a test, demonstrate that the current code fails and that your PR fixes it. Merge. Deploy!

**Comment by asecondwill** [comment]
I updated Timber today, and yet it didn't revert my fix on my site.  Wondering if i had gone mad, i've been through TimberPost's history

https://github.com/jarednova/timber/commit/b02ef30cf9730fc0a98251832d0c86b243bf5ae9


the issue was fixed back then on line 55, with the test for PID  ===null.  Must have had an old version of Timber on my stage server. Sorry.  never mind.  Closing!

w
