### ISSUE TITLE
WYSIWYG fields within an ACF repeater field

### ISSUE THREAD

**Issue by vincentGustav** [jarednova/timber#563]
Good Day,

Quick question, I have a WYSIWYG field inside a repeater. The docs on Timber mention that in order for the content of a WYSIWYG field to be formatted (tags stripped etc) properly you must call it like:

```
{{post.get_field('wysiwyg_field')}}
```

However, later in the docs it mentions that subfields of ACF repeater fields should never be called with the .get_field('some_field') syntax and instead they should be called like repeater.wysiwyg_field

While the repeater.some_field works for all other fields I have tried, the proper formatting for the wysiwyg field is not being outputted.

Anyone run into this issue before and have a solution?

Thanks!

**Comment by thisislawatts** [comment]
Have you looked at using the `wpautop` filter?
https://github.com/jarednova/timber/wiki/Text-Cookbook

Alternatively you could add a filter to Twig that pushes text through WordPress' the_content filter.
https://github.com/jarednova/timber/wiki/Extending-Timber

**Comment by jnweaver** [comment]
I think you can also use:
```
{{ repeater.wysiwyg_field |apply_filters('the_content') }}
```

**Comment by vincentGustav** [comment]
Thanks, appreciate the help! Looks like this solved the issue.

**Comment by corradomatt** [comment]
@vincentGustav - While I am a huge fan of ACF, it's also a good idea to not use ACF functions so that you're project isn't so tightly coupled to that plugin - http://www.billerickson.net/advanced-custom-fields-frontend-dependency/

**Comment by vincentGustav** [comment]
@corradomatt really interesting read and also a good point. Definitely going to do this on the next project.    Thanks for passing along the link!
