### ISSUE TITLE
WordPress with Timber / Twig

### ISSUE THREAD

**Issue by Melusine49** [jarednova/timber#566]
Hi

I would like to test whether you are on the home page but I can not find the correct syntax.

I tested this:
{% if page == 'home' %}
	home
{% else %}
	TEST
{% endif %}

but it still shows TEST ..

Thank's in advance
Mélusine

**Comment by jarednova** [comment]
Hi @Melusine49, `page` is not a pre-defined value, to make this work, you would need some PHP...

```php
if (is_home()) {
    $context['page'] = 'home';
}
Timber::render('mytemplate.twig, $context);
```

... then your sample Twig snippet would work

**Comment by Melusine49** [comment]
Hi

It doesn't work .. I have to do my test in the header (basic template) to display or not a tag (a < h 1 >).

I put in PHP:
<pre>if(is_home()){
	$context['page'] = 'home';
}</pre>

And in my basic template:
<pre>{% if page == 'accueil' %}
	home
{% else %}
	TEST
{% endif %}</pre>

Thank's in advance
Mélusine

**Comment by Melusine49** [comment]
Hi
I found the solution. We must put this in php:
<pre>$context['page'] = 'home';</pre>

and this in html:
<pre>{% if page == 'home' %}
	HOME
{% else %}
	OTHER
{% endif %}</pre>

Thanks for your help
