### ISSUE TITLE
WordPress.org asking for Composer Install

### ISSUE THREAD

**Issue by lmartins** [jarednova/timber#567]
Hi,

Im starting a new project on which I've installed everything from scratch. After installing Timber (from WordPress.org), im getting the following error:
```
Fatal error: You have not run "composer install" to download required dependencies for Timber, you can read more on https://github.com/jarednova/timber#installation in /srv/www/idomlive/htdocs/wp-content/plugins/timber-library/timber.php on line 63
```

**Comment by jarednova** [comment]
Oh composer. Can you provide some server details: let's start with PHP version?

**Comment by lmartins** [comment]
Hi Jared, this is what I get with `php -v`:
```
vagrant@vvv:~$ php -v
PHP 5.5.9-1ubuntu4.7 (cli) (built: Mar 16 2015 20:47:39)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

**Comment by jarednova** [comment]
ugh, oh well -- thought that might lead us to an easy answer. I've verified on my side with a fresh install that things are working. However, on your end, for some reason the check for the `Twig_Autoloader` is failing. The only thing I can think of is that some file(s) didn't download or copy correctly. Can you take a screenshot of the file structure from `/timber-library` down to `Twig/lib`? Here's what mine (from a comparison fresh test install) looks like for comparison:

![screen shot 2015-06-11 at 8 40 10 am](https://cloud.githubusercontent.com/assets/1298086/8107194/8c528436-1015-11e5-9eeb-bc45be56f0da.png)

**Comment by lmartins** [comment]
Hey Jared,
I think it's safe to assume it is fine on repo. I had other plugin complaining about failed install (it wasn't the case for Timber) and only when you mentioned that possibility I've remembered what happened when I was installing all the plugins.
If I see it happen again i'll reopen this.
Thank you for your help.
