### ISSUE TITLE
Support for Twital

### ISSUE THREAD

**Issue by asecondwill** [jarednova/timber#571]
A nice idea.  

https://github.com/goetas/twital

**Comment by jarednova** [comment]
Cool stuff! Plate's a little crowded right now but this is a really interesting extension for down-the-line

**Comment by connorjburton** [comment]
Hi @asecondwill, I know you posted this a long time ago, just clearing up some issues. As @jarednova, this will probably be better off as an extension or V2 of Timber.

I'm going to close this for now.

**Comment by asecondwill** [comment]
@connorjburton  - no worries connor.  I've not done much WP work for a while. the trail went cold on a few of these tickets, makes sense to close them now like you have.
