### ISSUE TITLE
get_option doesn't work in .twig file

### ISSUE THREAD

**Issue by andricicezar** [jarednova/timber#573]
Hello,

I register the option with (this works):
```php
  $wp_customize->add_setting( 'post_a_demand_text' , array(
    'default'     => 'Post a demand',
    'transport'   => 'refresh',
  ) );

  $wp_customize->add_control( new WP_Customize_Control( $wp_customize, 'post_a_demand_text', array(
    'label'        => __( 'Post a demand (text)', 'frec' ),
    'section'        => 'frec_texts',
    'settings'   => 'post_a_demand_text',
  ) ) );
```

I get the option with this after I set a value from Customize page:
```php
$context = Timber::get_context();
print_r(get_option("post_a_demand_text")); // this returns nothing
Timber::render('views/index.twig', $context);
```

I don't get any errors. Can you tell me why?

Thanks!

**Comment by jarednova** [comment]
Hi @andricicezar -- can you confirm that the above works when the Timber plugin is disabled? `get_option` is a WordPress function so things should be good. The output you have will come before the page so also do a raw view source to see if it's somewhere before the `<html>` tag

**Comment by andricicezar** [comment]
My bad. I should have used get_theme_mod.
