### ISSUE TITLE
is_main_query() or in_the_loop() and Timber::get_post()

### ISSUE THREAD

**Issue by aaronhipple** [jarednova/timber#575]
So, I may be pushing Timber to (or past) its limits, but just thought I'd put this out here for a lark...

I'm accessing the Timber object from a plugin that creates a custom post type, with a view toward using it to output the markup for the page's 'detail' view as it were. Before Timber, we'd been accomplishing this by hooking `the_content` and modifying the content conditionally, based on is_singular(), is_main_query(), and/or in_the_loop(), so we've tried to retain this logic.

Our filter looks like this:

```php
function display_myposttype_detail($output) {
    if( is_singular('myposttype') && is_main_query() && in_the_loop() ){

        $context = Timber::get_context();
        $post = Timber::get_post();
        $context['post'] = $post;
        
        /* Other logic happens here */

        return Timber::compile( array( 'mposttype.twig' ), $context );
    } else {
        return $output;
    }
}
add_filter( 'the_content', 'display_myposttype_detail', 99999999 );
```

We have another plugin which displays content from another post type in a widget, also engaging `the_content`, and it works beautifully on a non-Timber theme. `in_the_loop()` and `is_main_query()` work nicely. However on a Timber-based theme, that logic breaks down and the filter is triggered for widget. Our single.php reads like so.

```php
$context = Timber::get_context();
$post = Timber::get_post();
$context['post'] = $post;

/* Other logic happens here */

Timber::render( array( 'single-' . $post->ID . '.twig', 'single-' . $post->post_type . '.twig', 'single.twig' ), $context );
```

Using `Timber::get_post()`, we get results like this in both the main query and the secondary query used in the widget.

* `is_singular('myposttype')`: true
* `is_main_query`: true
* `in_the_loop`: false

I've also tried `Timber::query_post()` (per the example from [timber-starter-theme's single.php](https://github.com/Upstatement/timber-starter-theme/blob/master/single.php#L13)). In that case, we get...

* `is_singular('myposttype')`: true
* `is_main_query`: true
* `in_the_loop`: true

Again, for both cases (main query or secondary queries).

So, we'd like to preserve the compatibility here with non-Timber themes if possible (instead of relying on logic in `single.php` to access `single-department.twig` or including our view twig using logic inside `single.twig`). Is there currently a Timber-friendly way to differentiate the main query from a secondary query inside the `the_content` filter?

**Comment by corradomatt** [comment]
I work for a company where we create "posts" from API data (so these aren't really posts in the database). In the past we've used ```the_content``` filter to inject our "views" much the same way you are doing currently.

One thing I wanted to mention about all of this is that we're looking into using Timber for these template views as well and we're playing with "hi-jacking" the post object. Basically, we're injecting our Timber template view inside of the ```post_content``` part of the post object. I don't know how relevant this is to your particular use-case or how helpful it is but I figured I'd share our thought process on this subject. 

*Also, we are just in the testing phase with this setup and I have no idea how well it's going to work in production yet.*

**Comment by jarednova** [comment]
Hey @aaronhipple -- thanks for the Q. Unfortunately though, Timber was designed to operate outside of the notions of whether it was inside of a main query, secondary query, loop, etc. That was always a notion I found frustrating in WP. And well, turns out I wasn't the only one.

In terms of file structure, instead of relying on what's in `single.php` I'll usually extend `TimberPost` for a project like so:

```php

class MyPost extends TimberPost {

    function content() {
        $content = parent::content();
        // do stuff to $content;
        return $content;
    }    
}
```

Not sure if that's helpful in your situation, but hopefully it sets off some bells or lightbulbs. Good luck!

**Comment by aaronhipple** [comment]
@corradomatt & @jarednova -- Much appreciate the input. I do feel like this is a case of trying to understand the 'Timber' way of accomplishing what we want, and your insights are extremely helpful!

**Comment by lmartins** [comment]
I am facing a similar situation, where a I have a page that displays a posts loop inside it and need to differentiate the main post (page in this case) from the loop items (loop). 

I was wondering if anyone found out a more robust solution for this...

Thank you.

**Comment by sirtawast** [comment]
Not related directly but I got a bug fixed in my template which was caused by `in_the_loop()` being interpreted as `false` in a plug-in "Contact Form 7". The form would always list post ID as zero (default value) in a hidden field: 

```<input type="hidden" name="_wpcf7_container_post" value="0">```

Putting this in template

```
$timber_post = Timber::query_post();
$context['post'] = $timber_post;
```

did the trick.

@aaronhipple, thanks for listing out the function return values.
