### ISSUE TITLE
WooCommerce: How to add recent product instead of get all products from teaser site?

### ISSUE THREAD

**Issue by tdserviceco** [jarednova/timber#576]
I was wondering how to collect all recent product from a catergory I made called "new stuff" and want it to be on the front-page.

Is it a easy fix? if so please share? 
I be gladly in your debt haha.

**Comment by jarednova** [comment]
Hi @tdserviceco this is where my knowledge of WooCommerce might fall short, but I'll give it a shot....

```php
$recent_products = Timber::get_posts(array('post_type' => 'product', 'category_name' => 'new-stuff', 'posts_per_page' => 6));
```

Is something like that what you're looking for?

**Comment by tdserviceco** [comment]
Looks like it.. But still i get all 24products (have only 1 recent)

**Comment by tdserviceco** [comment]
But i look a bit more in to it :)

**Comment by jarednova** [comment]
@tdserviceco would a WP_Query [date_query](https://codex.wordpress.org/Class_Reference/WP_Query#Date_Parameters) take care of what you're after?

**Comment by connorjburton** [comment]
Hi @tdserviceco - is this still an issue for you?

**Comment by connorjburton** [comment]
As this seems inactive I am going to close this for now. If it's still an issue please let me know and I will re-open.
