### ISSUE TITLE
Warning: call_user_func_array() expects parameter 1 to be a valid callback,

### ISSUE THREAD

**Issue by daslicht** [jarednova/timber#577]
When I try to add a css style in my functions.php i get this error:

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'load_custom_style' not found or invalid function name in C:\wamp\www\wordpress\wp-includes\plugin.php on line 496

What am I missing please?
```
function load_custom_style() {
		wp_enqueue_style( 'my-style', get_stylesheet_uri() );
 }


function __construct() {
		add_action( 'wp_enqueue_scripts', 'load_custom_style' );
                 ...
```

**Comment by jarednova** [comment]
I notice you're calling `load_custom_style` from inside `__construct` -- does that mean all of this is inside a class? in that case, you'll need to call it like...
```php
add_action( 'wp_enqueue_scripts', array($this, 'load_custom_style' ));
```

**Comment by daslicht** [comment]
ahh , ok thank you !
