### ISSUE TITLE
doc example & single.php

### ISSUE THREAD

**Issue by tgelles** [jarednova/timber#579]
I'm a total newbie to twig, so apologies if this is a stupidly rudimentary question.

But when following the getting started guide, where in single.php do I place:

`$context['all-about-jared'] = Timber::get_post(11);
Timber::render('single-all-about-jared.twig', $context);` 

without both the base.twig and single.twig repeating on my all-about-jared post? 

Screenshot below
![screen shot 2015-06-23 at 3 03 55 pm](https://cloud.githubusercontent.com/assets/5149286/8314703/212923ec-19b9-11e5-8a88-9430c7e7ee54.png)

**Comment by tgelles** [comment]
So I should not be adding that code to single.php, but I'm very confused by the Getting Started Pt.2 docs.

I'm supposed to create a `single-all-about-jared.twig` file in my views folder, but the code in [`single.php`](https://github.com/Upstatement/timber-starter-theme/blob/master/single.php#L20) code only looks for posts with an ID listed (which would mean `single-all-about-jared.twig` should be `single-#.twig`) or the generic `$post->post_type`. There doesn't seem to be anything looking for the post title which is what the docs specify you create.

Is this correct or am I way off?

**Comment by jnweaver** [comment]
You're right. In single.php, you would need to specify your template array as:
```php
Timber::render(array('single-' . $post->ID . '.twig', 'single-' . $post->post_name . '.twig', 'single-' . $post->post_type . '.twig', 'single.twig'), $context);
```

That Getting Started Pt. 2 documentation might be out of date with regard to the current version of the starter theme. For what it's worth, typically, I don't think it's common to have unique Twig views for specific WordPress posts (i.e. single.php); but I do sometimes do so for specific pages (i.e. page.php) and you will see that the starter theme does look for a page-{slug-name}.twig view in its render call within page.php.

**Comment by connorjburton** [comment]
@jnweaver has covered this so going to close this. Feel free to comment @tgelles if this is still an issue for you.
