### ISSUE TITLE
Path filter

### ISSUE THREAD

**Issue by haroldangenent** [jarednova/timber#581]
The path filter is [documented](https://github.com/jarednova/timber/wiki/Filters#path), but it seems to be removed in https://github.com/jarednova/timber/commit/c96391deba3e893c3042a4120ddd76b44680f9a4.

**Comment by jarednova** [comment]
Thanks for the heads-up! I've updated the documentation to reflect the current name:

My custom link: {{ 'http://example.org/2015/08/my-blog-post' | relative }}
