### ISSUE TITLE
ACF options page fields not working

### ISSUE THREAD

**Issue by spentacular** [jarednova/timber#582]
I'm trying to add a few of the fields from the options page to my footer.

Currently, in my `footer.php`:

```php
$context['options'] = get_fields('options');
Timber::render('footer.twig', $context);
```

But when I try to reference anything using the `{{options.[field]}}` syntax, I can't get it to work.

I'm using ACF Pro, and the options page is included now, instead of a separate plugin. Could that be causing the error?

I've also tried referencing via the syntax [here](http://www.advancedcustomfields.com/resources/get-values-from-an-options-page/) (specifically, using 'option' instead of 'option'), but no luck.

Any ideas?

Thanks for the incredible work on this as well!

**Comment by ivanjuras** [comment]
+1, I'd like to know that too for ACF Pro...

**Comment by jarednova** [comment]
Hi @spentacular and @ivanjuras the method you show makes sense to me, I'm about to run a test on my side....

**Comment by ingmeister** [comment]
It's not working for me either, any news yet?

**Comment by anugupta** [comment]
Odd, this seems to be working fine for me:

In my template (`archive-case-study.php`)

    $context['site_options'] = get_fields('options');

    TimberHelper::render( "archive-case-study.twig", $context );


In the view (`archive-case-study.twig`)

        {{ dump(site_options) }}
        <h3>{{ site_options.case_studies_heading }}</h3>

This seems to render correctly

**Comment by ingmeister** [comment]
I'm using ACF 5 Pro,
adding the global fields like this:
```
if( function_exists('acf_add_options_page') ) {
	acf_add_options_page();
	acf_add_options_sub_page('Header');
	acf_add_options_sub_page('Footer');
}
```
and adding this to header.php:
```
$context['header_options'] = get_fields('Header', 'options');
Timber::render('base.twig', $context);
```
Then I have this file header-info.twig which I include in base.twig. I'm getting Null using
```
{{ dump(header_options) }}
{{header_options.header__address}}
```

I'm a Timber/Twig newbie, what am I missing here?

**Comment by anugupta** [comment]
`$context['header_options'] = get_fields('Header', 'options');` won't work as  `get_fields()` only takes a single optional parameter to specify the source of the fields. 

So, you need to do `$context['header_options'] = get_fields('options')`

**Comment by ingmeister** [comment]
Still an empty array... guess I'm doing something wrong elsewhere

**Comment by spentacular** [comment]
I'm with @ingmeister and I still can't get anything. @anugupta I followed everything you did exactly, and my `{{ dump(site_options) }}` just breaks my page.

I've even tried changing it to `the_field`, as shown here: http://www.advancedcustomfields.com/resources/options-page/#template-usage

I think we were getting hung up because it's shown in the wiki to use get_field, here: https://github.com/jarednova/timber/wiki/ACF-Cookbook#options-page

Regardless, no form of options, selecting a specific field, or anything will even get a dump of data on my page. I'm also only adding the options page, not the header or footer:

```php
if(function_exists('acf_add_options_page')) {

	acf_add_options_page();

}
```

**Comment by ingmeister** [comment]
For {{ dump(site_options) }} to work, you need to set "define('WP_DEBUG', false);" located in the wp_config.php file to true. But still no options available on my screen either :)

**Comment by spentacular** [comment]
@ingmeister ahhh, okay. I've just being using `{{ field|print_r }}` for everything!

**Comment by anugupta** [comment]
Ah, yeah, forgot that you need to set `WP_DEBUG` for `dump()` to work!

At this point, you need to work out whether your `get_fields()` call is working and returning the data you're expecting, which isn't a Timber issue. In the PHP template, do a `var_dump` or `print_r`of  your `$context` variable and see if the options data is there.

**Comment by anugupta** [comment]
@spentacular - I've edited my earlier comment to use `Timber::render` instead of my own `TimberHelper::render` wrapper function (which I use to more easily control global caching, so not relevant here). Just wanted to make sure you hadn't copied that line as well.

**Comment by jarednova** [comment]
Hey all! Just to wrap this up, some of the problems I've noticed is (going back to @spentacular's first filing of this) is that the proper way to fetch the option fields from ACF is via `option` not `options` so...
```php
$context['option'] = get_fields('option');
Timber::render('mytemplate.twig', $context);
```

In ACF, let's say you have a field on your ACF options page slugged `welcome_message`, the proper way to access this is:

```twig
<h1> My Website </h1>
<h2> {{ option.welcome_message }} </h2>
```

**Comment by spentacular** [comment]
Hey @jarednova , thanks for your help. I almost had a mess-up again, but I've figured out what was messing up on my end (although I'm still confused). I created a footer-text option on my single options page, and then in my footer.php, added to the bottom:

```twig
<?php
/*
 * Third party plugins that hijack the theme will call wp_footer() to get the footer template.
 * We use this to end our output buffer (started in header.php) and render into the view/page-plugin.twig template.
 */
$timberContext = $GLOBALS['timberContext'];
if ( ! isset( $timberContext ) ) {
	throw new \Exception( 'Timber context not set in footer.' );
}

$context['option'] = get_fields('option');
Timber::render('footer.twig', $context);
```

Which does not let that option render on the page when I do `{{ option.footer_text }}`.

I *can* get the options page to render when I put the `$context` on the page template page, and *then* it renders in the footer. But since I'm only using it for header/footer info, it will only fall on that specific page, not the entire website.

Is there a way to add the content to the `base.twig` layout in order to make it fall to the entire theme?

**Comment by anugupta** [comment]
@jared - ACF treats `option` and 'options` as the same, I think

This is from the ACF file: 'api-helpers.php'

    function acf_get_valid_post_id( $post_id = 0 ) {
	
    ...	
	
	// allow for option == options
	if( $post_id == 'option' ) {
	
		$post_id = 'options';
		
	}

**Comment by jarednova** [comment]
@anugupta -- thanks for that! a nice piece of defensive programming by @elliotcondon.
* * *
To @spentacular's question, if this is going to appear on every page, my recommendation is to put it in `functions.php` in the context filter:
```php
/* functions.php */
add_filter( 'timber_context', 'mytheme_timber_context'  );

function mytheme_timber_context( $context ) {
    $context['option'] = get_fields('option');
}
```

This will now be available to every template (as long as it receives the `Timber::get_context` array) so then on your `base.twig` you could... 

```twig
{# base.twig #}
        <footer><h4>{{option.footer_message}}</h4></footer>
    </body>
</html>
```

**Comment by ingmeister** [comment]
@jarednova - thank you very much, this got the job done!

**Comment by spentacular** [comment]
@jarednova Yep! This worked perfect. Do you want me to add this under options or make a new section on the ACF part of the wiki?

**Comment by jarednova** [comment]
Can you add it to the ACF stuff for now? I need to create a new doc in there for all the hooks as well, so I'll start that doc on my side

**Comment by TaulantSeferi** [comment]
`if( function_exists('acf_add_options_page') ) {
    acf_add_options_page();
    acf_add_options_sub_page('Header');
    acf_add_options_sub_page('Footer');
}`

don't function
 please help me

**Comment by TaulantSeferi** [comment]
don't show menu in wordpress
