### ISSUE TITLE
What is the equivalent in timber for creating columns similar to twig (batch)?

### ISSUE THREAD

**Issue by johnnytrinh** [jarednova/timber#585]
I tried to add the pipe + parameters but my results return nothing.

{%for item in items | batch(2) %}

Following documentation:
http://twig.sensiolabs.org/doc/filters/batch.html

**Comment by jarednova** [comment]
Hi @johnnytrinh it should be exactly what you see there — the Twig library is used directly as opposed to wrapped. Try viewing the contents of items with:
```twig
{{ items | print_r }}
```

**Comment by johnnytrinh** [comment]
Excellent, thank you!
