### ISSUE TITLE
Multisite and image resizing

### ISSUE THREAD

**Issue by haroldangenent** [jarednova/timber#586]
This doesn't seem to work properly. Upon resizing, `TimberImageHelper::_operate` seems to call `TimberImageHelper::is_external` which always return true for subwebsites, since `site_url` and `home_url` are never part of source URL.

For example:
`www.example.com/wp-content/uploads/...` never contains `www.example.com/nl/` (if `/nl/` is the subwebsite).

`network_home_url()` and `network_site_url()` should also be checked. Something like this should work: (but could be DRY-er)

```
protected static function is_external($path) {
		if (is_multisite()) {
			$is_external = TimberURLHelper::is_absolute($path) && !strstr($path, network_site_url());
			if ($is_external) {
				$is_external = TimberURLHelper::is_absolute($path) && !strstr($path, network_home_url());
			}
		} else {
			$is_external = TimberURLHelper::is_absolute($path) && !strstr($path, site_url());
			if ($is_external) {
				$is_external = TimberURLHelper::is_absolute($path) && !strstr($path, home_url());
			}	
		}
		
		return $is_external;
	}
```

**Comment by haroldangenent** [comment]
Not to push you @jarednova, but I'm looking for a way to fix this for now (without using WordPress image sizes). However, I don't think there's a possibility. I don't see any filters and I don't think I can overwrite this class without re-creating the core of it completely (since `_operate` is private).

Do you have any ideas on how to fix this temporarily until this gets fixed in a new release?

**Comment by jarednova** [comment]
It's alright, sometimes I need a push. I should be able to take a look at this later this evening....

**Comment by jarednova** [comment]
@haroldangenent I think this might be fixed by a change between when your comment was posted and now. The current code checks for `content_url()`:

```php
	$is_external = TimberURLHelper::is_absolute( $url ) && !strstr( $url, content_url() );
```

This should satisfy a case where the image is.. `http://example.com/wp-content/2015/08/fake-pic.jpg` and the image were called from a page on `http://example.com/nl`, (`content_url()` returns `http://example.com/wp-content`). As I understand "child" sites share the `wp-content` location with the parent site, is this correct in all instances?

**Comment by haroldangenent** [comment]
@jarednova Thank for looking at this. I can confirm this has been fixed in a later version!

I'm not aware of (and couldn't find) any built in way to specify a `WP_CONTENT_URL` per subwebsite. So checking `content_url()` should be fine for Multisite.
