### ISSUE TITLE
Error after update 0.21.4

### ISSUE THREAD

**Issue by smouki** [jarednova/timber#587]
Hi, I'm getting 

Fatal error: Cannot access private property TimberPost::$_content in /wp-content/plugins/timber-library/lib/timber-core.php on line 61

when trying to get custom post type list in page.php

```php
$args = array(
        'post_type' => 'project'
    );
$context['projects'] = Timber::get_posts($args);
```

Any ideas? Everything worked fine before update.

**Comment by jarednova** [comment]
Thanks @smouki -- looking into it right now

**Comment by jarednova** [comment]
@smouki I wasn't able to re-create the error. That said, I understand exactly the PHP error it's giving you. Can you test the latest `master` (it can be as simple as replacing the `lib` directory for the Git repo with the one that's currently in your `timber-library` directory) and let me know if it resolves the error?

**Comment by smouki** [comment]
@jarednova it looks like it solved the problem.

**Comment by jarednova** [comment]
Awesome! I'm deploying right now to WordPress.org as 0.21.5

**Comment by smouki** [comment]
Thanks!
