### ISSUE TITLE
render() and echo being an arg

### ISSUE THREAD

**Issue by AlchemyUnited** [jarednova/timber#589]
long to short, it would be nice if the echo in the render function was optional. 

that is, echo, else return the string. 

perhaps there's another / other way to get this result? that is, twig friendly string + context returns a string.

**Comment by jarednova** [comment]
@AlchemyUnited you want `Timber::compile` -- same arguments and it will return, rather than echo the string

**Comment by AlchemyUnited** [comment]
@jarednova 

i looked as that i'm pretty sure it in turn uses the render method, and that has an echo. 

i ended up using string_render() (or was it render_string()) within an ob_get_contents().

**Comment by jarednova** [comment]
I might be missing what you're looking to do, I've updated the docs to clarify the distinctions and behaviors of `Timber::render`, `Timber::compile`, `Timber::render_string` and `Timber::compile_string`. Hope this helps!:

https://github.com/jarednova/timber/wiki/Timber-docs

**Comment by AlchemyUnited** [comment]
@jarednova - great i'll have a look. thx.

to clarify, i had two needs

1) template as a string, not a file.

2) not echoing the output, just returning it, and letting me echo it as i see fit.
