### ISSUE TITLE
Is there any way to require Timber in my theme by default?

### ISSUE THREAD

**Issue by ivanjuras** [jarednova/timber#593]
Downloading and installing Timber has become tedious for me. Especially when I click that magical "Activate" button before I actually activate Timber.

You know the drill then: move the theme folder, reactive another theme, install Timber, move my starter theme back to the folder and then activate it.

I tried with TGM-plugin activation plugin, but for some reason it doesn't work for me. Is there a way for us to require Timber before our theme gets activated?

**Comment by KLVTZ** [comment]
@ivanjuras just to verify, did you follow the config from: 

https://github.com/TGMPA/TGM-Plugin-Activation/blob/develop/example.php

and added your own settings/path? Curious to see how this looks.

**Comment by ivanjuras** [comment]
@KLVTZ , yeah, the problem is that the theme always activates first, so I get the dreaded error of "Timber not found..." and the white screen, before the notification even pops up.

**Comment by jarednova** [comment]
@ivanjuras two options I recommend:

1. Put a "loader file" into `mu-plugins`:
```php
/* wp-content/mu-plugins/loader.php */
if (file_exists('../plugins/timber/timber.php') {
    require_once('../plugins/timber/timber.php');
} else if (file_exists('../plugins/timber-library/timber.php') {
    require_once('../plugins/timber-library/timber.php');
} 
```
2. Checkout the top of `functions.php` in [`timber-starter-theme/functions.php`](https://github.com/Upstatement/timber-starter-theme/blob/master/functions.php#L3-L8), there's some code that checks for timber before proceeding with loading the theme

**Comment by ivanjuras** [comment]
@jarednova Thanks, now I remember that I deleted that piece of code when I started working on my own framework.

A quick question: What part of that code actually stops the theme from being activated? It seems to me that it only displays the error message, but I don't know which part of it actually stops it from loading?

**Comment by corradomatt** [comment]
@ivanjuras the TGM class doesn't stop a theme from being loaded. It only requires specific plugins to be installed and activated. If the required plugin is installed, you can "force activation" which basically keeps the plugin active and doesn't allow a user to deactivate it. But if the required plugin is not installed, it will only display an error message on the admin.

I created functionality once that would switch themes if a required plugin was installed and active. But it never quite worked right and I don't recommend it. You have to make certain assumptions about the users setup...like that they have one of the default themes installed still. Plus, setting a theme deactivation hook for when the plugin is not installed is a real PITA.

The best you can do is to package a version of the plugin with your theme and auto-install it when the theme is activated. But again, you'd have to write some custom code for this as it's not supported by TGM. I would just stick with admin and maybe a front-end notice about installing and activating the plugin for the theme to work properly. As far as I know, Timber templates fail gracefully without the plugin installed, is that right @jarednova?

**Comment by connorjburton** [comment]
This is being covered in #835 and discussion is on going there.
