### ISSUE TITLE
How to extend TimberTerm

### ISSUE THREAD

**Issue by budnieswski** [jarednova/timber#594]
Currently its possible to filter inside the TWIG file with term.get_posts
Example:
```php
{% for post in term.get_posts({'numberposts' : 5, 'orderby' : 'title'}) %}
```

I would add filter by category (term.get_cetegories)
Example:
```php
{% for category in term.get_cetegories({'child_of' : 1, 'orderby' : 'title'}) %}
```

How to do this ?

**Comment by jarednova** [comment]
Hi @budnieswski you should extend the `TimberTerm` object by making your own class:

```php
/* MyThemeTerm.php */

class MyThemeTerm extends TimberTerm {
    
    function get_categories( $args ) {
        //do something
        return $category
    }
}
```

You'll use this in your PHP files so that the MyThemeTerm is sent to the `.twig` files:

```php
/* single.php */
$context = Timber::get_context();
$context['term'] = new MyThemeTerm( $term_id); 
Timber::render('single.twig, $context);
```

You can also convert to `MyThemeTerm` on the fly in your twig files via...

```twig
{% set term = TimberTerm(term, 'MyThemeTerm') %}
{% for category in term.get_cetegories({'child_of' : 1, 'orderby' : 'title'}) %}
```

**Comment by dmmarmol** [comment]
Sorry for the N00b question but I'm a little confused with PHP and Timber.

My idea it's to create a `MyPost` class and extend the original `Post` class to add custom methods.
So I created a file called `Post.php` and placed it inside an `extension` dir in a folder structure like this.
```
- templates/ (contains the .twig views)
- extension/
--- Post.php
- functions.php
- index.php
```

### Post.php
```
namespace Timber;

use Timber\Post as TimberPost;

class CQ_Post extends TimberPost {
    public function texts() {
        $texts = ['some random text'];
        if (is_array($texts) && count($texts)) {
            return $texts[0];
        }
    }
}
```

I don't know how to require this file from the `index.php` and then use it on my templtaes to do `{{ post.texts }}` 
Also I don't know if my class definition it's ok.

**Comment by jarednova** [comment]
@dmmarmol your approach is pretty much spot-on. Just include your file in `functions.php`...
```php
# functions.php

require_once('extension/Post.php);
```

To use your class, inside of `single.php` just do something like...

```php
# single.php

$context['post'] = new MY_Post();
```


to the class itself, I have some aesthetic suggests. Namely, not putting it inside the `Timber` namespace as (in theory) this should be reserved for Timber itself

```php

namepsace MyProject;

class Post extends \Timber\Post {

    public function texts() {
        $texts = ['some random text'];
        if (is_array($texts) && count($texts)) {
            return $texts[0];
        }
    }

}
```

good luck!

**Comment by dmmarmol** [comment]
@jarednova Thanks a lot for the quick response and your suggestions! They are highly appreciated.
I did exactly what your suggested but I keep getting this error:
```shell
Class 'Timber\Post' not found in "C:/path/to/my/project/extension/Post.php"
```

### Post.php (updated)
```php
namespace MyProject;

use \Timber\Post as TimberPost;

class Post extends TimberPost {
	public function get_share_count($network) {
		return 'get_share_count from '.$network;
	}
}
```

And when I extend the class with `\Timber\Post` instead of the alias, I get the same error. I *requried_once* the `extension/Post.php` file at the top of my `functions.php`.

**Comment by jarednova** [comment]
hmmm, if I had to guess, it could be a load order issue. Ensure that Timber loading before your `Post.php` file is loaded

**Comment by dmmarmol** [comment]
I manage to fix it by removing the `namespace My Project` and extending it like `class Post extends TimberPost`
