### ISSUE TITLE
Duplicates in category.children

### ISSUE THREAD

**Issue by mvarrieur** [jarednova/timber#595]
I'm getting duplicate categories displaying in `{{category.children}}` in my twig files, I've traced it back to the native `get_term_children()` call in Wordpress. If I wrap the call in `array_unique()` in `lib\timber-term.php` it seems to fix the issue.

I'm unsure if I just have a weird install here or what is going on (it wasn't happening when I originally setup the categories but I haven't really changed the view since then).  I have ~20 or so categories some are nested 3 levels deep, the ones that are getting repeated seem to only be the second level categories (and only 2 out of the 10 or so second level categories are getting duplicated in the view).

I'm glad to submit a pull request if this is a reasonable thing. I tried reaching out in #wordpress on IRC but wasn't able to find out if this was intended behavior for the native function or not. Let me know what you think?

**Comment by mvarrieur** [comment]
Oh and here is the output of my native `get_term_children` call for reference:

````php
print_r(get_term_children(24, 'category'));
 
/////// Output:
Array ( [0] => 25 [1] => 26 [2] => 27 [3] => 27 [4] => 28 [5] => 28 [6] => 63 [7] => 64 [8] => 65 )
````

**Comment by jarednova** [comment]
@mvarrieur my feeling is that this is more of a WordPress issue than a Timber issue. As you note, you're getting the same results with both the TimberTerm method of `children` and `get_term_children`. I've become very reluctant to "fix" underlying WP behavior (especially around terms/taxonomies which WP core folks say is going to get a big-time overhaul soon). Are there other taxonomies in your install?

**Comment by mvarrieur** [comment]
@jarednova Sounds good. I have extended TimberTerm and fixed the problem within my theme.
