### ISSUE TITLE
Undefined index: HTTP_HOST

### ISSUE THREAD

**Issue by maketimetodesign** [jarednova/timber#605]
Hey,

Just been checking my error logs for something else and spotted this Notice:

Undefined index: HTTP_HOST in +++++/httpdocs/wp-content/plugins/timber-library/lib/timber-url-helper.php on line 90

AND 

Undefined index: HTTP_HOST in +++++/httpdocs/wp-content/plugins/timber-library/timber.php on line 228

Has anyone got any idea why this is?

Cheers,
Tom

**Comment by jarednova** [comment]
Tom: is this happening locally or on a server somewhere?

**Comment by maketimetodesign** [comment]
It's happening on a live server.

**Comment by jarednova** [comment]
thanks @maketimetodesign -- looking into it now

**Comment by jarednova** [comment]
So the word is that there are some very interesting distinctions between HTTP_HOST and SERVER_NAME, but they all boil down to the same thing for most setups. #609 has a patch for this ready....

**Comment by maketimetodesign** [comment]
Ah well what do you know! Perfect, thanks for investigating!
