### ISSUE TITLE
Timber integration with Livefyre Comments

### ISSUE THREAD

**Issue by aleksandr-grinevich** [jarednova/timber#606]
I am trying to add Livefyre Comments on my wordpress blog.
https://wordpress.org/plugins/livefyre-comments/

Livefyre plugin adds the filter on comments_template. I try to put the comments into the context for a further use in twig.

context['comments'] = comments_template();

But it immediately outputs the comments at the top of my page. Do you have any idea how to handle it?
Thanks

**Comment by jarednova** [comment]
@aleksandr-grinevich try...

```php
$context['comments'] = TimberHelper::ob_function('comments_template');
```

**OR**

```twig
<div id="my-comments">
    {{ function('comments_template') }}
</div>
```

... this will take the output of `comments_template` and hold it in a buffer so you can control where it gets outputted.

**Comment by aleksandr-grinevich** [comment]
Perfect! Thank you
