### ISSUE TITLE
String Output whenever calling get_context

### ISSUE THREAD

**Issue by asecondwill** [jarednova/timber#608]
On updating Timber this morning, 

string(15) "meta-inline-top"

**Comment by asecondwill** [comment]
The line generating the output is in timber.php, line 232

````
		$data['body_class'] = implode( ' ', get_body_class() );
````

because the function get_body_class  is outputting the text.

**Comment by asecondwill** [comment]
That line hasn't changed in a while.  so i guess something wrong with the site or the wordpress function.

**Comment by jarednova** [comment]
Yeah, looking at the docs:

https://codex.wordpress.org/Function_Reference/get_body_class

... it returns an array with no echo-ing. Maybe a theme or plugin on the site is hooked into it?

**Comment by asecondwill** [comment]
thanks for looking @jarednova  - I realised i didn't need to call get context anyway since i was just setting some posts and rendering a partial. (this is for a site that uses a regular theme and I'm just sprinkling in timber) so I removed it.

i'm pretty sure this isn't timbers fault.  closing.
