### ISSUE TITLE
Template includes

### ISSUE THREAD

**Issue by danielhq** [jarednova/timber#612]
Hey everyone.

I have a question regarding templates.
Lets say i have a index.twig which includes another template "comments.twig"

Does comments.php gets executed, passing data to comments.twig ?
Because if i do a simple, inside comments.php
$context['test] = "test"; 
Timber::render('comments.twig', $context)
and inside comments.twig i do:
{{ test }} 

Nothing shows, How does that work?
Thanks

**Comment by geoffyuen** [comment]
Only the php file that contains the original Timber::render get's executed. The twig files really have no association to any other .php file other than the one that renders it.

**Comment by danielhq** [comment]
I mainly build my themes like this, including "modules" which may be the search-bar or the main-menu.

So Timber won't fit my needs?

**Comment by jnweaver** [comment]
Reading over the [get_sidebar method](https://github.com/jarednova/timber/wiki/Timber-docs#get_sidebar) might be helpful. 

For your original question, if you want to render comments for each post, your include would iterate over `post.comments`. If you're thinking more in terms of your comments.php being the file where you build what you need for your comments form, then the sidebar example might be relevant. (I don't do much with native Wordpress comments so I might be overlooking some nuances I'm unaware of.)

If it's something that will be used on every page of your site (menus, e.g.), then you'll want to consider using the `timber_context` filter to add the data to the context you send to every Twig template you render; see [the menu documentation](https://github.com/jarednova/timber/wiki/TimberMenu) for an example.

At any rate, you can be very modular in your use of Timber.

**Comment by connorjburton** [comment]
Think @jnweaver covered this pretty well so going to close this. Feel free to comment and i'll reopen if it's still an issue for you @danielhq
