### ISSUE TITLE
Image resizing with the "resize()" filter

### ISSUE THREAD

**Issue by ltarasiewicz** [jarednova/timber#614]
Hello,

I noticed that when I apply a `resize()` filter, e.g. `{{ image|resize(500) }}`, the image will be cropped to have the width of 500px, which is fine.

However , if `{{ image }}` is originally smaller than 500px, then it will be stretched to the width of 500px (as specified in the `resize` filter) and pixelated in the process. 

Is there a way to apply the `resize(n)` filter **only if** image width is larger than `n` ?

The objective is to prevent the filter from stretching the image.

**Comment by jarednova** [comment]
Hi @ltarasiewicz -- you can get the `image.width` and `image.height` values and then run a ternary test using those values within the tag, the result looks something like this....

```twig
<img src="{{ image.width > 500 ? image|resize(500) : image }}" />
```

Here's the [Twig documentation](http://twig.sensiolabs.org/doc/templates.html#other-operators) on ternary operators

**Comment by ltarasiewicz** [comment]
This is great, thanks so much.
