### ISSUE TITLE
TimberPost lost post_format

### ISSUE THREAD

**Issue by DreapsCo** [jarednova/timber#617]
post_format is not in TimberPost .
This variable should be in the TimberPost.
in the wordpress can see this with this function
get_post_format

**Comment by jarednova** [comment]
Thanks @DreapsCo! I'm looking into this right now

**Comment by jarednova** [comment]
Hi @DreapsCo, you can access a post's format via...
```twig
My format is: {{ post.format }}
```

The reason that it's not available under `post_format` is that the `TimberPost` object is an extension of `WP_Post` which contains some properties (like `post_title`, `post_content`)

**Comment by jarednova** [comment]
I've added a test in b50eb12eef2bf606eb4849f2d639a16bc4e866b8 to verify
