### ISSUE TITLE
What's the best way to convert a custom query to a Timber object?

### ISSUE THREAD

**Issue by lmartins** [jarednova/timber#618]
Im using the Event Organiser plugin which as a custom method to retrieve posts. It is a wrapper to  `get_posts` but it adds a few features specific to dealing with events.

What would be the best approach to avoid reinventing these queries while still using the awesomeness of Timber. Can I convert the result object to a Timber posts object?

The documentation for this custom method can be found here:
http://codex.wp-event-organiser.com/function-eo_get_events.html

**Comment by herrbischoff** [comment]
You will basically have to write all that logic in the PHP template file and just output the results into a Timber post object.

```
$events = eo_get_events(array(
    'numberposts'=>5,
    'event_start_after'=>'today',
    'showpastevents'=>true,//Will be deprecated, but set it to true to play it safe.
));

$data = Timber::get_context();
$data['events'] = Timber::get_posts($events);
$data['post'] = new TimberPost();

Timber::render('events.twig', $data);
```

What you should get is post object `{{ events }}` containing all results.

Then, you will probably have to write a custom filter to further process the results. The basic process is explained here: https://github.com/jarednova/timber/wiki/Extending-Timber#adding-to-twig

I believe the most attainable goal here is to create a filter (for example called `get_eventlist_item`) that does the work of creating a single list item.

```
add_filter('get_twig', 'add_to_twig');

function add_to_twig($twig) {
    /* this is where you can add your own fuctions to twig */
    $twig->addExtension(new Twig_Extension_StringLoader());
    $twig->addFilter('get_eventlist_item', new Twig_Filter_Function('my_eventlist'));
    return $twig;
}

function my_eventlist($event) {
        $format = ( eo_is_all_day($event->ID) ? get_option('date_format') : get_option('date_format').' '.get_option('time_format') );
        $result = '<li><a href="'.get_permalink($event->ID).'"> '.get_the_title($event->ID).' </a> on '.eo_get_the_start($format, $event->ID,null,$event->occurrence_id).' </li>';
    return $result;
}
```

Then you can iterate through them in the view like this:

```
{% if events != '' %}
<ul>
    {% for event in events %}
    {{ event | get_eventlist_item }}
    {% endfor %}
</ul>
{% endif %}
```

As this event beast seems to implement quite a lot of its own user-side functions, this may not be worth all the trouble though.

Please note that I did wrote this up in about 10 minutes in a browser windows, so there will probably be problems I didn't think of. But maybe this helps pointing you into the right direction.

**Comment by lmartins** [comment]
Thank you @herrbischoff it does give some ideias, as I've been struggling to get this to work, more than with WooCommerce.
I'll try your suggestions and report back here if it does work.

Thanks again!

**Comment by lmartins** [comment]
Ok, I am to the point where I have it almost working but facing the same issue I had with WooCommerce, that is all the posts run their functions as if they were the first post in the loop.

To get around this, for WooCommerce, @jarednova suggested adding a helper function:
```php
function timber_set_product( $post ) {
    global $product;
    if ( is_woocommerce() || is_search() || is_front_page() ) {
        $product = wc_get_product($post->ID);
    }
}
```
Which is triggered in the `tease-product.twig` template:
``` {{ fn('timber_set_product', post)}} ```

I've tried a similar approach in this case but no luck. 

Will try the filters approach, although that kinda defeats the advantage of having twig templates for manipulating things around. Hoping there's a similar approach to what was possible with WooCommerce here too.

**Comment by lmartins** [comment]
Ok, actually I had a small typo and the helper function as suggested for WooCommerce does work here too:

```php
function timber_set_post( $current_post ) {
    global $post;
    $post = get_post($current_post->ID);
}
```

This allows me to run the plugin's functions inside twig templates with the right context.
Thanks again for your help @herrbischoff
