### ISSUE TITLE
{{ site.url }} does not work when manually defining WP_HOME and WP_SITEURL

### ISSUE THREAD

**Issue by herrbischoff** [jarednova/timber#619]
While hunting for this very annoying oddity, I found out that as long as I am manually defining `WP_HOME` and `WP_SITEURL` within `wp-config.php` as follows, `{{ site.url }}` and other related tags like `{{ theme.parent.link }}`, `{{ theme.link }}`, `{{ theme.parent.path }}` and `{{ theme.path }}` do not work, outputting nothing.

```
define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] . '/wp');
```

As soon as I declare those within the database, and comment those defines, it starts working as expected again.

I was hoping to circumvent WordPress' rather braindead behavior of being tied to a domain name to make updating between a local dev environment and a staging server more seamless.

**Comment by jnweaver** [comment]
FWIW, I use those exact same definitions in my wp-config.php without any issues in Timber.

**Comment by herrbischoff** [comment]
@jnweaver: Maybe I'm overlooking something incredibly stupid here. Can you think of other reasons that could interfere with those tags/functions?

**Comment by jnweaver** [comment]
Not really.

What does `{{ http_host }}` return for you in one of your twig views when defining those constants in wp-config?

Also, what does `get_bloginfo( 'url' )` return?

**Comment by ivanjuras** [comment]
@jarednova , is this really the prefered behavior?

**Comment by PauGNU** [comment]
Hi,

I confirm this bug.

After setting a custom theme directory using the function:
    register_theme_directory(ABSPATH . '../themes');

The variable {{ theme.path }} doesn't return the correct value anymore. I had to define my own variable in the functions.php file to set it correctly.

**Comment by xavivars** [comment]
I've added a pull request that may partially fix this (at least, @PauGNU's issue).

According to WordPress documentation, path-related constants shouldn't be used by plugin/themes, and it seems the issue was because Timber was assuming the themes folder would always be inside WP_CONTENT_DIR.

By using methods instead of the constants, `{{theme.path}}` returns the right  value

**Comment by destefanis** [comment]
I'm also encountering this bug when developing locally using a VM. Posts and pages won't appear styled as the path appears as ```<link rel="stylesheet" href="/style.css" type="text/css" media="screen">```

**Comment by herrbischoff** [comment]
@jarednova: Any update on this?

**Comment by xavivars** [comment]
@herrbischoff: the pull request got merged, and we don't have problems anymore with our use cases. What is exactly the problem you have?

**Comment by herrbischoff** [comment]
@xavivars: Thanks for notifying me. I somehow overlooked this completely until I browsed through my issues just now. I'm going to check this again when I'm starting my next project, which should be sometime next week.

**Comment by herrbischoff** [comment]
Since I have mostly dropped WordPress as a development platform for the time being, this is currently not relevant to me any more. Closing.
