### ISSUE TITLE
excerpt filter and get_preview: spacing inconsisitencies

### ISSUE THREAD

**Issue by geoffyuen** [jarednova/timber#624]
When using the excerpt filter the output is the content and then "..." with no space between. 

    Lorem ipsum dolor sit amet...

When using .get_preview() it outputs the content, then a space, then '...' another space and then the 'read more' link. 

    Lorem ipsum dolor sit amet ... Read More

It would be nice to be able to replace the ellipsis with a string as well.

**Comment by Gaffen** [comment]
+1

**Comment by connorjburton** [comment]
See above PR

Added a new 5th parameter to `get_preview` to allow an ellipsis substitute, it also fixed the inconsistency.

Hopefully will get pushed out with next Timber WP release
