### ISSUE TITLE
Performance related questions about query_posts/pagination and ACF get_field. 

### ISSUE THREAD

**Issue by christianmagill** [jarednova/timber#625]
Just getting started on Timber and as I read through the documentation I have a few questions.

When you use query_posts to alter pagination, does this requery the database an additional time in addition to get_posts()? 

Also, I could be wrong, but I believe the example "pre_get_posts" action in the documentation needs a conditional restricting it to altering the "home" query as indicated.

Additionally, if I wanted to use ACF's get_fields instead of querying each field separately, is there an easy way to do this, or would I be looking at setting up a separate class for each post type and a separate property for field, following the Extending Objects documentation? 

Would it be possible to making create something like AcfPost which houses the returned array in an "acf" property, and then access via {{ post.acf.field_name }}?

Another possible minor documentation correction: for the first Extending Objects example, I assume that {{ post.issue.title }} uses the return of the function issue(). If this is the case {{ post.issue.name }} should be used as a term object is returned.

Thanks!

**Comment by christianmagill** [comment]
I got the AcfPost class working using

    class AcfPost extends TimberPost {
    
        var $_acf;
    
        public function acf(){
            if(!$this->_acf){
                $this->_acf = get_fields($this->ID);
            }
            return $this->_acf;
        }
    
    }

Fields can be access in twig templates via {{ post.acf.field_name }}

**Comment by connorjburton** [comment]
Going to close this as you seem to have solved it, feel free to comment if it's still an issue and ill re-open.
