### ISSUE TITLE
Extend image manipulation

### ISSUE THREAD

**Issue by pboisclair** [jarednova/timber#629]
Hi,

I'm trying to find infos to add some new manipulation functions (flip, rotate). I have read the text about Timber Extend but I did not figure out how to had a new filter image in Twig. My flip and rotate function are working (I've put directly in the Timber folder (with call in different files) and is working. But when I make an update of Timber all my change was lost.

Anybody can help me.

Thanks

**Comment by jarednova** [comment]
@pboisclair those sound really exciting. I'd love to include them as a part of [Timber Sugar](https://github.com/Upstatement/timber-sugar)

Checkout [this article](https://github.com/jarednova/timber/wiki/Extending-Timber#adding-to-twig) about adding functions to Twig. You can add these directly into your functions.php file. If you're having trouble with that, please post your PHP code

**Comment by pboisclair** [comment]
Thanks. I've found the solution, my brain was bit scrambled yesterday. 
I finish comment my code and I will send you. 

I'm not familiar with Github, how I can send you the code?

Bravo for Timber plugin, very great product

**Comment by jarednova** [comment]
It's probably longer than I can describe here. Check out this article from GitHub Guides:

https://guides.github.com/activities/contributing-to-open-source/

... and read the "Pull Requests" section

**Comment by pboisclair** [comment]
Thanks

> Jared Novack <mailto:notifications@github.com>
> July 29, 2015 at 4:37 PM
>
> It's probably longer than I can describe here. Check out this article 
> from GitHub Guides:
>
> https://guides.github.com/activities/contributing-to-open-source/
>
> ... and read the "Pull Requests" section
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jarednova/timber/issues/629#issuecomment-126088224>.
>

-- 
------------------------------------------------------------------------

*Patrick Boisclair*
Conseiller

patrickboisclair.com | Solutions numériques
Tél. : 450.813.1594
Mobile : 514.814.1312 [urgence]
Fax : 438.968.3230

**Comment by pboisclair** [comment]
Hi,
I have a little problem with my plugin, when the WP debug mode was enabled, I've got this error:
<img src="<br />
<b>Strict Standards</b>:  call_user_func_array() expects parameter 1 to be a valid callback, non-static method CsscoImageHelper::flip() should not be called statically in <b>/home/xxxxxx/public_html/vitreart2/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Environment.php(332) : eval()'d code</b> on line <b>83</b><br />
http://vitreart2.codesourcestudio.co/wp-content/uploads//661_A_g@2-flip-h.png"

Do you have an idea why I have this error?

Thanks

**Comment by connorjburton** [comment]
I think the best bet would be to follow what the guys at mind.ch are doing over at https://github.com/MINDKomm/Timmy for extended image manipulation
