### ISSUE TITLE
Site very slow

### ISSUE THREAD

**Issue by icomarto** [jarednova/timber#630]
Hello,
I created my site with timber plugin and timber-starter-theme. Everything is ok, but my site is very slow. I use twig cache, but site still slow.

- php version https://nw.fantasticservices.com/
- latest wp version
- timber version is Version 0.21.0
- site fantasticservices.com

Thank you :)

**Comment by ivanjuras** [comment]
@icomarto can you install plugin performance profiler plugin and check if there's a plugin that's causing  lag?

**Comment by icomarto** [comment]
WordPress Plugin Profile Report
===========================================
Report date: 29th July 2015
Theme name: Fantastic Services Master
Pages browsed: 16
Avg. load time: 7.3759 sec
Number of plugins: 21
Plugin impact: 72.53% of load time
Avg. plugin time: 5.3497 sec
Avg. core time: 0.7839 sec
Avg. theme time: 0.2719 sec
Avg. mem usage: 139.17 MB
Avg. ticks: 166,829
Avg. db queries : 298.62
Margin of error : 0.9704 sec

Plugin list:
===========================================
P3 (Plugin Performance Profiler) - 0.2813 sec - 5.26%
Gravity Forms - 0.2143 sec - 4.01%
Advanced Custom Fields: Flexible Content Field - 0.0052 sec - 0.10%
Advanced Custom Fields: Options Page - 0.0039 sec - 0.07%
Advanced Custom Fields: Repeater Field - 0.2571 sec - 4.81%
Advanced Custom Fields - 3.1530 sec - 58.94%
Breadcrumb Trail - 0.0105 sec - 0.20%
Better WordPress Minify - 0.0766 sec - 1.43%
Filter by parent in admin - 0.0002 sec - 0.00%
Gravity Forms Multiple Form Instances - 0.0001 sec - 0.00%
Gravity Forms No Captcha Recaptcha - 0.0106 sec - 0.20%
Gravity Forms + Stripe - 0.0268 sec - 0.50%
Mce Table Buttons - 0.0003 sec - 0.00%
Members - 0.0232 sec - 0.43%
Ultimate Nofollow - 0.0027 sec - 0.05%
Redirection - 0.0254 sec - 0.48%
Shareaholic | share buttons, analytics, related content - 0.0415 sec - 0.78%
Timber - 0.7938 sec - 14.84%
Wordpress Seo - 0.3431 sec - 6.41%
WP Migrate DB - 0.0174 sec - 0.33%
Yith Infinite Scrolling - 0.0624 sec - 1.17%

**Comment by icomarto** [comment]
Advanced Custom Fields - 3.1530 sec - 58.94%
Timber - 0.7938 sec - 14.84%

May be problem in Advanced Custom Fields
