### ISSUE TITLE
No Timber Default Template?

### ISSUE THREAD

**Issue by JustSteveKing** [jarednova/timber#636]
I installed the plugin (tried both way) but there is no theme installed? I am trying to guess/figure out the best way to use this atm.

Is the theme not included anymore??

**Comment by corygibbons** [comment]
@JustSteveKing You can download the Timber starter theme here: [Upstatement/timber-starter-theme](https://github.com/upstatement/timber-starter-theme)

**Comment by JustSteveKing** [comment]
That is perfect thank you @corygibbons ! Will have a look through and see what I can do!
Does the plugin come with the built in caching that comes with TWIG?

**Comment by corygibbons** [comment]
@JustSteveKing The [caching](https://github.com/jarednova/timber/wiki/Performance) page in the wiki has a good rundown of what's available.
