### ISSUE TITLE
Can't Activate Plugin

### ISSUE THREAD

**Issue by andydlin** [jarednova/timber#637]
Hello,

I'm building a Wordpress website for a friend and I've created the a new theme using Timber and installed the Timber plugin on my local Wordpress website. It works fine on my local computer but I can't activate the plugin on her server. She says she's on PHP5 and Wordpress v4.2.4.

Here's the error I get when trying to activate the Timber Plugin:
http://puu.sh/jvV6y/b27f5fb82b.png

Any help would be great, thanks!

**Comment by corygibbons** [comment]
@andydlin Looks like her PHP version is too old. I had a similar issue when running 5.2 because the `__DIR__` constant is only available in 5.3+

**Comment by andydlin** [comment]
@corygibbons ohhh, alright I'll tell her to update her PHP and see if that works. Thanks for the quick response!

**Comment by connorjburton** [comment]
Hi @andydlin, is this still an issue for you? Thanks

**Comment by connorjburton** [comment]
As this seems to be inactive and it's been answered I'm going to close this.

Let me know if it's still an issue and I will re-open.
