### ISSUE TITLE
Timber::get_pagination() always returns next link when 0 posts found

### ISSUE THREAD

**Issue by sdunham** [jarednova/timber#639]
The ```get_pagination``` function calculates the total number of pages using this code:

```PHP
$args['total'] = ceil( $wp_query->found_posts / $wp_query->query_vars['posts_per_page'] );
```

If ```$wp_query->found_posts``` is 0, this will result in ```$args['total']``` being 0 as well.

Later in the function, ```$args['total']``` is passed to ```get_next_posts_page_link``` to get the next link. Looking at the ```get_next_posts_page_link``` function, it looks like passing in 0 will result in a next link always being generated because this block of code will always run (```$max_page``` is ```$args['total']``` in this case):

```PHP
if ( !$max_page || $max_page >= $nextpage )
			return get_pagenum_link($nextpage);
```

I'm assuming you'd want a check in ```get_pagination``` to set ```$args['total']``` to 1 if the above calculation results in 0, but I wanted to check in with an issue first since I'm not sure if this would have an unintended consequences elsewhere.

**Comment by sdunham** [comment]
Just checking in about this. I can submit a pull request if that would be more useful.

**Comment by jarednova** [comment]
Hi @sdunham, a long delayed update from us. @connorjburton submitted a PR to resolve this that I just merged. Thanks for your bug report and please checkout `master` to confirm that it solves your issue
