### ISSUE TITLE
Using the & character in a title

### ISSUE THREAD

**Issue by shackep** [jarednova/timber#640]
When using & in a WP post title I get the warning: Notice: Uninitialized string offset: 0 in /.../.../wp-content/themes/themename/templates/educational-transformation.php on line 32
and this notice:
NOTICE: wp-content/themes/FoundationPress/templates/educational-transformation.php:32 - Uninitialized string offset: 0
require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/themename/templates/educational-transformation.php')

**Comment by shackep** [comment]
I am using the standard <h1 class="article-h1">{{post.post_title}}</h1>. The notice appears on the page as soon as I publish a title with '&' in it.

**Comment by shackep** [comment]
I have tried {{post.post_title | e}} to try and escape the & sign, but still had issues.

**Comment by jarednova** [comment]
Try doing `{{ post.title }}` -- that should apply the correct formatting

**Comment by shackep** [comment]
Still the same, unless it is holding on to the error in cache. What is the simplest way to clear twig cache?

**Comment by jarednova** [comment]
@shackep I've verified that `{{ post.title }}` is giving the correct data back, even when an ampersand is present. Can you take a look at what's around line 32 of `wp-content/themes/FoundationPress/templates/educational-transformation.php` and post it here?

**Comment by shackep** [comment]
Here is what i have on 30-34:
`$context = Timber::get_context();
$context['posts'] = Timber::get_posts(165);
$person = $context['posts'][0]->page_person_reference[0];
$context['person'] = Timber::get_posts((int)$person);
$templates = array( 'views/educational-transformation.twig' );`

**Comment by jarednova** [comment]
Great thanks @shackep -- from what I can tell this is about a lack of sanity checks on this line (32):

```php
$person = $context['posts'][0]->page_person_reference[0];
```

I would recommend adding checks to catch for when there are empty items...
```php
if ( isset($context['posts'][0]) && isset($context['posts'][0]->page_person_reference[0]) ) {
    $person = $context['posts'][0]->page_person_reference[0];
}

**Comment by shackep** [comment]
Thanks Jared. I'll be sure and do that.
