### ISSUE TITLE
ACF repeater field nesting

### ISSUE THREAD

**Issue by jscontrust** [jarednova/timber#650]
I have a complex structure build with ACF Pro, and it can not be accessed easily in Timber template:

My Structure

    Post Types: Devices, Modules, Measurement values

Devices has a repeater field, so you can add X modules with one more parameter "Order"

    Device A
        Module: Module A, Order: 2
        Module: Module D, Order: 1
        Module: Module F, Order: 4

Modules has X measurement values with a range

    Module A
        Measurement value: voltage, min: 1, max: 5
        Measurement value: current, min: 0.2, max: 3

When I now get a device with Timbers get_post or get_posts function, it would be great to have the module as TimberPost object.

    {% for device in devices %}

        {% for module in device.get_field('modules') %}
            {{ module.module.measurement_inputs }} {# Value is string with count of inputs #}
            {{ module.module.get_field("measurement_inputs") }} {# Is empty #}
        {% endfor %}

    {% endfor %}

**Comment by jnweaver** [comment]
You should look at the documentation for [Extending Timber](https://github.com/jarednova/timber/wiki/Extending-Timber). 

You can extend the TimberPost class and add methods such that you could reference something like `device.modules` in your view. That would return an array of modules as TimberPost objects (your Device->modules method would call Timber::get_posts, passing the appropriate arguments as saved in your ACF field on the device post.) You can then iterate over each module in Twig.

In your PHP Wordpress template file, you can you use the [second argument](https://github.com/jarednova/timber/wiki/Timber-docs#timberget_postsquery--false-class--timberpost) on *Timber::get_posts* to return your objects as your subclass, e.g. if your subclass was named *Device*:

```php
$devices = Timber::get_posts(array('post_type' => 'device'), 'Device');
```

**Comment by connorjburton** [comment]
I think @jnweaver covered this pretty well, feel free to comment if it's still an issue for you @jscontrust
