### ISSUE TITLE
WordPress 4.3 and ACF Pro 5.3.0  are returning 0 as value

### ISSUE THREAD

**Issue by rpkoller** [jarednova/timber#651]
I am a new Timber user. At first i thought the misbehaviour was due to my faulty application but meanwhile i am uncertain. Anyhow somehow Timber is returning 0 as a return value even if the ```$context``` variable is filled correctly with values. 

The setup. I am running WordPress with MAMP locally. I've changed PHP from version 5.6.10 to 5.5.26. WordPress is version 4.3 and ACF Pro version 5.3.0. Now i've tried to port an existing site over to Timber. At first i've installed the version via composer. Since nothing behaved as expected i've removed it and installed version 0.21.8 from wordpress.org. Those are my base settings. 

Now i've taken an existing page and tried to get running the main content area. wp_header and wp_footer should be taken care of in the next step, i just wanted to see if two basic functionalities work. But as already noted above they don't and honestly speaking i am uncertain why :/ . 

The used PHP code is the following ( in the root of the template folder)

```php
<?php
$context = Timber::get_context();
$context['op-headline'] = 'Hinweis';
$context['op-body'] = get_field('op-info-general', 'option');
print_r($context);
timber::render( 'sk-info.twig', $context );
```
the according twig file inside the templates views folder looks that way: 

```twig
{# sk-info.twig #}
<main id="infol" class="acknowledgement" role="main">
  <div class="container">
    <h2 class="lat-ubn acknowledgement__mainhead">{{op-headline}}</h2>
    {{op-body}}
  </div>
</main>
```

Problem is if i take a look at the print_r output the get_context was properly passed to ```$context```as well as the "Hinweis" string as well as the ACF Pro options field. But the rendering of ```{{op-headline}}``` and ```{{op-body}}``` is only returning ```0```and ```0``` none of the existing and available values is displayed. Am I am using the wrong variable inside the twig template? Or is there a more general bug related issue? Best regards Ralf

**Comment by rpkoller** [comment]
If i add ```{{dump()}}```to the twig template also the array is shown properly like with print_r in the php file. But the display isn't working. But at least ```op-headline``` is definitely the correct call and should return ```Hinweis```. I am confused a bit.

**Comment by jnweaver** [comment]
Because Twig compiles into PHP, the dashes (hyphens) in your context keys (e.g. op-headline) are being treated as minus operators and thus failing. You could rename your ACF fields to use underscores instead (but, careful, you'll lose references to data you have already input if you do this).

You could also wrap those problematic keys in a proper key in your PHP template:

```
$context['options'][''op-headline'] = "Hinweis";
$context['options'][''op-body'] =get_field('op-info-general', 'option');
```

Then you can reference these in your view using Twig's *attribute* method:

```
{{ attribute(options,'op-headline') }}
{{ attribute(options,'op-body') }}
```

But if you can rename the ACFfields, that would of course be cleaner.

**Comment by rpkoller** [comment]
ahhhhhhhhh thanks a lot!!! Now things finally work properly. And is there really the necessity of renaming the acf fields in existing projects? Ok i haven't known that bit and will avoid it in the future to use ```-``` as separators in acf field names. but it worked for me just to rename the key: 

```php
$context['opbody'] =get_field('op-info-general', 'option');
```
and then call it in twig by 

```twig
{{opbody}}
```
for the most basic working version. but i will take a closer look also at the suggested attribute method of yours. thanks a lot for the heads up. i think i could have gone on for another few hours or even days trying to figure out the root of the problem. cheers r.

**Comment by jarednova** [comment]
@rpkoller another method that will work (so you don't have to manually rename or translate all your fields) is....

```twig
{{ post.get_field('op-info-general') }}
```

This will circumvent the Twig limitations that @jnweaver mentioned (btw, thanks for jumping-in @jnweaver!)

**Comment by Yago** [comment]
@jarednova It doesn't work for me.

But I do something like : 

```php
$context['acf'] = get_fields();
```

```twig
<h1>{{ acf.intro_title }}</h1>
```

**Comment by rpkoller** [comment]
@jarednova ah good to know as a workaround as well. thanks. but meanwhile i've renamed all fields in my pet project and never will forget not to use - in fieldnames ;)))) 

@Yago if you wanna load all option fields in your example then you have to use `get_fields('options');` instead of `get_fields()'. With 'get_fields('options')' timber is loading every single option field into that array and you are able to call them like you did in your second line of code.
