### ISSUE TITLE
How to Include a Search Function

### ISSUE THREAD

**Issue by JakeHenshall** [jarednova/timber#653]
Hi,

Love this plugin so much, only been using it for a few days and its pretty easy to understand and get things working.

The only thing I don't really get is how to create a search function that i can add into my header and display a search icon with it.

I'm also trying get a search results page.

Thanks Jake.

**Comment by jarednova** [comment]
@JakeHenshall check out the `search.php` file in the [Timber Starter Theme](https://github.com/Upstatement/timber-starter-theme) that should give you what you're looking for. You can also use WP_Query's [s=](https://codex.wordpress.org/Class_Reference/WP_Query#Search_Parameter) parameter inside of `Timber::get_posts`

**Comment by JakeHenshall** [comment]
@jarednova Would i need to search a search.twig file to create my search function as there isnt a .twig file present.

**Comment by jarednova** [comment]
@JakeHenshall You can, but don't need to. What I recommend is to extend `archive.twig` or `index.twig` into `search.twig` and then add the necessary search input at the top so people can easily run a new search from that page

**Comment by nanotime** [comment]
Well i have the same question, ofcourse i readed the search.php in the starter theme but have a lot of questions yet. First of all, reading some things about... first of all: how should be the form? I have something like this:

```twig
                <div id="search">
                    <form class="navbar-form navbar-left" role="search" action="{{site.url}}">
                        <div class="form-group">
                          <input type="text" class="form-control" placeholder="Search">
                        </div>
                        <input type="submit" value="Search" class="btn" />
                      </form>
                </div>
```

And a stupidly simple `search.twig` (because i have some archive files and a normal archive.twig), like this:

```twig
{% extends 'base.twig' %}

{% block content %}
    <div class="container-fluid">
        {% for post in posts %}
            <h4>{{post.title}}</h4>
        {% endfor %}
    </div>
{% endblock %}
```

Example codes that i see be like:

```html
<form method="get" id="searchform" action="<?php bloginfo('home'); ?>/">
    <div>
        <input type="text" size="18" value="<?php echo wp_specialchars($s, 1); ?>" name="s" id="s" />
        <input type="submit" id="searchsubmit" value="Search" class="btn" />
    </div>
</form>
```

I just want some thing: write a query and display the titles of the results.

I'm pretty noob yet with wordpress, a lot of things are hard for me and some google searches don't give me nothing interesting.

**Comment by connorjburton** [comment]
Hi @nanotime, did you figure this out? Thanks

**Comment by connorjburton** [comment]
Hi,

As this doesn't seem to be active I'm going to close this for you.

If it's still an issue then let me know and I will re-open thanks.

**Comment by nanotime** [comment]
Oh, sorry... no i resolve this, thanks!

**Comment by dottodot** [comment]
Just in case anyone needs the answer

```
<form role="search" method="get" id="searchform" class="searchform" action="{{ site.link }}">
      <input type="text" value="{{ function('get_search_query') }}" name="s" id="s" />
      <input type="submit" id="searchsubmit" value="Search" />
 </form>
```

**Comment by verma-s3** [comment]
Hi, I have used the code into my base.twig file to  show the Search form: 
```
<form role="search" method="get" id="searchform" class="searchform" action="{{ site.link }}">
      <input type="text" value="{{ function('get_search_query') }}" name="s" id="s" />
      <input type="submit" id="searchsubmit" value="Search" />
 </form>
```
but I want whenever I search something it should got to woocommerce shop page, so what I need to change inside search.twig file?
