### ISSUE TITLE
Menu wordpress target="_blank"

### ISSUE THREAD

**Issue by sparrox** [jarednova/timber#655]
I don't want to debate if it's good or bad to use this attribute :) 

I need a target="_blank" to one item of a menu. 

I checked the checkbox in the configuration to enable it on the item. But I have the feeling that there is no target in the Timber's context.

**Comment by sparrox** [comment]
Ok I'm sorry I just found it

**Comment by DaanRuiter** [comment]
I'm having the same issue, how did you access the value for the page target?

**Comment by jarednova** [comment]
@DaanRuiter this is something that's re-written for 2.x. In the meantime you can use:

```twig
<a href="{{ item.link }}" target="{{ item.meta( '_menu_item_target' ) ? item.meta( '_menu_item_target' ) : '_self' }}">
```

... which is a bit verbose, but is compatible for both 1.x and 2.x
