### ISSUE TITLE
Add comments in a single post

### ISSUE THREAD

**Issue by nanotime** [jarednova/timber#661]
Oh, well another noob question that i cant resolve...

In the normal wordpress theme you only need to add `<?php comments_template(); >` to your single file and the form will inserted in your template, here i know that TimberPost have a object/function to take the posts.comments (number, content, etc), but exactly how to activate the comments form evades me.

I tried: `{{fcuntion('comments_template()')}}` ... `{{comments_template()}}` in the single-post_type.twig and `$context['comments'] = comments_template()` in single.php + `{{comments}}` aaand nothing happens.

Any idea or hint? I tried all what came to my mind.

**Comment by bigmike7801** [comment]
FYI, you misspelled "function" as "fcuntion" in your example above.

**Comment by bigmike7801** [comment]
Also, did you try:

`{% function('comments_template') %}`

**Comment by connorjburton** [comment]
Hi @nanotime, is this still an issue for you? Thanks

**Comment by nanotime** [comment]
Hi, @connorjburton right now nope, there are a new helper to get the comment form so, it's solved for me... Anyway, i forgot this posts, sorry, you can close it if you want.

Thanks for the interest :heart:
