### ISSUE TITLE
Is it possible to use blocks in the html-header.twig file? 

### ISSUE THREAD

**Issue by rpkoller** [jarednova/timber#663]
Hi i try to adapt my thinking to the twig approach and drop some possibly unnecessary PHP logic while converting an existing theme. One thing I still stumble across. For "normal" pages you are able to alter blocks used in the `base.twig` view. For a page you extend the `base.twig` file and then you are able to exchange its blocks. That is all fine and good.
But i wonder if it would be possible to exchange blocks for the `html-header.twig` somehow which is basically included into the `base.twig file`? So that you are e.g. able to add into the html tag on the front page a class of `start` and on another page exchange it with a class of `foo` and so on.
Somehow the `html-header.twig` file seems a bit unreachable for block exchange action? Best regards r.

**Comment by rpkoller** [comment]
Ok i was able to work around by dropping the `html-header.twig` and adding its content to the `base.twig` file. That way i was able to use blocks also for the header parts. But i am still curious if it would be basically possible to use block also if the `html-header.twig` file is included into the `base.twig` file.

**Comment by bigmike7801** [comment]
Yes. You should be able to use blocks in any twig file.

**Comment by connorjburton** [comment]
This seems to be solved, let me know if there's anything else related to this.
