### ISSUE TITLE
Is  there a Timber equivalent for home_url()?

### ISSUE THREAD

**Issue by rpkoller** [jarednova/timber#664]
I've searched through the get_context dump. But somehow i am unable to find an equivalent for WordPress home_url. Isn't there any? To bypass that problem i've just used `fn('home_url')`. But wouldn't it make sense to offer a native Timber equivalent? Best regards r.

**Comment by bigmike7801** [comment]
Is this what you're looking for?

`{{ site.url }}`

**Comment by rpkoller** [comment]
thats odd. i saw that one and tried it before but a wrong output was returned. i've retried it now and things look as expected. strange. so i think i could close this issue. thanks for reminding me and let me retry.
