### ISSUE TITLE
Using include_once with fn() results in call_user_func_array() warning

### ISSUE THREAD

**Issue by rpkoller** [jarednova/timber#665]
Inside my `base.twig`file i try to use the function `{{ fn( 'include_once', 'img/foo.svg' ) }}`which results in the following error message and a no show of the svg: 

```
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'include_once' not found or invalid function name in /Applications/MAMP/htdocs/twigtest/wp-content/plugins/timber-library/lib/timber-twig.php on line 216
```

If I define the following in the `front-page.php` file instead:   
```
$context['SVGsnippet'] = include_once('img/foo.svg');
``` 
and place `{{ SVGsnippet }}`in the front-page.twig file the svg is properly placed without any warnings. 

If I try another function like `get_permalink`everything works as expected, when i try to get the link to a certain page number with `{{ fn('get_permalink', '9') }}` for example.

Is the warning and not showing of the svg for `{{ fn( 'include_once', 'img/foo.svg' ) }}` due to the fact that the parameter is a path or is it actually a bug? Cheers r.

**Comment by connorjburton** [comment]
Hi @rpkoller 

Just tested this, doesn't seem to be an issue with Timber, rather PHP itself. `fn` and `function` are just wrappers around `call_user_func_array`.

If you try and do `call_user_func_array('include_once', 'index.php')` in a php file you will get the same error, which leads me to believe PHP just doesn't support this.

I can't find anything online however pretty sure there isn't much we can do unfortunately. And i guess it's more the timber way to abstract includes away from your template.
