### ISSUE TITLE
Feature suggestion: Support for the ACF Pro select field

### ISSUE THREAD

**Issue by rpkoller** [jarednova/timber#667]
I tried my luck but at the present state it seems ACF Pro select field isn't working with Twig and Timber. http://www.advancedcustomfields.com/resources/select/ . especially if your posts in a loop contain a select field and you wanna query the state of that select field for each post. 

I am not that familiar with the Timber code as well as the naming convention but the basic logic could look  more or less similar to the acf documentation: 

```
function get_select_field( $field_name ) {
     $object = get_field_object( $field_name);
     $value = get_field($field_name);
     return $object['choices'][$value];
}
```

But as i said unsure where to place the function that twig could recognize it ( i guess `acf-timber.php` it is not ;) ) as well as how to name variables and functions to prevent conflicts with the rest of the plugin. Cheers r.

**Comment by adlitinc** [comment]
I'm running into the same situation where I have ACF-Pro select field that I want to query. I'm easily looping through a list but I just can't seem to get it.

/* single.php */
$context['listing'] = new TimberPost($post->business_sponsoring_event);

/* single-swfl_event.twig */
{{ listing.title }}

/* functions.php */
$context['events'] = Timber::get_posts( array(
   'post_type'      => 'swfl_event',
) );

/* what we need in archive-swfl_event.twig */
{{ event.get_field('event_start_date') }} //works
{{ listing.title }} //doesn't work

The field is set as  'post_object',

Thanks

**Comment by rpkoller** [comment]
@adlitinc Well i've solved it solely in the Twig file and mimiced the functions i've listed in my initial post. My select field values and labels look the following way: 

````
1 : Monday
2 : Tuesday
3 : Wednesday
4 : Thursday
5 : Friday
6 : Saturday
7 : Sunday
````
The Twig file the following way. I've commented the important steps. 
```twig
            <div class="courses">
            {% for post in dates.courses %}{# looping through $context['dates']['courses'] query results #}
                <article class="courses__event" itemscope itemtype="http://schema.org/Event">
                    {% set myday = post.class_day %} {# query the value of the current post e.g. 5 for Friday #}
                    {% set myobject = fn('get_field_object','field_53932a20ba16a') {# getting the field object by field id - field name doesn't work %}
                    <span class="lat-bn courses__day" style="color:{{ options.op_yoga_color }}">{{ myobject.choices[myday] }}</span>{# if you dump() the myobject you see the choices property containing all the available day labels - and by adding the myday variable you are able to get the label of the specific day #}
```
Hope that helps. Cheers r.

**Comment by connorjburton** [comment]
As this has been answered i'm going to close this. Feel free to comment if it's still an issue and i'll re-open.
