### ISSUE TITLE
timber + woocommerce and cart problem

### ISSUE THREAD

**Issue by xmd5a** [jarednova/timber#668]
Hello guys!
I have strange problem with woocommerce cart and probably TWIG.

I wrote custom ajax function which allows user to add product to cart. Everything works great when user is logged in but when user is NOT logged product is added but after going to cart page all products gone (probably these products are not stored).

Issue is common and most of people recommend to turn the cache off.

And here's my question - how can I completly disable cache in TWIG (views and PHP)?

**Comment by jarednova** [comment]
Hey @xmd5a! By default, the cache is turned off. If you want to confirm, you can set....

```php
Timber::$cache = false;
Timber::$twig_cache = false;
```

When rendering, use no argument (or `false`) for the third argument, ie....
```php
// works
Timber::render('single.twig', $data, false);
// works
Timber::render('single.twig', $data);

// doesn't work (will use cache)
Timber::render('single.twig', $data, 600);
```

**Comment by xmd5a** [comment]
@jarednova thanks for reply ;)

I'll try to make app works using your examples and reply here soon

**Comment by connorjburton** [comment]
Hi @xmd5a, is this resolved for you now?

**Comment by xmd5a** [comment]
yeah, everything works great
