### ISSUE TITLE
Timber related errors and warning on image delete

### ISSUE THREAD

**Issue by rpkoller** [jarednova/timber#676]
A friend informed me regarding an issue deleting an image from the media library showing timber related notices and warnings. I've tried as well which lead to the following white screen showing the following errors and warnings: 

```
Notice: Undefined index: dirname in /Applications/MAMP/htdocs/mypage/wp-content/plugins/timber-library/lib/timber-image-helper.php on line 171

Notice: Undefined index: extension in /Applications/MAMP/htdocs/mypage/wp-content/plugins/timber-library/lib/timber-image-helper.php on line 172

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/mypage/wp-content/plugins/timber-library/lib/timber-image-helper.php:171) in /Applications/MAMP/htdocs/mypage/wp-includes/pluggable.php on line 1207
```
I am using WordPress 4.3 and Timber 0.21.9 locally. In the wp-config.php i've set the following debug settings and the php error reporting is set to strict: 

```
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_DISPLAY', true );
 ```

Got feedback from my friend. on his local install debug was switched off, there no notices and warnings showed up, while on his remote install debug is switched on and showed the errors. By adding `isset` checks for the indexs in the `delete_generated_files` function the warnings could be eliminated: 

```php
	static function delete_generated_files( $local_file ) {
		if (!isset($info['dirname']) || !isset($info['extension']) ) {
			return false;
		}
		if (TimberURLHelper::is_absolute( $local_file ) ) {
			$local_file = TimberURLHelper::url_to_file_system( $local_file );
		}
		$info = pathinfo( $local_file );
		$dir = $info['dirname'];
		$ext = $info['extension'];
		$filename = $info['filename'];
		self::process_delete_generated_files( $filename, $ext, $dir, '-[0-9999999]*', '-[0-9]*x[0-9]*-c-[a-z]*.' );
		self::process_delete_generated_files( $filename, $ext, $dir, '-lbox-[0-9999999]*', '-lbox-[0-9]*x[0-9]*-[a-zA-Z0-9]*.' );
	}
```

Would have created a pull request but the code changed in the master branch to Timber 0.2.19 and i also dont know against which branch in particular i would have to place the pull request. 

Best regards r.

**Comment by connorjburton** [comment]
Closing this as the fix has been merged.
