### ISSUE TITLE
Timber + Live Customiser WordPress & Autoloading

### ISSUE THREAD

**Issue by JakeHenshall** [jarednova/timber#678]
Hi Jared,

Love the Timber Plugin,

Using it more & more :)

I just have a question about using timber / WordPress Live Customiser / Autoloading.

1. I've installed Timber via Composer and it seems to add in a wp-content folder into my theme directory, is there a best way to load it in or use composers autoloader. I don't want to install it as a plugin.

2. I want to use the Live Customiser to allow myself to style my theme but i seem to lose the live refresh ability once timber is working, is there a way i can get that functionality back. I'm using Kirki to override WordPress's default live customiser.

Any help would be much appreciated.

Thanks Jake.

**Comment by connorjburton** [comment]
Hi @JakeHenshall, discussion about autoloading/composer has moved to #835 - regarding the customiser, there seems to be quite a few reports of issues with this so something we are going to look at.

For now I am going to close this issue as it's really two issues, feel free to open a new ticket regarding the customizer.
