### ISSUE TITLE
Getting Author Avatar to Use Image

### ISSUE THREAD

**Issue by jwegner13** [jarednova/timber#679]
I am converting a theme of mine to use Timber. 

Here's what I used in conjunction with a plugin called 'Simple Local Avatars'. Just so I can easily set an Author box that is lightweight. Then I would just echo out $user_pic for the image. 

```
$user_pic	=	get_avatar( get_the_author_meta( 'ID' ), $photo_size ); 
```

So in the single.php file here's what I have:
```
$context['userpic']	=	get_avatar( get_the_author_meta('ID'), 300 ); 
```

When I am printing out the $context, I can't see a way to use the Author ID. Any help would be greatly appreciated. Thanks for Timber, I love using it.

**Comment by daviddarke** [comment]
Hi, Within the Timber post object you should have 'post_author' available to you (see print_r from a Timber::get_posts()).

<img width="786" alt="screen shot 2015-09-14 at 23 07 13" src="https://cloud.githubusercontent.com/assets/1636310/9863133/5d120974-5b35-11e5-9bf2-4c9ec054448d.png">

**Comment by connorjburton** [comment]
Hi @jwegner13, is this still an issue for you? Thanks

**Comment by connorjburton** [comment]
I'm going to close this as it seems inactive and it's already been answered. Feel free to comment and I will re-open.
