### ISSUE TITLE
The TimberPost object is missing the terms property

### ISSUE THREAD

**Issue by rpkoller** [jarednova/timber#685]
I've compared the TimberPost object properties listed over here https://github.com/jarednova/timber/wiki/TimberPost#properties with the actual properties in one of my queries.  All listed properties are there but terms is missing completely in every post. The only reference for terms is at the beginning of each post object with `get_terms:protected`: 

```php
  [1] => TimberPost Object
        (
            [ImageClass] => TimberImage
            [PostClass] => TimberPost
            [object_type] => post
            [_content:protected] => 
            [_get_terms:protected] => 
            [_permalink:protected] => 
            [_next:protected] => Array
                (
                )

            [_prev:protected] => Array
                (
                )
```

The setup. I am running WordPress 4.3, Timber 0.21.9, ACF Pro 5.3 and Custom Post Type UI 1.1.2. . The used query looks like that: 

```php
$quotes_args = array(
  'post_type' => 'quotes',
  'orderby' => 'rand'
);

$context['quotes'] = Timber::get_posts($quotes_args);
````
Alongside the custom post type "quotes" i have a custom taxonomy attached to that post type containing five terms. But none of the posts contains the terms property showing the term assigned to that post. Best regards r.

**Comment by jarednova** [comment]
Hey @rpkoller -- `terms` is a method so the contents won't show in a `print_r` but in a template you can do something like this

```
{% for term in post.terms %}
    <a href="{{ term.link }}">{{ term.name }}</a>
{% endfor %}

**Comment by rpkoller** [comment]
Thanks @jarednova . I've investigated a bit further. With the solution you've described i was unable to solve my problem. As stated in the comments of the timber-post.php i had to roll my own; but it works now. But it is good to know that the way you've described is viable too. cool! thanks a lot! 

p.s. was able to finish my first port of an existing site to timber now. i am more than content with the results and how clean, sorted and in control things are now. thanks a lot!
