### ISSUE TITLE
Threaded Comments ?

### ISSUE THREAD

**Issue by daslicht** [jarednova/timber#688]
Hello,
is there any example how to use threaded comments in Timber ?
I know that I could simply use ```{{ function('comments_template') }}``` but is there a cleaner way, please?

**Comment by josephbergdoll** [comment]
+1

**Comment by connorjburton** [comment]
Hi guys,

Thanks for raising this, this is probably best asked on Stackoverflow under the Timber tag.

http://stackoverflow.com/questions/tagged/timber

Thanks
