### ISSUE TITLE
enqueue scripts

### ISSUE THREAD

**Issue by virtualLast** [jarednova/timber#691]
did a quick search but didnt find what I was looking for. I've used functions.php created new function to register and enqueue multiple stylesheets. used add_action in the constructor for the StarterSite class but nothing is being output on the front end. what am I missing?

**Comment by corygibbons** [comment]
@virtualLast Post your code, seems to be working fine for me.

**Comment by connorjburton** [comment]
Hi @virtualLast, did you managed to solve this?

**Comment by connorjburton** [comment]
I am going to close this as I haven't had a reply. Feel free to comment at any point in time and I will re-open.
