### ISSUE TITLE
Timber::render encoding urls when called via ajax

### ISSUE THREAD

**Issue by fi5u** [jarednova/timber#692]
Hi. I'm having a hard time trying to debug what's going on here.

I'm calling `Timber::render()` in a function called by `wp_ajax_()` action. The template is rendering fine when passed back to the JavaScript ajax script. However, all special characters are encoded. I don't understand why and I can't seem to decode them. 

For example, `http://abc.com` is output as `http&#x3A;&#x2F;&#x2F;abc.com`. In my template I'm escaping the output like so:
```
<a href="{{ link|e('html_attr') }}">
```
When removing the twig escape filter, it's shows as expected. Now when this template is used outside of the ajax call, I have no problems escaping it on the output. This says to me that when it comes from the ajax call it is already escaped. So there's some double-escaping going on.

The only alternative I can think of is to create an identical template without the escaping, however I don't want to do that as it is not very maintainable.

Am I overlooking something obvious? Is there something else I could do? Why does the double-escaping not happen when `Timber::render` is called outside of the ajax call?
Thanks.

**Comment by aaemnnosttv** [comment]
You shouldn't need to escape that since [Twig does it for you](http://twig.sensiolabs.org/doc/templates.html#html-escaping).

**Comment by connorjburton** [comment]
Hi @fi5u, is this still an issue for you? Thanks

**Comment by fi5u** [comment]
@connorjburton, I'm no longer working on this project, so no it's no longer an issue.
