### ISSUE TITLE
TimberImage letterbox image quality option

### ISSUE THREAD

**Issue by t-wright** [jarednova/timber#693]
Wondering if there's appetite to allow setting of imagejpeg quality parameter via the letterbox and resize filters? I'm getting some gnarly quality loss on certain images. Passing quality 100 to imagejpeg in timberimageoperationletterbox resolves so having this option when needed would be great.

Eg left to right: original, resize, letterbox

![timberimageoperationletterbox-quality](https://cloud.githubusercontent.com/assets/4177859/10152356/59ad7d80-6694-11e5-9a23-37b7e917f565.png)

**Comment by koraysels** [comment]
+1 I need this too. a lot of resized images from really big DSLR jpegs look blurry after resizing

**Comment by mgussekloo** [comment]
+1 would like. Seems under the hood, TImber uses WP_Image_Editor. Maybe you could use something like this: https://developer.wordpress.org/reference/classes/wp_image_editor/set_quality/
