### ISSUE TITLE
How do I get posts from specific category

### ISSUE THREAD

**Issue by melcarthus** [jarednova/timber#694]
Hi,

I'm new to timber, but not to twig although I'm still a novice...
I don't know how to list posts from a specific category.

Normally I would do something like:

```twig
{% setcontent records = "entries/latest/4" where { 'categories': 'localblog' } %}
{% for record in records %}
	<a href="{{ record.link }}" title="{{ record.title }}"> 
		<div class="col-md-4 col-lg-4 col-xs-12">
			<div class="services" itemscope itemtype="https://schema.org/ProfessionalService">
				<div class="service-picture" style="background-image:url({{ paths.theme }}img/{{ record.slug }}.png);">
					<meta itemprop="image" content="{{ paths.theme }}img/{{ record.slug }}.png">
				</div>
				<h3 itemprop="name">{{ record.title }}</h3>
				<div itemprop="description">{{ record.teaser }}</div>
				<i class="fa fa-star"></i>
			</div>
		</div>
	</a>
{% endfor %}
```

And there is no part in the documentation that handles categories.

Or maybe I'm reading the wrong part of the documentation

**Comment by indiadamjones** [comment]
I can't  find any way to deal with categories either...I created a custom action in my functions.php, and then called with do action like this(see below), in my twig file.  Timber seems like a solution to a problem I didn't have which creates problems in the solutions I did have.

In the functions.php add the following:

add_action('cat_description', 'my_function');

function my_function($context){
    //$context stores the template context in case you need to reference it
    echo category_description(); //outputs title of yr post
}

Then, in my archive.html.twig I include the following line.

{% do action('cat_description') %}

Read more here:
https://github.com/jarednova/timber/wiki/WP-Integration#actions

**Comment by dinolatoga** [comment]
Are you trying to use this on an archive page?

**Comment by indiadamjones** [comment]
Okay, sorry kind of noob on this.  What I have above worked to pull the correct category description.  Do I need to use the additional ($id) syntax somewhere?

**Comment by dinolatoga** [comment]
So you're saying that it's working? What's the other problem then?

**Comment by indiadamjones** [comment]
I don't have one, I was offering a solution for OP.
