### ISSUE TITLE
Question: How to dynamically set active class in header in Timber?

### ISSUE THREAD

**Issue by minthemiddle** [jarednova/timber#696]
Hi,

how can I easily add a class `active` to my active menu item im Timber?

Let's say I have a simple navigation:

```html
<nav class="navbar">
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="/home/">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/features/">Features</a>
    </li>
</ul>
</nav>
```

If I am at `domain.com/home`, I want the `active` class be added ot the respective `li` element (as above), but when switching to `domain.com/features` I want the active class to be only visible at its `li`.

I found a solution for Twig in general at SO:

`{% if menu.url == current_url %} class="active"{% endif %}`
Source: http://stackoverflow.com/a/19687966

But I have no clue how to implement that with Timber. Here's what I tried for `features` - and failed with:

```html
<nav>...
<li class="nav-item">
<a class="nav link {% if post.permalink == {{ site.url }} . 'features' %} active{% endif %}" href="/features">Features</a>
</li>...
</nav>
```

**Comment by rpkoller** [comment]
How about just using twig blocks? In my base.twig file one line in the html header looks like that for example: 

```twig
<html {% block html__id %}{% endblock %} class="{% block html__class %}sticky__html no-js{% endblock %}" {{site.language_attributes}} dir="ltr">
```

On the front-page twig template i've added the following snippet: 

```
{% block html__id %}id="start"{% endblock %}

{% block html__class %}no-js{% endblock %}
```

So there is no need for any conditional logic at all. Took me a while to wrap my head around that concept but imho one key twig concept. Hope that helps.

**Comment by minthemiddle** [comment]
That could work. However, I would need to add an extra block for every `<li>` element in my `nav`, so it would become in the `base.html`:

```
<nav class="navbar">
  <ul class="nav navbar-nav">
    <li class="nav-item {% block nav_item_1 %}{% endblock %}">
      <a class="nav-link" href="/home/">Home</a>
    </li>
    <li class="nav-item {% block nav_item_2 %}{% endblock %}">
      <a class="nav-link" href="/features/">Features</a>
    </li>
</ul>
</nav>
 ```

And in the page's twig that is active:

```html
{% block nav_item_1 %}active{% endblock %}
```

Doable for a couple of items. But not very elegant if the list grows.

**Comment by rpkoller** [comment]
You could replace the whole nav block. The default state is without active and then replace the whole nav block once with the active state. So actually only one block to exchange. 

{% block nav_active %}
<nav class="navbar">
  <ul class="nav navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/home/">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/features/">Features</a>
    </li>
</ul>
</nav>
{% endblock %}

and the block to exchange

{% block nav_active %}
<nav class="navbar">
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="/home/">Home</a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="/features/">Features</a>
    </li>
</ul>
</nav>
{% endblock %}

**Comment by minthemiddle** [comment]
Yes, will do.
