### ISSUE TITLE
Twitterify not present in current version (v 0.21.10)

### ISSUE THREAD

**Issue by fofoy** [jarednova/timber#698]
Referring to the documentation (https://github.com/jarednova/timber/wiki/Text-Cookbook#automatically-link-urls-email-addresses-twitter-s-and-s) it seems a twitterify filter is present in Timber but I'm getting an exception when trying to use it.

```WARNING: CALL_USER_FUNC_ARRAY() EXPECTS PARAMETER 1 TO BE A VALID CALLBACK, CLASS 'TIMBERHELPER' DOES NOT HAVE A METHOD 'TWITTERIFY'```

**Comment by anugupta** [comment]
It was deprecated a while back and has now been removed. 

https://github.com/jarednova/timber/releases/tag/0.21.10

However, it's still here (https://github.com/Upstatement/timber-sugar) - although i haven't tried it to see if it's still working

**Comment by fofoy** [comment]
Ok thank you, I didn't notice it was deprecated.

Issue closed then.
