### ISSUE TITLE
Need help to make plugin for timber

### ISSUE THREAD

**Issue by pboisclair** [jarednova/timber#702]
Hi, 
I created a function flip images. Now I would like to convert it in extension. I need I little help to start this project. I extend the TimberImageHelper and  TimberImageOperation. Can you help me?

Thank. Timber is very nice.

Patrick

**Comment by slimndap** [comment]
Here is another Timber extension that works with images:
https://github.com/slimndap/TimberPhoton

**Comment by pboisclair** [comment]
Thank slimndap, I saw your plugin and it will be useful for me, but the problem is, I use some functions in the  TimberImageHelper file and I don't want to put all of this function in my plugin (if is possible).

Thanks

**Comment by connorjburton** [comment]
Hi @pboisclair, how did you get on with this?

**Comment by connorjburton** [comment]
I am going to close this as I haven't had a reply. Feel free to comment at any point in time and I will re-open.
