### ISSUE TITLE
How to handle conditional entry fields at controller level

### ISSUE THREAD

**Issue by benkutil** [jarednova/timber#703]
What's the best way to do something like this:

```
if (get_field('entry_heading')):
  $context['heading'] = get_field('entry_heading');
else:
  $context['heading'] = $post->post_title;
endif;
```

Where the entry is saved in $context['post'].

Ideally, in to use `{{ post.title }}`, and have it updated by the above conditional.

**Comment by connorjburton** [comment]
Hi @benkutil, what you have done above is okay. Otherwise you could directly alter the $post itself, so something like:

```php
$post->post_title = (has_field('entry_heading')) ? get_field('entry_heading') : $post->post_title;
```

**Comment by benkutil** [comment]
Thanks @connorjburton
