### ISSUE TITLE
Set up a Timber Slack team or IRC channel

### ISSUE THREAD

**Issue by anugupta** [jarednova/timber#704]
Opening an issue to discuss and help out if necessary. 

I think it would be very useful to have somewhere where we can discuss Timber and get and give help. I had a little discussion with @jarednova on Twitter about Slack or IRC, and it seems preferable to get something going on IRC.

What does everyone think?

**Comment by prisis** [comment]
Hey, why not gitter.im?

**Comment by anugupta** [comment]
@prisis No real reason apart from never having used it, and that I'm already using Slack and IRC, so those were the tools that I thought of.

I personally don't mind what is used, as long as we end up with something :)

**Comment by rpkoller** [comment]
+1 for the idea. but i would tend to either the mentioned slack ( where most of the wordpress related conversations happen these day ) or irc. to get another chat app like gitter.im just for a timber channel i am unsure if i would join. but that are only my two cents. ;)

**Comment by daslicht** [comment]
freenode -> #timber

**Comment by dinolatoga** [comment]
+1

**Comment by jarednova** [comment]
@dinolatoga @daslicht @rpkoller @anugupta @prisis I've got things setup. Email me at jared@upstatement.com and I'll invite you to the Slack Team

**Comment by anugupta** [comment]
:)

**Comment by jarednova** [comment]
For those wondering, we've shut down the Slack team in favor of Gitter:

https://gitter.im/timber/timber?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
