### ISSUE TITLE
Routing doesn't work on MAMP but works on live server

### ISSUE THREAD

**Issue by andydlin** [jarednova/timber#710]
Hi guys,

Something is weird, I've setup routing for my Schedule page but on my MAMP server, it says that "The requested URL was not found" but it works perfectly on my live server. Then I tried setting up a new route for my Sign Up page but now it doesn't work on either MAMP or the live server.

Here's the code in my function.php:

```
Timber::add_route('schedule', function($params) {
	Timber::load_template('schedule.php', null, 200, $params);
});

Timber::add_route('register', function($params) {
	Timber::load_template('signup.php', null, 200, $params);
});
```

And the code in my schedule.php:

```
$templates = array('schedule.twig');
$context = Timber::get_context();
Timber::render($templates, $context);
```

And code for signup.php:

```
$templates = array('signup.twig');
$context = Timber::get_context();
Timber::render($templates, $context);
```

Thanks in advance for the help!

**Comment by lukasholzer** [comment]
My issue is qite the same on mamp an testserver ii is working but on live environment i get a 404

**Comment by lukasholzer** [comment]
The only difference is that i used a wordpress quick install on live

**Comment by connorjburton** [comment]
Thanks for the update @lukasholzer - will take a look today as I am working on a project on MAMP with Timber

**Comment by lukasholzer** [comment]
Thanks @connorjburton – it is realy urgent, because it is on the live system and i can't realize why it does not work. The test environment (where it is working is on the same server, only in a subfolder) and the theme folder is a git repository with a jenkins build – so it is the complete same code on live and test.

if you want't i can add you to my bitbucket repo for helping me, contact me at [office@lukasholzer.com](mailto:office@lukasholzer.com)

**Comment by connorjburton** [comment]
I have tested this on MAMP and then pushing up to a live server and everything works fine.

Can you post you post the URL that is 404'ing please? (Doesn't have to be publicly accessible, just so I can see the URL itself)

Also do you have a `sendmail.php`?

**Comment by lukasholzer** [comment]
Yea it is public accessible [http://www.kleinmuenchner.at/sendmail/t/Fragen/](http://www.kleinmuenchner.at/sendmail/t/Fragen/) and i pass some variables with a post and the sendmail.php exists
on my testsystem everything works…

the url to the test system is  [http://test.kleinmuenchner.atsendmail/t/Fragen/](http://test.kleinmuenchner.atsendmail/t/Fragen/)

**Comment by connorjburton** [comment]
I've sent you an email @lukasholzer

**Comment by connorjburton** [comment]
Hi @lukasholzer - I have cloned your repo, set it up and tested it on MAMP and it works fine.

Are you sure your server just doesn't have a `.htaccess` in the web root? If I take the `.htaccess` out of my local install the same thing happens.

I'm 90% sure this is a server config issue.

**Comment by lukasholzer** [comment]
Thanks so how should the .htaccess looks like?


Regards Lukas

Lukas HOLZER | Frontend Developer

Web & Kommunikationsdesign
Sandgasse 16/3, 4020 Linz
lukas.holzer@netural.com | +43 660/48 355 48
office@lukasholzer.com | www.lukasholzer.com

Am 3. März 2016 bei 14:43:04, Connor Burton (notifications@github.com) schrieb:

Hi @lukasholzer - I have cloned your repo, set it up and tested it on MAMP and it works fine.

Are you sure your server just doesn't have a .htaccess in the web root? If I take the .htaccess out of my local install the same thing happens.

I'm 90% sure this is a server config issue.

**Comment by connorjburton** [comment]
Like the default wordpress `.htaccess` https://codex.wordpress.org/htaccess

**Comment by connorjburton** [comment]
Did this work for you @lukasholzer

**Comment by connorjburton** [comment]
I'm going to assume this is okay, i'm sure these problems are server configuration. Please let me know if this is still an issue and i will re-open
