### ISSUE TITLE
No 'Awaiting Moderation' message after posting comments

### ISSUE THREAD

**Issue by dinolatoga** [jarednova/timber#711]
Normally, when a commenter leaves a message and comment moderation is on, the commenter should be able to read a *Your comment is awaiting moderation* message. This doesn't work for me in Timber. Anybody got a clue?

**Comment by dinolatoga** [comment]
My code looks kinda looks like this:

    {% for comment in post.comments %}
        {% if comment.approved %}
            <li>{{comment.author.name}}, says {{comment.content}}</li>
        {% else %}
            <li>{{comment.author.name}}, says {{comment.content}}<br>Your comment is awaiting moderation.</li>
        {% endif %}    
    {% endfor %}`
`

**Comment by connorjburton** [comment]
This seems to have been fixed in #770 so i'm going to close this. Let me know if you are still having issues @dinolatoga
