### ISSUE TITLE
Getting Repeater Values From Site Options

### ISSUE THREAD

**Issue by JakeHenshall** [jarednova/timber#712]
Hi,
How would i go about showing the value from a repeater field in Twig.

    {% for test_section in post.get_field('test_section') %}
        <h4 class="grid__column--title">{{test_section.title_left}}</h4>
            {% for content_left in test_section.content_left %}
                <li><a href="{{content_left.link_left}}">{{content_left.left_link_title}}</a></li>
            {% endfor %}
    {% endfor %}

The code above works if i want to loop if the repeater is on a page.
and this code works for getting the value from the options page if it isn't a repeater.

    <p>{{option.contact_email}}</p>

any help is much appreciated.
Jake

**Comment by pensandpencils** [comment]
Hey @JakeHenshall

Am running into the issue you have here and just wondered how you solved it? 

Any help would be hugely appreciated!

Thanks and hope to hear back from you.

**Comment by pensandpencils** [comment]
As is always the way - two minutes after sending this I figured it out. So for anyone else who has this issue:

I added this function (edited of course to my requirements)

`add_filter( 'timber_context', 'mytheme_timber_context'  );
function mytheme_timber_context( $context ) {
    $context['options'] = get_fields('option');
    return $context;
}`

Then this to the template:

`{% for option in options.your_repeater_acf %}
	{{option.your_repeating_field}}
 {% endfor %}`
