### ISSUE TITLE
post.permalink missing protocol

### ISSUE THREAD

**Issue by piotrkulpinski** [jarednova/timber#714]
Hi,

Not sure the issue is related to Timber itself but `{{ post.permalink }}` run locally is returning addresses without the protocol specified. So instead of:

```
http://localhost:3000
```
I get 
```
//localhost:3000
```

Is this some common issue? On remote servers protocols are added to the permalink.
Thanks

**Comment by connorjburton** [comment]
Hi @piotrkulpinski, as far I can see Timber just returns whatever Wordpress returns for Permalinks, this sounds more of an environment issue (as you mentioned it works on a remote server).

From a personal opinion, without a protocol would probably be better anyway

I'm going to close this, if you can reproduce this consistently regardless of environment please let me know.
