### ISSUE TITLE
Adding Yoast Breadcrumbs

### ISSUE THREAD

**Issue by JakeHenshall** [jarednova/timber#719]
Hi,

Is there an easy way to add the yoast breadcrumbs into the timber framework?

Thanks Jake.

**Comment by terminalpixel** [comment]
I use something like this:

    if ( function_exists( 'yoast_breadcrumb' ) ) {
        $context['breadcrumbs'] = yoast_breadcrumb('<nav id="breadcrumbs" class="main-breadcrumbs">','</nav>', false );
    }

Which lets you just use the breadcrumbs html as a variable.

**Comment by JakeHenshall** [comment]
@terminalpixel Hey cheers mate, sorry for the late reply. how would you go about adding it in as a variable and how would you show it using a ACF checkbox?

**Comment by nickmoline** [comment]
@JakeHenshall 

If you do the context thing that @terminalpixel mentions above (adding it to your single.php before you render the twig) you could do it like this (assuming your ACF checkbox is named `enable_breadcrumbs`)

```twig
{% if post.enable_breadcrumbs %}{{ yoast_breadcrumb }}{% endif %}
```

If you don't want to bother with adding to your single.php you can replace `{{ yoast_breadcrumb }}` with 
```twig 
{{ function('yoast_breadcrumb', '<nav id="breadcrumbs" class="main-breadcrumbs">','</nav>', false ) }}
```

To call the function directly from your twig template

**Comment by JakeHenshall** [comment]
@nickmoline cheers mate, how can i check if a checkbox is selected and display an image. Here is my current code ->                                         

{% if post.icon == 0 %}
    <img style="margin: 0 auto; display: block; width: 40%;" src="/img/trophy.png" alt="">
{% else %}
    <img style="margin: 0 auto; display: block; width: 40%;" src="/img/medal.png" alt="">
{% endif %}

The Icon is triple nested 

achievements -> achievement -> achievement_desc -> {{ Icon }}

Any help would me much appreciated.

Thanks

**Comment by connorjburton** [comment]
Just adding this for anyone who searches for 'breadcrumbs timber wordpress'

You can alternatively do this to preserve ability to use arguments.

functions.php
```
if(function_exists('yoast_breadcrumb')) {
    function breadcrumbs($before = '', $after = '', $display = true) { return yoast_breadcrumb($before, $after, $display); };
	TimberHelper::function_wrapper('breadcrumbs');
}
```

index.twig
```
{{breadcrumbs('arg1', 'arg2', false}}
```

**Comment by connorjburton** [comment]
I think all relevant permutations of breadcrumbs have been mentioned so going to go ahead and close this.
