### ISSUE TITLE
Latest version breaks ACF date field dates

### ISSUE THREAD

**Issue by t-wright** [jarednova/timber#724]
I think pull request 715 https://github.com/jarednova/timber/commit/a6ba9ddb7f49a4231450912efa987058dc5d2093 exposed an issue with ACF date field values. Returned values are always numeric (even if you specify a string or date format in field settings) but they aren't unix timestamps, rather Ymd (20140917). As such date_i18n() doesn't play nice with them.

**Comment by rpkoller** [comment]
Yep same here. problem is dates are saved numeric in the 20151028 format in acf . so with that patch the else if statement matches and intval is run instead of strtotime. so with intval the value remains the same instead of getting converted into the necessary unix timeformat. :/

**Comment by jarednova** [comment]
@t-wright @rpkoller thanks for the heads-up on this. I'll take a look at it first-thing tomorrow

**Comment by xavivars** [comment]
Found a possible fix. I'll commit the change in a pull request

**Comment by xavivars** [comment]
Didn't realize @rpkoller fixed it earlier on #727. Just closed #728.

**Comment by jarednova** [comment]
Closed by #727 I also added a test in dd1c09738f072a0bfe17d6d822d59ce34b5e1b3c to catch the condition in the future
