### ISSUE TITLE
Preview of a Flexible Content Field

### ISSUE THREAD

**Issue by shiftsave** [jarednova/timber#725]
Hi guys,

I was wondering if anyone knows of a way to truncate an ACF Flexible Content Field in the same way timber handles post previews.

I tried adding the get_preview to it in hopes that it would work but it doesn't.

{% for media_item in post.get_field('content') %}
			{% if media_item.acf_fc_layout == 'text' %}
					{{media_item.text.get_preview(30)}}
			{% endif %}
	{% endfor %}

Thanks!

**Comment by dinolatoga** [comment]
Use truncate filter like so:

`{{ your_variable | truncate(8) }}`

More helpful filters [here](https://github.com/jarednova/timber/wiki/Filters)

**Comment by shiftsave** [comment]
Thanks! Is there also a way to only target the first row of that same content field?

Given that I use rows to organize the content of the post, truncate is truncating the beginnings of all rows rather than just the first.

```
{% for media_item in post.get_field('content') %}
		{{media_item.text | truncate(10)}}
	{% endfor %}
```

Outputs:

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id…
Proin bibendum quam odio, sit amet imperdiet mi vestibulum sit…
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id…

**Comment by dinolatoga** [comment]
{% for media_item in post.get_field('content') %}
{
  {{ media_item.text | truncate(10)}}
{% endfor %}

**Comment by dinolatoga** [comment]
````
{% for media_item in post.get_field('content') %}
  {% if loop.first %}
    {{ media_item.text | truncate(10) }}
  {% else %}
    {{ media_item.text }}
  {% endif %}
{% endfor %}
````

**Comment by dinolatoga** [comment]
A shorter solution would be.

````
{% for media_item in post.get_field('content') %}
{{ loop.first ? media_item.text | truncate(10) : media_item.text }}
{% endfor %}
````

I haven't tested all of the code above but it should work.

**Comment by shiftsave** [comment]
I removed the last part and it worked perfect:

```
{% for media_item in post.get_field('content') %}
    {{ loop.first ? media_item.text | truncate(20)}}
{% endfor %}
```

**Comment by dinolatoga** [comment]
Cool. Glad to see it work for you. A simpler solution would be:
````
{% set var = post.get_field('content') | first %}
{{ var.text | truncate(20) }}
````

**Comment by dinolatoga** [comment]
You can close this thread now by the way.
