### ISSUE TITLE
How to get the timber phpunit tests running in vvv

### ISSUE THREAD

**Issue by rpkoller** [jarednova/timber#726]
I've never used phpunit so far but wanted to let it run through before i place my next pull request. i am running my sites via vvv locally. i've then installed the timber version via git. 

```
git clone git@github.com:jarednova/timber.git
```

then used 

```
composer install
```
to install all the dependencies. in the next step i've just hit `phpunit`in the timber directory (version 4.7.6.). but then i get two warnings:

```
Warning: require_once(/tmp/wordpress-tests-lib/includes/functions.php): failed to open stream: No such file or directory in /Users/danton/Documents/Coding/Vagrant/vvv/www/timbertest/wp-content/plugins/timber/tests/bootstrap.php on line 7

Fatal error: require_once(): Failed opening required '/tmp/wordpress-tests-lib/includes/functions.php' (include_path='.:') in /Users/danton/Documents/Coding/Vagrant/vvv/www/timbertest/wp-content/plugins/timber/tests/bootstrap.php on line 7
```

based on the settings in the bootstrap.php i dont have a `/tmp/wordpress-tests-lib` folder as well as no `/includes/functions.php`  file and there isnt also any `/includes/bootstrap.php` . i am bit confused. :/ a brief headsup where and what to change to get the phpunit tests running would be more than appreciated. :) thanks r.

**Comment by xavivars** [comment]
If I'm not wrong, what I did some time ago was to create that folder (`/tmp/wordpress-tests-lib`) before running the tests. But probably you already tried that...

**Comment by rpkoller** [comment]
thanks for the headsup... hmmmmm ok manually creating those two folders helped at least a little... guess i also have to create the includes folder inside the `wordpress-tests-lib` folder but then i am still missing the two already mentioned files `functions.php` and `bootstrap.php. which do i have to use there? still a bit uncertain and puzzled. ;)

**Comment by xavivars** [comment]
(info coming from https://github.com/jarednova/timber/blob/master/.travis.yml)

Try to do this BEFORE running phpunit

`bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION`
`composer install --dev --prefer-source`

with `$WP_VERSION` being the version you want to test.

Then, you'll be able to run your tests.

**Comment by connorjburton** [comment]
@jarednova I assume this is all okay now?
