### ISSUE TITLE
wp_title() throws deprecated warning in WordPress 4.4

### ISSUE THREAD

**Issue by danielbachhuber** [jarednova/timber#730]
Called by `TimberHelper::get_wp_title()`

**Comment by danielbachhuber** [comment]
For those wanting to ignore this in their tests, you can overload `WP_UnitTestcase::expectedDeprecated()`:

```
/**
 * Overload WP_UnitTestcase to ignore deprecated notices
 * thrown by use of wp_title() in Timber
 */
public function expectedDeprecated() {
	if ( false !== ( $key = array_search( 'wp_title', $this->caught_deprecated ) ) ) {
		unset( $this->caught_deprecated[ $key ] );
	}
	parent::expectedDeprecated();
}
```

**Comment by connorjburton** [comment]
Do you know if this is resolved @jarednova

**Comment by jarednova** [comment]
Yes! The main issue that @danielbachhuber points out (the error being thrown) is resolved. It would still be ideal to remove `wp_title` entirely as it's deprecated, but that's out-of-scope for this ticket (and brings up a bunch of other questions about backwards compatibility vs. ideal output)
