### ISSUE TITLE
Nested modular components with controllers

### ISSUE THREAD

**Issue by willvedd** [jarednova/timber#732]
Is there a way to nest a component with a controller within a page template? From what I've gathered so far, since the data flow is unidirectional, all fields and relevant components need to be organized at the time of the page controller instantiation. A use case for this would be related-content blocks where modular blocks should have their own template and controller to delegate various business logic but there isn't a place to render these blocks since the page.twig files don't seem to run php. Does this make sense?

**Comment by connorjburton** [comment]
Hi @willvedd, sorry for the late reply. Do you mean conditionally loading .twig templates inside a template? Such as:

```twig
{% for row in post.get_field('rows') %}
	{% set data = {'data': row[row.type]} %}
	{% include "rows/#{row.type}.twig" with data %}
{% endfor %}
```

**Comment by connorjburton** [comment]
Hi @willvedd - as this seems to be inactive i'm going to close this, if this is still an issue for you please feel free to comment and I will re-open.

Thanks

**Comment by thedamon** [comment]
This is something I'm thinking of as well.

My use case is a partial (.twig) that has a certain data interface that can be used to list a number of different things, which are coming from different data sources. Really I think I will always be able to see in the page controller which are being used and then if necessary create a 

But if not, I think the best way to address this with what's available in Timber would be a custom filter (`include 'templates/components/tablist.twig with tabs: post | formatChildPagesForTabList`) that formats input as needed for the view.

This way it's clear from looking where the data is coming from *and* you're using PHP to do the data restructuring.
