### ISSUE TITLE
Add comment about get_posts limit on docs

### ISSUE THREAD

**Issue by Blueblau** [jarednova/timber#735]
Hi guys,

Can you please add a comment about the limit on `get_posts`? It's currently 10.

**I had to do this:**
```php
$context['jobs'] = Timber::get_posts(array(
    'posts_per_page' => 100,
    'post_type' => 'job',
));
```

...in order to get all my posts with `post_type` "job".

**Comment by jarednova** [comment]
@Blueblau it should take the `posts_per_page` from the value you've set in the "Reading" section of the admin (which matches with WP's default usage of `get_posts`). Give that a shot and see if it works

**Comment by Blueblau** [comment]
Oh, I see. Maybe it's just me that isn't that familiar with Wordpress, but I would have loved a little note about the limit in the docs. Thank for for an awesome product! :+1:

**Comment by connorjburton** [comment]
Updated the docs with a little note
