### ISSUE TITLE
{{dump()}}} not working --> Fatal:Error Uncaught Exception

### ISSUE THREAD

**Issue by maxleistner** [jarednova/timber#739]
I am trying to use `{{dump()}}` but it is nor working. define( 'WP_DEBUG', true ); is set to TRUE.
I am getting the following error:

Fatal error: Uncaught exception 'Twig_Error_Syntax' with message 'The function "dump" does not exist in "/views/frontend.twig"

WordPress: 4.3.1
TimberLibrary: 0.22.0

Any ideas?

**Comment by nanotime** [comment]
I think that it's not supported... i tryed to use that function like the twig documentation says and nothing...

Anyway, try something like `{{function('dump()')}}`, maybe that works

**Comment by pboisclair** [comment]
I have the same problem since the last update

**Comment by jarednova** [comment]
Thanks for the heads-up, I'll investigate

**Comment by connorjburton** [comment]
Hi @maxleistner - is this still an issue?

**Comment by maxleistner** [comment]
Hi @connorjburton – i did not use the function any more. Sorry for not being of any help

**Comment by neemiasjnr** [comment]
I solved by setting WP_DEBUG to true in wp-config
