### ISSUE TITLE
'The function "TimberImage" does not exist in 

### ISSUE THREAD

**Issue by maxleistner** [jarednova/timber#740]
Trying to use `<img src="{{TimberImage(post.get_field('bild_worker')).src}}" />` get a Fatal error:

Fatal error: Uncaught exception 'Twig_Error_Syntax' with message 'The function "TimberImage" does not exist

**Comment by dinolatoga** [comment]
Assuming that the `bild_worker` is an image custom field, you can get the image url like so:
````
{% set image = post.get_field('bild_worker') %}
<img src="{{ image.url }}">
````

**Comment by maxleistner** [comment]
@dinolatoga Correct. It is a custom field. But it is not working. 

I have a page (Backend) where with a dropdown (POST OBJECT ACF) i can choose a custom post type called `workers`. Within the CPT is a ACF field called `bild_worker` defined as an ACF Image Field with ID as parameter value. Now, on my page i get only the ID as return. Does this help figuring out the problem?

**Comment by jarednova** [comment]
@maxleistner does that error have a file/line number?

**Comment by dinolatoga** [comment]
To make my solution work, edit the ACF and make the return value an Image Object instead.

**Comment by maxleistner** [comment]
@dinolatoga doesn't work as well :(

**Comment by maxleistner** [comment]
@jarednova `Fatal error: Uncaught exception 'Twig_Error_Syntax' with message 'The function "TimberImage" does not exist in "/views/frontend.twig" at line 12' in ***/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/ExpressionParser.php:578 Stack trace: #0 ***/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/ExpressionParser.php(351): Twig_ExpressionParser->getFunctionNodeClass('TimberImage', 12) #1 ***/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/ExpressionParser.php(144): Twig_ExpressionParser->getFunctionNode('TimberImage', 12) #2***/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/ExpressionParser.php(84): Twig_ExpressionParser->parsePrimaryExpression() #3 ***/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/ExpressionParser.php(41): Twig_ExpressionParser->getPrimary() #4 /Vol in ***/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/ExpressionParser.php on line 578`

**Comment by jarednova** [comment]
@maxleistner I'm not sure what's going on. What you're showing is valid and matches the contents of this (passing) test:

https://github.com/jarednova/timber/blob/master/tests/test-timber-twig-objects.php#L7

Some ideas:
- Can you confirm that `TimberImage` twig function exists in the [`lib/timber-twig.php`](https://github.com/jarednova/timber/blob/master/tests/test-timber-twig-objects.php#L7) file in your setup?
- Can you copy-and-paste `TimberImage` into your code (views/frontend.twig) to make sure there are no special characters hiding-out?
- Can you try another Timber object function (like `{{ TimberPost(post_id).title }}`) to see if that triggers an error?
- See what `post.get_field('bild_worker')` itself spits out in a template. `TimberImage` _should_ be able to handle either a post ID or an attachment object, but let's make sure we know which one we're working with

**Comment by maxleistner** [comment]
@jarednova 

- The twig function does exist in plugins/timber-library/lib/timber-twig.php
- another Timber object function does NOT work as well. Same error
- post.get...does not spit out anything at all

what now? :(

**Comment by rpkoller** [comment]
@maxleistner maybe redownload the plugin from wordpress.org and replace the downloaded version with the one making troubles in your plugins folder?

**Comment by maxleistner** [comment]
@rpkoller tried this as well :(

**Comment by bambamboole** [comment]
Try to install a fresh wordpress with timber, acf and acf viewer.

then try again with a single custom field.

I believe that will help you with your issue.

**Comment by PatrikJarl** [comment]
This one just closed down without an confirmed solution? I have the same problem.

**Comment by PatrikJarl** [comment]
Omg.. 
plugins --> activate Timber 

*facepalm*

Now lunch.
