### ISSUE TITLE
Using React.js with Timber

### ISSUE THREAD

**Issue by JakeHenshall** [jarednova/timber#743]
Hi,

Could anyone possibly give me an example of using react.js and outputting into twig files?

Thanks Jake.

**Comment by milanholy83** [comment]
using react is same with and without twig. or you want to render react on server side?

**Comment by connorjburton** [comment]
As @milanholy83 said, it shouldn't matter if you are using Timber or not for React. Closing this, please comment ID you have more info.

**Comment by davisshaver** [comment]
I'm looking into using Timber template to render modules with PHP and then hydrate with React 16. Has anyone done this?
