### ISSUE TITLE
do_shortcode in Timber

### ISSUE THREAD

**Issue by petenorris** [jarednova/timber#744]
Is there a simple timber way of using WP's do_shortcode?

I currently use: <?php echo do_shortcode( 'content' ) ?> which does exactly what I need, but cant find anything as concise in timber - Don't need to change/filter anything, just need to show the shortcode in theme template rather than WP editor.

Thanks.

**Comment by dinolatoga** [comment]
{{ function('do_shortcode', 'content') }}

**Comment by petenorris** [comment]
Thanks so much.

**Comment by grohlbainselic** [comment]
How do I pass post.id inside a shortcode function? 

As in:

 {{ function('do_shortcode', '[favorite_button post_id="{{post.id}}"]') }}

**Comment by gchtr** [comment]
@grohlbainselic You can’t nest the double curly braces `{{ }}`. But, you could use Twig’s string concatenation with `~`.

```twig
{{ function('do_shortcode', '[favorite_button post_id="' ~ post.id ~ '"]') }}
```

Sometimes that gets a little difficult to read with all the `"` and `'`. As an alternative, you could also use the [`format` filter](https://twig.symfony.com/doc/2.x/filters/format.html) in Twig, which works pretty much like [`sprintf`](https://www.php.net/manual/en/function.sprintf.php) in PHP and replaces all the placeholders in your string with what you pass to the filter.

```twig
{{ function('do_shortcode', '[favorite_button post_id="%s"]'|format(post.id)) }}
```
