### ISSUE TITLE
Possible to get random row from ACF repeater?

### ISSUE THREAD

**Issue by Twansparant** [jarednova/timber#745]
Hi there,

I'm just starting to learn Timber and am loving it so far!
Was wundering if it's possible to get a random row from a ACF repeater field, just like described here: http://www.advancedcustomfields.com/resources/repeater/ but in a twig template?

The `array_rand` obviously is a php function, but I really need it in my template right now.
I tried to install this Twig extension: https://github.com/umpirsky/twig-php-function but I have no idea how to correctly register and load it in my theme.

The following loop works:
```twig
{% for video in section.section_videos %}
  <img src="{{TimberImage(video.video_poster).src}}" />
{% endfor %}
```
But I would like to do something like this:
```twig
{{array_rand(section.section_videos)}}
```

Thanks!

**Comment by Twansparant** [comment]
Never mind, was looking for random function in Timber documentation, but should have been looking in the Twig documentation... This works!
`{% set video = random(section.section_videos) %}`

**Comment by frazerf** [comment]
Hey there, I'm having trouble with this as well but I can't seem to see how you're executed it in the mark up.

Mine looks like this - 

<div class="my-list">
{% for bike in post.get_field('biker') %}
    <div class="item">
        <h4>{{random(bike.item)}}</h4>
    </div>
{% endfor %}
</div>

If you could help I'd be really appreciative.

**Comment by Twansparant** [comment]
You can't use it within the loop, you should use it like this:
'{% set biker = random(post.get_field('biker')) %}'
Assuming the biker field returns an array?
