### ISSUE TITLE
404 with custom post type

### ISSUE THREAD

**Issue by nanotime** [jarednova/timber#746]
That's a weird thing, or a noob thing, i don't know but im trying to access in a single post page from a list and i get a 404. Let me show you my liitle code:

Here is the list, a page called "servicios" where i pull the list of "servicios" (the custom post type):

``` php
// page-servicios.php
<?php

$context = Timber::get_context();
$context['servicios'] = Timber::get_posts("post_type='servicios'");

Timber::render('page-servicios.twig', $context);
```

That's work, i'm getting all "servicios" without problems here. The problem *per se* is when i click the link of any post, it returns me a 404 (but no the 404 template).

The default single.php works, i create a blog in the same web and it works fine, but no with the custom post, so i create another single for it:

``` php
// single-servicios.php
<?php

$args = array(
    'post_type' => 'servicios'
);

$context = Timber::get_context();
$post = Timber::query_post($args);
$context['post'] = $post;

Timber::render('single-servicios.twig', $context);
```

Stupidly simple, but nope, it doesn't work... here is a capture of the "single-servicios":

![404](https://cloud.githubusercontent.com/assets/1323582/11148274/eebdf5a4-89ed-11e5-88ca-deb2bcf9e0fa.png)

Any idea? :/

**Comment by dinolatoga** [comment]
In your WordPress dashboard, go to Settings > Permalinks then re-save it.

**Comment by nanotime** [comment]
My template exploded D:

Now i can't see the lists on any page

**Comment by dinolatoga** [comment]
It means that the correct template is loaded however there is an error in `single-servicios.php`. You don't need to define the `$args` anymore. So your single-servicios.php should only look like this:

````
$context = Timber::get_context();
$post = Timber::query_post();
$context['post'] = $post;
Timber::render('single-servicios.twig', $context);
````

**Comment by nanotime** [comment]
Haha The problem is that now before carrying on the list, no longer charge, now simply recognizes nothing.

I do not know if I explain myself, this:

```
<?php

$context = Timber::get_context();
$context['servicios'] = Timber::get_posts("post_type='servicios'");

Timber::render('page-servicios.twig', $context);
```

Is not working anymore, no idea why, just the templates "page-servicios.twig" don't charge.

**Comment by dinolatoga** [comment]
Don't use a page for post type archives. Just use the archives template. The problem here is that your post type slug conflicts with the page slug. I could give you a comprehensive solution but I am on mobile right now. You should be able to figure it out on your own.

**Comment by nanotime** [comment]
Hm, im really noob on this, is my second site in wp and i always used timber, but don't know how to use the archive... Not only for use with taxonomies and that? let me see.

**Comment by dinolatoga** [comment]
Quick workaround would be changing the slug of your page. So instead of using servicios, just use some other page slug.

**Comment by nanotime** [comment]
It works a little, the lists reapeared, the 404 error is gone, but the "single" still show nothing... anyway i learned some new today, i'll trying to solve this, sure i'll have more doubts with this but well, you helped me a lot.

Don't close this issue rigth now, I'll try a few things to try to solve it.

**Comment by connorjburton** [comment]
Hi @nanotime, have you resolved this? Thanks

**Comment by nanotime** [comment]
Yep, solved. Simple, i'm was using same names in a page and custom-post singular name, so it cause some conflicts, the solution was to use the record template.

**Comment by connorjburton** [comment]
Thanks for getting back to me @nanotime and glad its sorted!
