### ISSUE TITLE
Co-authors in template

### ISSUE THREAD

**Issue by shiftsave** [jarednova/timber#747]
Can anyone guide me on a way to properly add multiple authors to a post?

**Comment by dinolatoga** [comment]
I don't think that your problem is a Timber issue or bug in particular but to give you an idea of a solution to your problem, use custom fields.

**Comment by jarednova** [comment]
@shiftsave I recommend creating an object that extends `TimberPost` inside of which add a custom `authors

**Comment by dinolatoga** [comment]
@shiftsave You will be needing the [Co-Authors Plus]("https://wordpress.org/plugins/co-authors-plus/") plugin for that solution to work.

**Comment by shiftsave** [comment]
Thanks I'll try this!

**Comment by rbvea** [comment]
Just noting that if a TimberPost had an `authors` attribute (e.g. {{ post.authors }}, this commit would've broken it as it references the co-authors plugin now instead of the variable.
