### ISSUE TITLE
post.get_preview() adds a </p> to excerpts without a corresponding <p> tag

### ISSUE THREAD

**Issue by jon-childs** [jarednova/timber#748]
In TimberPost, when generating a post excerpt, the generated text always has a `</p>` appended to it (lines 391-392), if tag stripping is disabled. This causes many instances of a singular closing `</p>` tag with no corresponding opening tag. An example would be any manual excerpt without a `<p>` or an automatically generated excerpt where the post content is a table.

My quick band aid was to change the condition where a `</p>` is added to:
`if ( !$strip && $last_p_tag && ( strpos($text, '<p>') || strpos($text, '<p ') ) ) `

Any thoughts are much appreciated.

**Comment by jarednova** [comment]
Thanks for the heads-up @jon-childs -- I'll take a look!

**Comment by jarednova** [comment]
@jon-childs it turns out I'm not able to trigger the error — can you post a gist to a manual excerpt that triggers the incorrect `</p>` tags for you? Also, the exact way you're calling these from within a Twig template so I can make sure to use all the same info in my tests. Thanks!

**Comment by jon-childs** [comment]
@jarednova Thanks for the reply! Here's my simple gist that adds the extra `</p>`
https://gist.github.com/jon-childs/3498bbb2b90abe316284

Below are some screenshots of the markup generated.
![screen shot 2015-11-17 at 2 16 52 pm](https://cloud.githubusercontent.com/assets/2837721/11225199/2174e99e-8d36-11e5-8b92-55e26dba7b13.png)
![screen shot 2015-11-17 at 2 17 10 pm](https://cloud.githubusercontent.com/assets/2837721/11225200/2175e9fc-8d36-11e5-880d-3522b0636308.png)

**Comment by jarednova** [comment]
Thanks for the heads-up @jon-childs! I've got this fixed in #753

**Comment by jon-childs** [comment]
@jarednova Awesome, thanks!
