### ISSUE TITLE
WooCommerce Cart Page, Payment & User Login Template

### ISSUE THREAD

**Issue by maximaldesign** [jarednova/timber#755]
I followed the instructions on https://github.com/jarednova/timber/wiki/WooCommerce-Integration but how can i add the templates for the following pages:

- cart page/payment page
- user login page (where the user can see his orders)

thanks for help!

**Comment by maximaldesign** [comment]
nobody? :(

**Comment by ivanjuras** [comment]
I'd like to know that as well. Is this even possible?

**Comment by luizbills** [comment]
https://github.com/niklasravnsborg/blender-shop

**Comment by ivanjuras** [comment]
@jarednova is there any way for you to create a code snippet for cart, payment, login and other non-product pages in the WooCommerce integration part of the wiki? That would make it so,much easier for other developers: to find all the neccessary code in one place.

**Comment by connorjburton** [comment]
Hi,

Most of Woocommerce support/issues are being covered in #79 - ultimately we need a Woocommerce starter theme, however that will most likely come after 1.0 release.

I'm going to close this, if you could carry over discussion in #79 if necessary that'd be great.

Thanks
