### ISSUE TITLE
Conditional tags in Timber

### ISSUE THREAD

**Issue by petenorris** [jarednova/timber#756]
I am looking for a way to show content if the page is home page...

I have found the synax, but what to replace 'single' with?

{% if page == 'single' %}

Whilst I am here, is there a decent glossary of timber functions to match the WP functions they cover? I appreciate TImber is still new, but finding info seems to be difficult.

Many thanks.

**Comment by jnweaver** [comment]
Hi Peter,

The way I would handle this would be to use Wordpress's *is_home()* function to pass that boolean value through the Timber context via the *timber_context* filter. E.g.

```
function add_to_context( $data ){
  $data['is_home'] = is_home();
  return $data;
}
add_filter( 'timber_context', 'add_to_context' );
```

Then in your Twig view, assuming your PHP file calls `$data = Timber::get_context();`:

```
{% if is_home %}
```

**Comment by petenorris** [comment]
Great thanks for your time.
