### ISSUE TITLE
Extending TimberPost and TimberTerm

### ISSUE THREAD

**Issue by mrvudo** [jarednova/timber#766]
I have read the docs at https://github.com/jarednova/timber/wiki/Extending-Timber but it doesn't say where to add the file and then how to reference the file.

Anyone care to explain where the MySitePost file goes and how it is then called.

Thanks

**Comment by Jmayhak** [comment]
You could put the call in your theme's functions.php file

class MySitePost extends TimberPost
{
    public function getFoo() {
        return 'bar';
    }
}

// and then it's available in your page.php, single.php, etc and can be used
$mySitePost = Timber::get_post($post_id, 'MySitePost');

// use before rendering twig
echo $mySitePost->getFoo();

// or in the twig file
Timber::render('post.twig', array('post' => $mySitePost));

// post.twig
<h2>{{ post.getFoo }}</h2>

**Comment by enovision** [comment]
This is what I used in a plugin I created using Timber

```
// let's assume that the require below holds class 'timberExtendedPost'
require_once(YOUR_PLUGIN_DIR . '/classes/class.timber.php');

class myPlugin
{
	var $context = [];

	function __construct($instance, $isShortCode = false, $shortCode = '')
	{
		...
	}

	public function query($args = [])
	{
		global $timber;

		$queryArgs = array_merge([
			'post_type' => 'some-post-type',
			'showposts' => 12
		], $args);

		// watch this !!!
		// here we inject our own extended post with the extra's we
		// created on any post

		$this->context = array_merge($this->context, [
			'posts' => $timber::get_posts( $queryArgs, 'timberExtendedPost' )
		]);
	}
    
	public function renderContent()
    {
		global $timber;

		$template = $this->getTemplate();

		$output = $timber::compile($template, $this->context);

		return $output;

	}
...
}
```
