### ISSUE TITLE
Could anyone give me an example of a functions.php with an integrated sidebar?

### ISSUE THREAD

**Issue by petenorris** [jarednova/timber#767]
I have set the theme files as per https://github.com/jarednova/timber/wiki/Sidebar but I cannot get it to work. I imagine this is because I'm not registering the sidebar properly in functions.php as I am using standard non-timber method.
Not sure pasting my code here would be of any use, so if someone has an example as the timber theme doesn't have sidebars in the function.

Many thanks

**Comment by petenorris** [comment]
I have managed to work it out. Hope the following helps other non-programmers out there - (This is my main issue with timber documentation. Timber is built to simplify development and enable non-programmers to embrace it, but the docs are written for programmers.

First as per usual WP you must register the widget:

Functions.php
-------------

function _s_widgets_init() {
	register_sidebar( array(
		'name'          => 'Sidebar',
		'id'            => 'sidebar-1',
		'description'   => '',
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h1 class="widget-title">',
		'after_title'   => '</h1>',
	) );
}
add_action( 'widgets_init', '_s_widgets_init' );

Then you need to add to context in functions.php - (This function already exists and just needs to be added to existing)

function add_to_context( $context ) {
	$context['widget_area_1'] = Timber::get_widgets('sidebar-1');
	return $context;
}

(widget_area_1 is how it will be reference in twig below, whereas sidebar-1 is name of registered id when regisitering the widget - above)

Template
--------

Wherever you want the widget simply:

	<aside class="my-sidebar">
		{{widget_area_1}}
       </aside>

**Comment by jarednova** [comment]
Thanks for posting the solution @petenorris. I agree with you that working on documentation is a priority. @lggorman — can you update the sidebar docs that you're working on with @petenorris's info above?
