### ISSUE TITLE
Crop position with coordinates

### ISSUE THREAD

**Issue by lmartins** [jarednova/timber#772]
Now that WordPress will include support for responsive images builtin, it becomes possible to have some sort of art direction associated with our images, making the crop operation a bit more demanding. 

We currently can pass a position to our crop function, such as:
```twig
{{ thumbnail.src|resize(1200,320,'center') }}
```
Although really useful, it would be nice to have the option to integrate this with something like https://wordpress.org/plugins/my-eyes-are-up-here/

That plugin allows the site admin to add hotspots to an image, so that the image can be cropped in such a way that the hotspot remains visible.

The aforementioned plugin does not work with images cropped with Timber filters, so I am now looking for solutions to achieve something similar.

Have anyone tried this before?

**Comment by connorjburton** [comment]
Hi @lmartins - i'm going to close this as if we do come to this solution, it will probably involve Timmy in some way or another. Hope you don't mind.

**Comment by lmartins** [comment]
I don't mind at all, thank you for the feedback.
