### ISSUE TITLE
Timber cannot be activated as a network plugin (Notice: Undefined index: pagenow in /vagrant/app/wp/wp-includes/link-template.php on line 2742)

### ISSUE THREAD

**Issue by kvdnberg** [jarednova/timber#774]
When acitivating Timber on a multisite as a network plugin, the following notice is displayed on every page: 
Notice: Undefined index: pagenow in /vagrant/app/wp/wp-includes/link-template.php on line 2742

This is the stack trace.

( ! ) Notice: Undefined index: pagenow in /vagrant/app/wp/wp-includes/link-template.php on line 2742
Call Stack
#	Time	Memory	Function	Location
1	0.0079	245488	{main}( )	../index.php:0
2	0.1117	247248	require( '/vagrant/app/wp/wp-blog-header.php' )	../index.php:4
3	0.1117	247896	require_once( '/vagrant/app/wp/wp-load.php' )	../wp-blog-header.php:12
4	0.1129	248568	require_once( '/vagrant/app/wp-config.php' )	../wp-load.php:42
5	0.1144	368024	require_once( '/vagrant/app/wp/wp-settings.php' )	../wp-config.php:150
6	0.1708	1580944	include_once( '/vagrant/app/content/plugins/timber/timber.php' )	../wp-settings.php:180
7	0.1723	1582112	Timber->__construct( )	../timber.php:26
8	0.1742	1584056	Timber->init( )	../timber.php:59
9	0.1761	1604680	TimberImageHelper::init( )	../timber.php:81
10	0.1761	1604736	TimberImageHelper::add_constants( )	../timber-image-helper.php:22
11	0.1762	1604768	home_url( ???, ??? )	../timber-image-helper.php:178
12	0.1762	1605024	get_home_url( ???, ???, ??? )	../link-template.php:2709

**Comment by lmartins** [comment]
While im not sure what is going on here, just wanted to say I am using Timber as a Network Enabled plugin and have no issues with it. Perhaps something related to your install.

**Comment by beatelite** [comment]
Same here. Works fine for me on 4.4

**Comment by connorjburton** [comment]
Hi, @kvdnberg are you still experiencing this?

**Comment by connorjburton** [comment]
I am going to close this as I haven't had a reply. Feel free to comment at any point in time and I will re-open.
