### ISSUE TITLE
Is the latest, stable version available on WordPress Packagist ?

### ISSUE THREAD

**Issue by ltarasiewicz** [jarednova/timber#777]
Hello,

I want to manage my project dependencies with Composer. I wanted to fetch timber from wppackagst. The version that I found there is "dev-trunk". Is this the latest stable?

Thanks

**Comment by jarednova** [comment]
@ltarasiewicz make sure you get `timber-library` from WPPackagist ("Timber" was taken years ago by an unrelated project), here's the code I use in my `composer.json`s...

"wpackagist-plugin/timber-library":"0.22.*",

**Comment by prisis** [comment]
Or you use "jarednova/timber" : "~0.22" works fine :)

**Comment by Ciul** [comment]
Please change the type of the package to _wordpress-plugin_

**Comment by chrisvanpatten** [comment]
@Ciul Timber no longer is intended to be used as a WordPress plugin; it should be used as a standard composer dependency, loaded through an autoloader. This makes it easier to bundle with your code as a library, and makes it harder to mistakenly deactivate Timber when a theme depends on it.

**Comment by Ciul** [comment]
> @Ciul Timber no longer is intended to be used as a WordPress plugin; it should be used as a standard composer dependency, loaded through an autoloader. This makes it easier to bundle with your code as a library, and makes it harder to mistakenly deactivate Timber when a theme depends on it.

Oh got it. Thanks Chris!
