### ISSUE TITLE
Wordpress 4.4 - Responsive images and term meta

### ISSUE THREAD

**Issue by zcuric** [jarednova/timber#784]
Hi! Awesome plugin!

Will Timber support responsive images and term meta? Thanks.

**Comment by lmartins** [comment]
Hi @zcuric 

Regarding responsive images, I thunk your best bet for now is just to declare your images manually, something like:

```twig
<img
    src="{{ post.thumbnail.src|resize(480) }}"
    srcset="
        {{ post.thumbnail.src|resize(480) }} 480w,
        {{ post.thumbnail.src|resize(220) }} 220w
    "
    sizes="
        (min-width: 980px) 25vw,
        50vw
    "
    itemprop="image"
    alt="{{ variation.thumbnail.alt }}" />
```

You can also wrap the new WordPress functions to generate the srcset. Personally I prefer doing it manually to have a bit more control hover it, but both ways will work.

**Comment by connorjburton** [comment]
@lmartins seems to have answered this pretty well, going to close this for now.

**Comment by laras126** [comment]
In case anyone is looking for an example of the non-manual/function wrapping route to use core's responsive images:
```
<img src="{{function('wp_get_attachment_image_url', post.thumbnail.id, 'medium')}}" 
         srcset="{{function('wp_get_attachment_image_srcset', post.thumbnail.id, 'medium' )}}"
         sizes="(max-width: 1024px) 100vw, 1024px" alt="Post thumbnail">
```
Swap out post.thumbnail.id with the id of your desired image.
