### ISSUE TITLE
Timber::get_calling_script_file backtrace doesn't necessarily reference a file

### ISSUE THREAD

**Issue by gwagroves** [jarednova/timber#785]
https://github.com/jarednova/timber/blob/master/timber.php#L608

The `if` clause assumes that the `file` key exists, but `file` is only a **possible** key. (A callable is listed in the backtrace without `file` being set, causing an undefined index notice to be triggered.)

Solution: use `array_key_exists`.

**Comment by connorjburton** [comment]
Closing as this has been merged.
