### ISSUE TITLE
No errors or tracebacks in the new version 0.22.3

### ISSUE THREAD

**Issue by nanotime** [jarednova/timber#788]
Eh, well the thing is simple, there is not an error message or traceback when you make a mistake like write wrong a direction in the `include` sentence of twig. Instead you get a 500 in the browser, and this is serious.

I need to turn something on or of?

**Comment by jarednova** [comment]
@nanotime I don't recall disabling any debug output. Are you saying that now when you include a file that doesn't exist, it fails silently? (Whereas, before you would get a 500 error?)

**Comment by prisis** [comment]
You need to active WP_DEBUG like => define('WP_DEBUG', true);

**Comment by nanotime** [comment]
@jarednova when i make any mistake, it fails silently. I don't touched any, just make a clean instalation, put timber, debug-bar and debug-bar timber (as allways) and well, this is it, any error throws me a 500 page on my browsers.

@prisis ehm, i have no idea where is WP_DEBUG D:

**Comment by alenabdula** [comment]
@nanotime 

When you install WordPress it's always set to `define('WP_DEBUG', false);`

You can visit https://codex.wordpress.org/Editing_wp-config.php for more
