### ISSUE TITLE
global post in Timber::get_posts($args); loop

### ISSUE THREAD

**Issue by waltercruz** [jarednova/timber#792]
Not sure if it's the best place to ask for help... I have a page that list posts from 2 custom types (not an real archive, but kind of).

I have an: 
$posts = Timber::get_posts($args);

and a loop:

    	{% for post in posts %}
            {% include ['box-'~post.post_type~'.twig'] %}
    	{% endfor %}

In my post.content I have a shortcode. When I call get_post() inside it, I get the post id of the page, and don't the id of the current post. How I deal with it on timber? (I need to know the post id inside the shortcode)

**Comment by lmartins** [comment]
What arguments are you passing into `Timber::get_posts`? If you do a `var_dump` do you see both the post and page?

**Comment by connorjburton** [comment]
Hi @waltercruz - did you figure this out and if not could you provide the full code please? Thanks

**Comment by connorjburton** [comment]
Closing this for now as it seems to be inactive, feel free to comment and I will re-open.
