### ISSUE TITLE
Display categories archive for custom posts?

### ISSUE THREAD

**Issue by nanotime** [jarednova/timber#794]
Eh, i make the same question time ago, but i have no response. Anyway, i just want to make an archive for the categories attached to a custom post.

I have an `archive.twig` and it display the regular posts (*post_type=post*) but no the custom posts with the same category.

I tried something like this:

```php
$args = array(
    'post_type'   => 'custom',
    'tax_query' => array(
        array(
            'taxonomy' => 'category',
            'field'    => 'slug',
            'terms'    => 'finalizados',
        ),
    ),
);

$data['custom'] = Timber::get_posts($args);
```

In the `archive.php` and then iterate the array of "custom" in a `archive-finalizados.twig`... but nothing is displayed.

Any idea with the category archives, please? **I really need help here**, i tried and read a lot of things but nothing works for me... i'm completely stuck at this point.

**Comment by nanotime** [comment]
Well, the solution exists, but it's not evident... all you need here is to add some things to the `functions.php`.

First of all, this function:

```php
function add_custom_types_to_tax( $query ) {
    if( is_category() || is_tag() && empty( $query->query_vars['suppress_filters'] ) ) {

        // Get all your post types
        $post_types = get_post_types();

        $query->set( 'post_type', $post_types );
        return $query;
    }
}
```

**Note**: i tried to add this into the StarterSite Class, but it gives me an error "function does not exists", so i put the function outside of the class and that's all.

Then, into StarterSite Class, `__contrsuct`: `add_filter( 'pre_get_posts', 'add_custom_types_to_tax' );`

And that's all.

@jarednova it's possible to add that snippet for default in the next version of Timber?

**Comment by alenabdula** [comment]
@nanotime 

The reason the function didn't work inside the Class is because

`add_filter( 'pre_get_posts', 'add_custom_types_to_tax' );`

needs to be:

`add_filter( 'pre_get_posts', array($this, 'add_custom_types_to_tax') );`

When calling a method the second argument needs to be an array, specifying what Class and method to call.

Hope that helps

**Comment by connorjburton** [comment]
Hi @nanotime - as this has been solved, I'm going to go ahead and close this.

If you want to discuss this further feel free to jump into gitter
