### ISSUE TITLE
New release :)

### ISSUE THREAD

**Issue by prisis** [jarednova/timber#796]
Hey @jarednova, can you make a small new release with the last bug fixes?

Thanks,
Daniel

**Comment by lmartins** [comment]
So, what's new @prisis ? Anything interesting?

**Comment by prisis** [comment]
Yes :), this one #785

**Comment by jarednova** [comment]
@prisis — you got it, I'll run tonight

**Comment by prisis** [comment]
Many thanks, @jarednova
