### ISSUE TITLE
Problem with timber/twig/filters filter?

### ISSUE THREAD

**Issue by dudewithamood** [jarednova/timber#798]
This code, called within a Gantry5 particle in WordPress, causes an error:
```
{{ gantry.platform.call( 'Timber::compile_string', 'hi' ) }}
```
Commenting out this line 347 in timber.php of the function compile_string() allows it to work:
```
$twig = apply_filters( 'timber/twig/filters', $twig );
```
I can't find where the code is that handles this filter so have been unable to investigate further.

**Comment by newkind** [comment]
Just a note -
`gantry.platform.call`
is an aliast to Timbers
`function`

Hmmm I'll take a look at this error.

**Comment by connorjburton** [comment]
This is related to #863 and there seems be more info in the gantry issue that is referenced so I'm going to close this.
