### ISSUE TITLE
TimberHelper::function_wrapper not working for me

### ISSUE THREAD

**Issue by dennis-van-bennekom** [jarednova/timber#803]
Hello,

I am trying to use the TimberHelper::function_wrapper like this: 

```php
$context['get_src'] = TimberHelper::function_wrapper('wp_get_attachment_image_srcset');
Timber::render('templates/album.twig', $context);
```

But when I try to use the function in the template like this:

```html
{{ get_src(foto.id, 'medium') }}
```

It gives me a unknown function error: 
```
Fatal error: Uncaught exception 'Twig_Error_Syntax' with message 'Unknown "get_src" function in "templates/album.twig" at line 76.'
```

Any idea what the problem is?

Thanks!

**Comment by connorjburton** [comment]
Bit late but just saw this one. As far as I have used, ```TimberHelper::function_wrapper``` doesn't return a function, it adds it straight to ```Twig```.

So for this usage, you can just do:

```
TimberHelper::function_wrapper(_string_);
Timber::render('templates/album.twig, $context);
```

And then in your ```.twig```:

```
{{ wp_get_attachment_image_srcset(foto.id, 'medium') }}
```

**Alternatively**, I believe all the standard WP functions are accessible via ``fn()``, so you can just do:

``` {{ fn('wp_get_attachment_image_src', foto.id, 'medium') }}```

Without adding it to your context at all.

**Comment by dennis-van-bennekom** [comment]
Ahh alright, thanks for the help. I will try it soon. It is still useful for me :)

**Comment by connorjburton** [comment]
@dennis-van-bennekom did this work for you?

**Comment by dennis-van-bennekom** [comment]
@connorjburton yes it did. Thanks!
