### ISSUE TITLE
Resize based on height parameter ignoring width

### ISSUE THREAD

**Issue by ashrayer** [jarednova/timber#804]
Hi,

Happy New Year! and thank you for the Timber -- it made me happy with WP development again :)

One thing I wanted to ask -- is there any way to resize image to certain height (instead of width)? sometimes I need this feature. 
I know it is not difficult to implement, what method/function should I modify?

**Comment by jarednova** [comment]
You bet! Just send a `0` or `false` to the width parameter, and your desired height in pixels

**Comment by ashrayer** [comment]
Thanks!
P.S. Updated the docs https://github.com/jarednova/timber/wiki/TimberImage#arguments

**Comment by jarednova** [comment]
@lggorman — can you make sure this is reflected in the docblock/new docs?

**Comment by lggorman** [comment]
@jarednova Sure no problem!

**Comment by connorjburton** [comment]
This just needs docblock/new docs updated before we can close this
