### ISSUE TITLE
Support user taxonomies?

### ISSUE THREAD

**Issue by beatelite** [jarednova/timber#807]
Wordpress does support adding taxonomies to any object - including users. 

However, I'm not seeing the terms show up in the object when I use:
```
{{author|print_r}}
```

Any way you know of that I can get them to show?

**Comment by beatelite** [comment]
I suppose that using [wp_get_object_terms](https://codex.wordpress.org/Function_Reference/wp_get_object_terms) is what I need here. Any suggestions on how to achieve this in timber?

**Comment by jarednova** [comment]
@beatelite I'm not familiar with adding taxonomies to User objects. I've accomplished this before, but only using custom fields.

How does wp_get_object_terms distinguish between posts vs. users? for example if I were to call...

`wp_get_object_terms( 6, 'post_tag');`

... how does WP know if I want post #6 or user #6?

**Comment by beatelite** [comment]
Hi Jared, i'm looking at [this article:](https://tadpole.cc/blog/user-taxonomies-categorize-wordpress-users/)

I notice he's using a variable '$curauth' that's referencing the author: [https://gist.github.com/portfola/10750784#file-author-php-L27](https://gist.github.com/portfola/10750784#file-author-php-L27)

**Comment by beatelite** [comment]
ok so i tried this: 

```
global $wp_query;
$data = Timber::get_context();

$data['posts'] = Timber::get_posts();
if ( isset( $wp_query->query_vars['author'] ) ) {
    //$author = (get_query_var('author_name')) ? get_user_by('slug', get_query_var('author_name')) : get_userdata(get_query_var('author'));
	$author = new TimberUser( $wp_query->query_vars['author'] );
	$terms = wp_get_object_terms( $author->ID, 'languages_spoken' );
	$data['author'] = $author;
	$data['languages_spoken'] = $terms;
	$data['title'] = 'Author Archives: ' . $author->name();
}
Timber::render( array( 'templates/author.twig', 'templates/archive.twig' ), $data );
```

but I still don't see it when I use {{author|print_r}}

I do have the taxonomy set up properly as I can see it on the user profile in the admin and can select a language there. 

I'm sure I'm close but not sure where to go next.

**Comment by beatelite** [comment]
ok, figured this out. I used the code above and didn't realize that I needed to do {{languages_spoken|print}}

Done and done.
