### ISSUE TITLE
[question] Custom menu: extend TimberMenuItems or build one with get_posts?

### ISSUE THREAD

**Issue by mikmikmik** [jarednova/timber#808]
Hi, thanks for everyone involved in this really nice tool.
I'm using Timber for the first time in a new project and I'm wondering what would be the best way to make my menu work well with polylang and another field in the associated post that I want to check.

I made a menu with every pages inside wp, filter them with a function call inside the twig for loop on items to check the lang, but I have difficulties to access the post field associated with the menu item.

I thought maybe I should extend the TimberMenuItems class but not sure it is the right way... and where to put the code... in functions.php of my theme?
Also I considered building the "hierarchical menu" myself by querying all the pages and using args instead of trying to filter the menu after...

Any hint on good practice?

Cheers
mik

**Comment by lmartins** [comment]
As far as I can tell you have two options here:
1) Try to build the menu and rebuild any behaviours introduced by polylang
2) Just use the default WordPress functions

I use both cases, but as far a main navigation I tend to use the latter, something like:
```php
        // MENUS  -------------------------------------------------------------
        $defaults = array(
			'theme_location'  => 'primary',
			// 'menu'            => 'main_menu',
			'container'       => 'ul',
			'menu_class'      => 'Nav Nav--main',
			'echo'            => false,
			'fallback_cb'     => 'wp_page_menu',
			'items_wrap'      => '<div id="%1$s" class="%2$s">%3$s</div>',
			'depth'           => 0
		);
        $context['nav']['primary']  = wp_nav_menu( $defaults );
```

This can then be called in your twig file like this:
```twig
{{ nav.primary }}
```

You'll lose the convenience of Timber's custom walker, but will be easier to integrate 3rd party tools such as Polylang.

Hope this helps.

**Comment by acobster** [comment]
If the goal is to check meta fields on the corresponding post for each nav item, I see no reason _not_ to extend `TimberMenuItem`. It's more elegant IMO and gives your Twig views more control.

See this gist: https://gist.github.com/acobster/1545161136b1da584c5f

A useful next step might be to extend `TimberPost` itself so that you can abstract the translated properties (and whatever else you want to check on each post) away from Twig. For that, you simply define a `public $PostClass` property in both `CustomMenu` and `CustomMenuItem` that points to your child Post class. This makes sure that whenever your menu or one of its items creates a `TimberPost` object, it actually instantiates your child class.

**Comment by connorjburton** [comment]
Hi @mikmikmik - is this still an issue with the answers above?

**Comment by mikmikmik** [comment]
Thanks for your answers, I didn't have time to work again on this project and test to re-build the menus yet. 
This is how I did it in the first place, with a menu manually filled with all pages in all languages:
```php
// functions.php
class MySite extends TimberSite {
    function __construct() {
// ...
        add_theme_support( 'menus' );
        add_action( 'init', array( $this, 'register_menus' ) );
// ...
    }
    function register_menus() {
        register_nav_menus( array(
            'menu_lang' => 'Lang Menu',
            'menu_main' => 'Main Menu',
        ) );
    }
// ...
}
// ...
function is_lang( $post_id ) {
    $active_lang = pll_current_language();
    $post_lang = pll_get_post_language( $post_id );
    return $active_lang == $post_lang;
}
```

```twig
{# main-menu.twig #}
{% for l1_item in menu_main.get_items %}
    {# select only pages from active lang #}
    {% if function('is_lang', l1_item.object_id) %}
    <a class="ui inverted basic button{{'current' in (l1_item.classes | join(' ')) ? ' activepath'}}" href="{{l1_item.get_link}}">{{l1_item.title}}</a>
        {% for l2_item in l1_item.get_children %}
        <div class="level2">
            {% if not l2_item.get_children %}
            <a class="item{{'current' in (l2_item.classes | join(' ')) ? ' activepath'}}" href="{{l2_item.get_link}}">{{l2_item.title}}</a>
            {% else %}
                {# other levels #}
            {% endif %}
        </div>
        {% endfor %}
    {% endif %}
{% endfor %}
```
I know it is not really optimized so I'll try your ways asap.
Hi @connorjburton it was not really an issue it just needs to be coded the way I want it to work. I'll post my code here if I find a beautiful way to do it with extending the TimberMenu class.
