### ISSUE TITLE
strpos() warning in Timber::render first parameter

### ISSUE THREAD

**Issue by lmartins** [jarednova/timber#809]
Hi,

I've getting a lot of New Relic warnings related to this line:
```
Timber::render(array('page-' . $post->post_name . '.twig', 'page.twig'), $context);
```
The warnings say:
```
[06-Jan-2016 14:22:17 UTC] PHP Warning:  strpos() expects parameter 1 to be string, object given in /Users/luismartins/Sites/webipack.dev/wp-includes/query.php on line 4534
```

But these only happen when Im navigating the site via customizer.  The regular front-end don't trigger any warning.

Any tips?

**Comment by connorjburton** [comment]
Hi @lmartins - i'm not getting this on the starter theme, are you sure it's from that line? Are you able to provide access to a repo so I can replicate this?

**Comment by lmartins** [comment]
Haven't seen this for a while and honestly have since forgot about this issue. Closing for now. 
Many thanks.
