### ISSUE TITLE
Issues using the Live Customizer with Browser-Sync

### ISSUE THREAD

**Issue by JakeHenshall** [jarednova/timber#817]
Hi,

I don't seem to be getting a live customizer preview when i'm using both together.

I don't think its a timber thing though. When I don't use browser-sync it works fine.

<img width="1093" alt="timber-browser-sync-error" src="https://cloud.githubusercontent.com/assets/4720782/12251830/d2208262-b8c9-11e5-8819-5991a05c18ad.png">

Any help is much appreciated.

Jake.

**Comment by connorjburton** [comment]
As you said, it doesn't seem to be Timber, you aren't connecting to the same port so you are getting cross domain issues.

Closing this issue, feel free to comment if you do think it's Timber.
