### ISSUE TITLE
Comments Link

### ISSUE THREAD

**Issue by adi8i** [jarednova/timber#818]
Hello. 

I can use `comment_count` to display the number of comments, but is possible to link this count to article page comments?

I showcase latest 3 posts on homepage, here i want to add the link to full page comments.

`{{ post.link }}#comments` worked but i find this a trick, not sure if is a proper way.

**Comment by alenabdula** [comment]
@adi8i I wouldn't consider that as a trick. You're using anchors, something that web has supported for years.

`#comments` is fragment identifier

See: https://www.w3.org/TR/html401/struct/links.html

**Comment by adi8i** [comment]
Yeah, I stick with that, i thought there's a syntax something like `coment_link` too. :)
