### ISSUE TITLE
What about internationalisation?

### ISSUE THREAD

**Issue by senlin** [jarednova/timber#821]
I am just reading the introduction to Timber and it all looks pretty cool, but my immediate concern is regarding internationalisation.

Taking a sample from the documentation:
```
$context = array();
$context['welcome'] = Timber::get_post(56);
Timber::render('welcome.twig', $context);

<section class="welcome-block">
    <div class="inner">
        <h3>{{welcome.post_title}}</h3>
        <p>{{welcome.get_content}}</p>
        <p>Follow me on <a href="https://twitter.com/{{welcome.twitter_handle}}" target="_blank">Twitter!</a></p>
    </div>
</section>
```

How can a sentence like `Follow me on ...` become translated in other languages?

**Comment by ogrosko** [comment]
Check this [link](https://github.com/jarednova/timber/wiki/Text-Cookbook#internationalization)

**Comment by senlin** [comment]
Wow, so simple, huh? Thanks @ogrosko
