### ISSUE TITLE
Images with special sign not resized

### ISSUE THREAD

**Issue by ogrosko** [jarednova/timber#822]
Hi
When I want to resize image which name contains some special signs e.g. ® Images are not resized
I use this code
```
<img src="{{TimberImage(image)|resize(158, 202)}}" alt="some alt" class="img-responsive">
```

Images with name `®-some-image-name.jpg` are not resized

**Comment by connorjburton** [comment]
Hi @ogrosko, does it render the image if you don't resize?

**Comment by ogrosko** [comment]
@connorjburton Yes without resizing it works

**Comment by connorjburton** [comment]
Okay thanks, I'll put this on my list

**Comment by connorjburton** [comment]
Hi @ogrosko - I've investigated this pretty thoroughly and can't seem to replicate this bug. I created an image `©test.png` and it resized it correctly.

I've traced this all the way back through to the `wp-http` class that is just a wrapper around `curl` and couldn't find any obvious that'd cause this.

One test is to check that your server can actually serve that URL, if you go to the image in the browser that you want to resize and see if it displays it?

**Comment by ogrosko** [comment]
Hey
I also test it on fresh new wordpress instance and I can confirm it works. 
But with the existing project it´s problem :(  It´s seems not to be timber problem in other words not your  problem :) 

I have to investigate it
Thanks for the help and sorry for troubles
