### ISSUE TITLE
date function is inserting a dot

### ISSUE THREAD

**Issue by waltercruz** [jarednova/timber#826]
{{post.post_date|date('Y-M-d')}} ir returning something like 2015-jan.-17, with a dot in the end of the month. My locale is pt_BR. I would like to return it WITHOUT the dot. 

(Sorry if it's not the best place to ask, couldn't find anything better)

**Comment by connorjburton** [comment]
Hi @waltercruz - I have tried this on VVV however I can't seem to replicate the issue. (See screenshot)

Perhaps you could provide an `.sql` file of the post this happening on, maybe the data is corrupt?

Thanks

**Comment by connorjburton** [comment]
A long shot (I don't know too much about locales), you could try do (assuming ubuntu here) `sudo locale-gen pt_BR`

**Comment by waltercruz** [comment]
Hum... I'm on mac OS.

I 'solved' it with a string replace, replacing the dot.

**Comment by connorjburton** [comment]
Okay, sorry I can't fix it but doesn't seem to be an issue with Timber.

**Comment by waltercruz** [comment]
don't know if it's really timber... If I change the locale to another one, I got the month name without dot. will investigate

**Comment by waltercruz** [comment]
The problem seems to be on wordpress (or more exactly, on pt_BR i18n team)

https://core.trac.wordpress.org/ticket/36053

Thanks!
