### ISSUE TITLE
PHP Warning.../timber-twig.php on line 220

### ISSUE THREAD

**Issue by AlchemyUnited** [jarednova/timber#832]
PHP Warning: in_array() expects parameter 2 to be array, null given in /.../wp-content/plugins/timber-library/lib/timber-twig.php on line 220

Version 0.22.5

Hosting is WP Engine, if for some reason that matters.

**Comment by jarednova** [comment]
Nice to know; we host w them so generally I know their stack pretty well. Any idea what line in the twig template is calling that? Line 220 has do with PHP function execution

**Comment by AlchemyUnited** [comment]
No idea. I can only assume that there needs to be an is_array() somewhere prior. 

It's just a warning. But still.

**Comment by connorjburton** [comment]
Hey @AlchemyUnited - I don't think we can fix this without more information, I've taken a look at that function and it could do with some more stringent checks however there isn't an `in_array` call in there, maybe that error is been thrown from whatever function `call_user_func_array` is calling?

I'm going to close this for now, if you do get more information about the line that twig is calling to cause this then comment and I will re-open and take a look.

Thanks

**Comment by AlchemyUnited** [comment]
well, I would say, at the very least the "array" should be checked before the in_array(). I'm not sure what else you want me to tell you. We're running the plugin and it's logging this warning.

**Comment by connorjburton** [comment]
Oh absolutely, but when I look in `timber-twig.php` there doesn't seem to be an `in_array` call in the whole file? That's why I am confused

That's why I am wondering if the error is actually in the function that `call_user_func_array` is calling.

**Comment by AlchemyUnited** [comment]
OOOH :)

Ok. If that client ever comes back from the dead I'll have a look. Maybe it was logged from an older version and I never noticed? Or maybe the error is in call_user_func_array () but the log isn't clear?

In any case, I get it. I'll look again if it comes up. Thanks.

**Comment by connorjburton** [comment]
Possibly could be a bad error from `call_user_func_array`, it does call it like `call_user_func_array( $function_name, ( $args ) )` which I am unsure on why there are parentheses wrapping `$args`

If you do get more info just drop a comment on here and I'll look into it

**Comment by yooDesign** [comment]
I have added just an if statement to check if $function_name exists.

`function exec_function( $function_name ) {
		$args = func_get_args();
		if($function_name!=''){
		array_shift( $args );
		if ( is_string($function_name) ) {
			$function_name = trim( $function_name );
		}
		return call_user_func_array( $function_name, ( $args ) );
		}
		else return false;
	}`
