### ISSUE TITLE
Move class Timber to separate file in lib/

### ISSUE THREAD

**Issue by mrgrain** [jarednova/timber#833]
For some reason the `Timber` class within [timber/timber.php](https://github.com/jarednova/timber/blob/master/timber.php#L30) is the only class not located in lib/ preventing the library from being fully autoloaded.

Moving the class to its own file in lib/ will not change the package behaviour at all.

I'll create a PR for this issue.

**Comment by jarednova** [comment]
Thanks @mrgrain — I'm still learning some autoloading stuff so I appreciate the heads-up and the explanation

**Comment by jarednova** [comment]
Merged! Thanks again for the PR!
