### ISSUE TITLE
Preview Changes and TimberPost

### ISSUE THREAD

**Issue by rwstone** [jarednova/timber#836]
Thanks for Timber!

I was having problems previewing changes in the admin. The preview showed the published version rather than the changes. 

I replaced
`$post = new TimberPost();`
with
`$post = Timber::query_post();`
in all my php files except for the blog home. That seems to fix the issue. 

However, I don't want to introduce new problems to my theme, changing things I don't fully understand, so I thought I'd ask about this behavior here.

Is this a TimberPost bug, a feature, or a subtlety I haven't grasped yet?

Thanks!

(On a related note, it seems like you need to use `post.get_field('field')` rather than `post.field` on _all_ field types to properly preview ACF changes. That makes sense, but it wasn't clear to me from the ACF Cookbook.)

**Comment by connorjburton** [comment]
This is solved and merged.
