### ISSUE TITLE
Routes do not fire with mapped within init action

### ISSUE THREAD

**Issue by parisholley** [jarednova/timber#845]
If you do the following

```
add_action('init', function () {
    Routes::map('url', function () {});
});
```

The route is never invoked

**Comment by jarednova** [comment]
Thanks @parisholley! I just saw yr PR come in; let's pick up the conversation there and then once things are good close the issue:

https://github.com/Upstatement/routes/pull/1

**Comment by jarednova** [comment]
closed by https://github.com/Upstatement/routes/pull/2, thanks @parisholley!
