### ISSUE TITLE
Making it work with other plugins

### ISSUE THREAD

**Issue by mamarilmanson** [jarednova/timber#846]
I happen to plan on using this plugin: https://wordpress.org/plugins/wp-listings/

and I also want to use timber... how would it be possible to output data in a custom design using twig/timber? :)

**Comment by jarednova** [comment]
Hi @mamarilmanson for general questions like this please post to StackOverflow: http://stackoverflow.com/questions/tagged/timber

However, it's very tough to provide support for each plugin combo w Timber. I can tell you that in general once data is available as an array or object it's very easy for Timber to loop through and display it; you might need to look into some of the plugin internals to figure out which methods return pure data as opposed to markup

**Comment by mamarilmanson** [comment]
Thanks... will head to stackoverflow now... :)
