### ISSUE TITLE
TimberFunctionWrapper has problems with Namespaces

### ISSUE THREAD

**Issue by PhilippBaschke** [jarednova/timber#854]
If I just use the `TimberFunctionWrapper` in an unsupported way: Sorry and please tell me. :)

I wanted to make a **static function** available in the context by doing this:

```PHP
$context["helper"] = new \TimberFunctionWrapper(
      "Name\\Space\\Class::staticHelperFunction",
      ["should_be_set_from_twig", "default", "default2"]
);
```
and expexted that I can use it in Twig like this:
```twig 
{{ helper }}
```
(Works)
```twig
{{ helper("first_parameter") }}
```
(Does not work because Twig does not have a `helper` function (only `Name\Space\Class::staticHelperFunction`))

I helped myself by **extending** `TimberFunctionWrapper` and supporting a **fourth parameter** `twig_function_name` that is passed as a first parameter into the `Twig_SimpleFunction` constructor (instead of `$this->_function`) in `add_to_twig`. See: [timber-function-wrapper.php](https://github.com/jarednova/timber/blob/master/lib/timber-function-wrapper.php#L41)

**Comment by connorjburton** [comment]
I'm looking to do a PR for #843 soon, but will look at this use case too when doing it.

**Comment by PhilippBaschke** [comment]
Thank you @connorjburton! :+1:

**Comment by connorjburton** [comment]
@PhilippBaschke look at for this in a Timber release whenever that will be. Should solve your issues, and see PR for usage

**Comment by PhilippBaschke** [comment]
Thank you very much @connorjburton! :+1: :blush:
