### ISSUE TITLE
Noob question concerning TimberMenu

### ISSUE THREAD

**Issue by swthate** [jarednova/timber#855]
Hi folks,

This if my first time trying out Timber and I have what is likely a noob question about `TimberMenu`.

I created a new, small menu: `main-menu`. I read the [menu page on the Wiki here](https://github.com/jarednova/timber/wiki/TimberMenu), and noticed it says to create a new `add_to_context` function with a `$data` param. I'm confused, why is this different from the already existent function `add_to_context` in functions.php that uses a `$context` param? So, my first question is: what's the difference here between `$data` and `$context`?

My second question/problem is my menu is simply not displaying. All that is showing is a link to Sample Page. I tried passing my menu slug to `new TimberMenu()`, but that doesn't do anything. Sample Page is still the only item in the menu. Do I need a menu location? Is there a specific location within functions.php I need to place `function add_to_context($data)` as shown in the Wiki? Right now I just have it at the end of my functions.php file.

Thanks!

**Comment by connorjburton** [comment]
I assume you are using the default theme? If your `functions.php` already contains an `add_to_context` function you can just add the menu inside that method, there won't be any difference between `$data` and `$context` other than the names, they are both just referring to the data that gets added to the context.

You can add this to your `add_to_context` function to add all menus to your context:

```
foreach(get_registered_nav_menus() as $k => $v) {
    $context['menu_' . $k] = new TimberMenu($k);
}
```

So if you have `header` and `footer` as menus, they are accessible in the template via `menu_header` and `menu_footer`.

To use the menu in a template, see an example below:

```
<ul>
	{% for item in menu_header.get_items %}
		<li class="nav-item {{item.classes | join(' ')}}">
			<a class="nav-link" href="{{item.get_link}}">{{item.title}}</a>
			{% if item.get_children %}
				<ul class="nav nav-drop">
					{% for child in item.get_children %}
						<li class="nav-drop-item">
							<a class="nav-link" href="{{child.get_link}}">{{child.title}}</a>
						</li>
					{% endfor %}
				</ul>
			{% endif %}
		</li>
	{% endfor %}
</ul>
```

**Comment by swthate** [comment]
Thanks for your reply, @connorjburton but oddly I can't get it to work still.

I deleted my menu, created a new one named "header" just to be safe, and use exactly what you used in functions and copied your navigation markup, but it still just grabs "sample page" for me. I even tried cloning the starter theme from GitHub and starting completely fresh, but it acts the same way.

Yes, sorry. I am using the default theme. The only thing I've changed is I have ACF plugin and Posts2Posts plugin installed, added some custom post types to my functions, but that's it.

Even if I remove my custom post types it still doesn't work properly. I'm not sure what I could be doing to interfere with it :(

**Comment by connorjburton** [comment]
Have you registered the menu in your functions.php? I'm not able to look anything up atm but that's one thing I think I did that you may be missing.

I can take a look properly tomorrow evening, in the mean time could you gist your full functions.php file please?

**Comment by swthate** [comment]
No, I haven't registered any menus. I assumed, maybe foolishly, that `$context['menu'] = new TimberMenu();` would handle that.

Here's my gist, but it's virtually identical to the same functions.php file found in the starter theme: https://gist.github.com/swthate/9f93e304c0b4fd7f1e12

Thanks for your help :+1:

**Comment by connorjburton** [comment]
Try registering some menus with `register_nav_menus`

**Comment by acobster** [comment]
Yeah, I think Connor is right: you still need to register your menu so that WP knows about it in the first place. See my [fork](https://gist.github.com/acobster/82346790be3f66c7d02d) of your gist.

The key here is the `$location` parameter (in this case `"primary"`). It acts like a pointer to a specific menu, so your code can talk about "the menu at this location" instead of referring to the menu directly.

**Comment by swthate** [comment]
Thanks guys! (Sorry, lost track of this as other projects came up)

@acobster , I got your solution to work by changing it just a little, to `register_nav_menu('primary', 'Primary Menu');`. Thanks a bunch! This was embarrassingly simple :)
