### ISSUE TITLE
How do I add Posts2Posts to my context?

### ISSUE THREAD

**Issue by swthate** [jarednova/timber#864]
I'm using the [Posts2Posts](https://github.com/scribu/wp-posts-to-posts) plugin to handle relationships between different custom post types.

As this is my first time really using Timber, I'm pretty much at a loss as to how to add this to my `$context` for, say, `single-clients.php`.

Here is the standard PHP code I have working in my non-Timber theme:

```php
<!-- Connected Objects from Posts 2 Posts plugin -->
<?php
$connected = new WP_Query( array(
  'connected_type' => 'job_to_client',
  'connected_items' => get_queried_object(),
  'nopaging' => true,
) );

if ( $connected->have_posts() ) : ?>
  <h3>Client:
  <?php while ( $connected->have_posts() ) : $connected->the_post(); ?>
    <a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
  <?php endwhile; ?>
  </h3>
<?php // Prevent weirdness
wp_reset_postdata();
endif; ?>
```

Let's say I have a pretty standard single.php:
```php
$context = Timber::get_context();
$post = Timber::query_post();
$context['post'] = $post;
```

How and where would I inject into this context the custom query that looks for all related posts of the current post?

Thanks!

**Comment by connorjburton** [comment]
I don't have access to the codebase right now but just wanted to reply, I am assuming Post 2 Post extends WP Query, which means you could simply do the following:

```
$context['connected'] = Timber::get_posts(array(
    YOUR WP QUERY ARRAY HERE
));
```

Which you can then loop over in a template:

```
{# for post in connected #}

{# endfor #}
```

This is a guess from memory, give it a try and see if it works. If not let me know and I'll investigate further. Apologises for any syntax errors as I'm on mobile.

**Comment by connorjburton** [comment]
Just installed the plugin, set it up and gave it a test, this worked for me (I had my contact page linked to Post 3 and it worked)

```php
$connected = Timber::get_posts(array(
	'connected_type' => 'posts_to_pages',
	'connected_items' => get_queried_object(),
	'nopaging' => true
));

$context['connected'] = $connected;
```

**Comment by swthate** [comment]
Sweet! Thank you so much.

Timber is getting cooler every day :sunglasses:
