### ISSUE TITLE
Issue with the datefilter

### ISSUE THREAD

**Issue by Langstra** [jarednova/timber#867]
When using the datefilter the timezone is completely omitted. For instance, I inserted the DateTime object with the timezone "Europe/Amsterdam", the time was 21.30. Now it converts this with gettimestamp() to an integer. Here is omits the timezone. Afterwards the time is printed as 20:30. 

A solution could be the following code:
`if ( $date instanceof DateTime ) {
   $timestamp = $date->getTimestamp() + $date->getOffset();
} else if (is_numeric( $date ) && strtotime( $date ) === false ) {
   $timestamp = intval( $date );
} else {
   $timestamp = strtotime( $date );
}`

**Comment by connorjburton** [comment]
Hi @Langstra, thanks for this. Could you please post full error reproducible code so I can look into this? Thanks

**Comment by Langstra** [comment]
PHP-code
`
$date = new DateTime("now", new DateTimeZone("europe/amsterdam"));
echo $date->format("d F \\a\\t G:i");
return Timber::compile('partials/signup_closed.twig', array('date' => $date));
`
Timber template
`
<br>
{{ date|date("d F \\a\\t G:i") }}
`
The timezone of $signup_open is ignored and the dates have one hour difference.

**Comment by connorjburton** [comment]
Okay have tested this and implemented a fix, just need to write a test then will submit a PR.

**Comment by connorjburton** [comment]
Merged
