### ISSUE TITLE
[Discussion] GitHub Issue Template Discussion

### ISSUE THREAD

**Issue by jarednova** [jarednova/timber#870]
GitHub now allows for [issue templates](https://help.github.com/articles/creating-an-issue-template-for-your-repository/). I'm very interested in implementing this to help spur better issues and point general support questions to [StackOverflow](http://stackoverflow.com/questions/tagged/timber). GitHub has a sample of what a sample issue template could look like, which I actually like quite a bit:

```md

### Expected behavior

### Actual behavior

### Steps to reproduce behavior

```

My only additions would be some guidelines and a little more detail

```md

### Expected behavior
Please describe what output you expect to see from Timber

### Actual behavior
Please describe what you see instead. Please provide samples of HTML output or screenshots

### Steps to reproduce behavior
Please include complete code samples in-line or linked from [gists](https://gist.github.com/)

### What version of WordPress, PHP and Timber are you using?
Example: WordPress 4.4.1, PHP 5.4, Timber 0.22.5

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Example: Upgraded to newest version via plugin updater in WordPress dashboard

```

@connorjburton — what thoughts/changes/edits do you have to this?

**Comment by connorjburton** [comment]
Pretty much exactly what I was thinking (with a couple of extras!), the only minor thing I would say is to put the descriptions in  which will hide that text when the issue is submitted.

Good job

**Comment by jarednova** [comment]
wooohooo!
