### ISSUE TITLE
Trying to call a certain post

### ISSUE THREAD

**Issue by chaladm** [jarednova/timber#875]
Hi all,
I'm trying to just call a certain post from this custom post type.
I am using Gantry5.

Right now I'm able to call all the posts for a certain post_type with this call
{% set posts = wordpress.call('Timber::get_posts', {post_type: 'detachedhome'}) %}

I tried different ways to do an array with this function but it's not working. Seeing maybe I'm doing something wrong.

**Comment by connorjburton** [comment]
Hi @chaladm, if you want to call just one post from the post type and you know the ID then you can do

`{% set posts = wordpress.call('Timber::get_post', IDHERE) %}`

**Comment by connorjburton** [comment]
Hi @chaladm - do you have any updates on this please?

**Comment by chaladm** [comment]
It uses the same calls from wp query

{% set posts = wordpress.call('Timber::get_post', p: IDHERE) %} 

Then do a {% for post in posts %}

Works fine.
