### ISSUE TITLE
Specific ACF field (nested ACF)

### ISSUE THREAD

**Issue by januarian** [jarednova/timber#878]
Hi everyone,

I just started web development some months ago, and really like how timber simplifies wordpress templating. I have a few questions about ACF repeater fields and Timber, I hope github is the right place for this.

I'm working on  a website where most pages consist of a number of rows with content in them, I'd like my clients to be able to easily fill these rows. I've now added seperate acf fields, but this is not an ideal solution since now a lot of pages have big unpopulated WYSIWYG fields in the page editor, because the number of content rows is not the same on each page.

Therefore I would like to use repeater fields like normal custom fields, would it be possible to use the fields outside of a loop like so?(just a simplified example):

<div>
   <div>
      {{repeater_parent.child_1.image_1}}
   </div>
   <div>
      {{repeater_parent.child_1.wysiwyg_1}}
   </div>
<div>

<div>
   <div>
      {{repeater_parent.child_2.image_1}}
   </div>
   <div>
      {{repeater_parent.child_2.wysiwyg_1}}
      {{repeater_parent.child_2.image_1}}
   </div>
<div>

Currently I only see people using them in loops. I cannot conveniently use them in a loop since the layout of each row is so different (different classes, images bootstrap cols etc.) Maybe timber can be extended with some sort of method to call certain fields by number?

I'm not a twig/php hero yet so my mind just freezes whenever I try to code a solution myself.

Cheers,
Max

**Comment by connorjburton** [comment]
You certainly can, see below

```twig
{{ repeater_parent.0.image }}
```

Let me know if that doesn't work.

P.S This probably would be best suited for the stackoverflow archive, but i'll let you off ;)

**Comment by januarian** [comment]
Thank you, it took some time to get it to work. This works:
    {% set foo = post.get_field('repeater_outer') %}
    {{foo.0.repeater_inner.0.wysiwyg_child}}

And this works:
    {{ post.get_field('repeater_outer').0.repeater_inner.0.child_field }}

These doesn't work however:
    {{foo.0.repeater_inner.0.wysiwyg_child}}

**Comment by connorjburton** [comment]
Hm, the last example you posted is the same as the first example? Unless you mean without the `{% set foo = post.get_field('repeater_outer') %}`, then no, it won't work as you need to get the field first.

**Comment by januarian** [comment]
No I guess it's logical. Thanks for the great support!

**Comment by connorjburton** [comment]
No problem, any time
