### ISSUE TITLE
TimberImageHelper::delete_generated_files doesn’t delete jpg files created through tojpg filter

### ISSUE THREAD

**Issue by gchtr** [jarednova/timber#894]
### Expected behavior
`TimberImageHelper::delete_generated_files()` should automatically delete **all** generated image sizes when an attachment is deleted.

### Actual behavior
Some JPG files are not deleted, when they were generated through [`tojpg` Twig filter](https://github.com/jarednova/timber/wiki/Image-cookbook#converting-images) that was used on a PNG file.

### Steps to reproduce behavior
1. Upload PNG image to Media Library.
2. Assign PNG to post as featured image.
3. Bring featured image into template through `<img src="{{post.thumbnail.src|tojpg|resize(200, 200)}}">`
4. Check if JPG file with dimensions 200x200 is present in `wp-content/uploads` folder.
5. Choose ***Delete permanently*** on uploaded PNG in Media Library.
6. Check for JPG file with dimensions 200x200 still present in `wp-content/uploads` folder.

### What version of WordPress, PHP and Timber are you using?
WordPress 4.4.2, PHP 5.6.10, Timber 0.22.5

### How did you install Timber?
Upgraded to newest version via plugin updater in WordPress.

**Comment by jarednova** [comment]
@gchtr: thanks for filing this detailed issue (and using the issue template, it really helps us zero-in on the problem quickly and provide a patch). @connorjburton made changes to the code and submitted a PR in #897 that resolves the issue. Thanks to you both for making the fix happen!

**Comment by gchtr** [comment]
@jarednova @connorjburton Thanks for the fix! I think the issue template works really well, for both sides.
