### ISSUE TITLE
menu item attr_title & description?

### ISSUE THREAD

**Issue by jmp909** [jarednova/timber#903]
Hi,

Timber doesn't seem to expose certain attributes in the menu loop that can be added in Wordpress  specifically i want a title attribute (attr_title) in my menu link 

`<a href="{{item.get_link}}" title="{{item.attr_title}}">{{item.title}}</a>`

(if you open 'screen options' on /wp-admin/nav-menus.php you get access to these:)

- Title 
- Attribute 
- Link Target 
- CSS Classes 
- Link Relationship 
- (XFN) Description

thanks for any advice
j

### Expected behavior
[attr_title] => 'title string defined for menu item in the edtior'
[description] => 'description string defined for menu item in the editor'

### Actual behavior
[attr_title] => 
[description] => 

### Steps to reproduce behavior
{{ item.attr_title }} in menu loop

### What version of WordPress, PHP and Timber are you using?
WordPress 4.4.2, PHP 5.5.12 Timber 0.22.5

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Upgraded to newest version via plugin updater in WordPress dashboard

**Comment by jmp909** [comment]
(for reference here's why you might want a description as well: http://www.wpbeginner.com/wp-themes/how-to-add-menu-descriptions-in-your-wordpress-themes/)

**Comment by jmp909** [comment]
sorry. i'm being really stupid. i was editing a different copy of the site :S it's fine

**Comment by connorjburton** [comment]
No problem, thanks for closing.
