### ISSUE TITLE
Twig Template Editor

### ISSUE THREAD

**Issue by sc0ttkclark** [jarednova/timber#97]
It would be great to give clients access to edit certain Twig templates instead of full theme editor access. You could potentially do a CodeMirror editor too, in which you can provide custom auto-completion based on your own theme's framework traversal! Yes, there's a "!" there, because that would just be amazing for users and developers alike. At that point, you may want to offer a way to *create* new twig templates as well :)

**Comment by connorjburton** [comment]
Hey all, I know this is really old but I'm cleaning up the issues list. If anyone has made progress on this please let me know.

**Comment by DRogueRonin** [comment]
I just made a plugin right here:
https://gitlab.com/DRogueRonin/wp-plugin-timber-editor

You can edit twig files in the theme & plugin editor and create and edit templates for individual pages/posts/cpts.
Currently waiting on review to be added to the wordpress plugin repository.

**Comment by jarednova** [comment]
This is great @DRogueRonin! Please follow-up with the link to the WP.org release and we'll tweet about it from the @TimberWP account to let the world know!

**Comment by DRogueRonin** [comment]
@jarednova Here's the WP.org link: https://wordpress.org/plugins/editor-for-timber/

May I use a Timber logo/icon/banner for the plugin as well?

**Comment by jarednova** [comment]
Yes, please do @DRogueRonin! Let me know if you need anything specific
